import {
  pgTable,
  text,
  timestamp,
  uuid,
  integer,
  boolean,
  unique,
  uniqueIndex,
  index,
  check,
  pgEnum,
  jsonb,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { WordItemComment } from "@/lib/word-item-comment";

// Enums
export const translationStatusEnum = pgEnum("translation_status", [
  "manual",
  "pending",
  "translated",
  "failed",
]);

export const audioStatusEnum = pgEnum("audio_status", [
  "none",
  "pending",
  "ready",
  "failed",
]);

export const storageTypeEnum = pgEnum("storage_type", ["arweave", "r2", "object_store"]);

export const storageProviderEnum = pgEnum("storage_provider", ["b2"]);

export const mediaTypeEnum = pgEnum("media_type", ["audio"]);

export const ttsProviderEnum = pgEnum("tts_provider", [
  "google_tts",
  "elevenlabs",
]);

export const apiKeyProviderEnum = pgEnum("api_key_provider", [
  "openrouter",
  "elevenlabs",
]);

export const googleApiScopeEnum = pgEnum("google_api_scope", [
  "translate",
  "tts",
]);

export const schoolPlanEnum = pgEnum("school_plan", ["pilot_v1"]);

export const schoolStatusEnum = pgEnum("school_status", [
  "active",
  "inactive",
]);

export const schoolRoleEnum = pgEnum("school_role", [
  "student",
  "teacher",
]);

export const schoolFeatureEnum = pgEnum("school_feature", [
  "ai_translation",
  "photo_lab",
]);

export const schoolTranslationRequestStatusEnum = pgEnum(
  "school_translation_request_status",
  ["reserved", "completed", "released", "unknown", "failed_charged"],
);

// Word lists - container for vocabulary sets
export const wordLists = pgTable(
  "word_lists",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ownerId: uuid("owner_id").references(() => users.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    description: text("description"),
    languageFrom: text("language_from").notNull(),
    languageTo: text("language_to").notNull(),
    isPublic: boolean("is_public").notNull().default(false),
    isCommon: boolean("is_common").notNull().default(false),
    isRecommended: boolean("is_recommended").notNull().default(false),
    isAutogenerated: boolean("is_autogenerated").notNull().default(false),
    // Capability token for share links. Null = not shared. Generated on demand;
    // rotating it (reset) invalidates old links. Never exposed in normal list
    // responses — only through the owner-only /share endpoints.
    shareToken: text("share_token"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("word_lists_owner_idx").on(table.ownerId),
    index("word_lists_public_idx").on(table.isPublic),
    index("word_lists_common_idx").on(table.isCommon),
    index("word_lists_recommended_idx").on(table.isRecommended),
    uniqueIndex("word_lists_share_token_unique")
      .on(table.shareToken)
      .where(sql`${table.shareToken} is not null`),
    uniqueIndex("word_lists_recommended_pair_unique")
      .on(
        sql`(case when lower(${table.languageFrom}) in ('cz', 'cs') then 'cs' else lower(${table.languageFrom}) end)`,
        sql`(case when lower(${table.languageTo}) in ('cz', 'cs') then 'cs' else lower(${table.languageTo}) end)`,
      )
      .where(sql`${table.isRecommended} = true`),
  ],
);

// Word categories - sections within a list
export const wordCategories = pgTable(
  "word_categories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listId: uuid("list_id")
      .notNull()
      .references(() => wordLists.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    position: integer("position").notNull().default(0),
    isSystem: boolean("is_system").notNull().default(false),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("word_categories_list_pos_idx").on(table.listId, table.position),
  ],
);

// Media assets - shared audio pool (content-addressed)
export const mediaAssets = pgTable(
  "media_assets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contentHash: text("content_hash").notNull(),
    storageType: storageTypeEnum("storage_type").notNull(),
    storageProvider: storageProviderEnum("storage_provider"),
    storageRef: text("storage_ref").notNull(),
    mediaType: mediaTypeEnum("media_type").notNull().default("audio"),
    language: text("language").notNull(),
    textReference: text("text_reference").notNull(),
    provider: ttsProviderEnum("provider").notNull(),
    // The voice that ACTUALLY produced this asset (may be an autofix fallback, not
    // the requested voice). Null on legacy rows created before this column — the UI
    // treats null as "unknown", not "default". The default name-less Google voice is
    // stored as the DEFAULT_GOOGLE_TTS_VOICE_ID sentinel, not null.
    voiceId: text("voice_id"),
    sizeBytes: integer("size_bytes"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [unique("media_assets_content_hash_unique").on(table.contentHash)],
);

// Word list items - individual words within a category
export const wordListItems = pgTable(
  "word_list_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listId: uuid("list_id")
      .notNull()
      .references(() => wordLists.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .references(() => wordCategories.id, { onDelete: "set null" }),
    canonicalWordId: uuid("canonical_word_id"),
    position: integer("position").notNull().default(0),
    // Owner/editor decision: when true, this item's text is case-folded when
    // computing its progress content key (see lib/progress-key.ts). Default
    // false = case-sensitive. Toggling it is an identity-changing edit.
    ignoreCase: boolean("ignore_case").notNull().default(false),
    textKnown: text("text_known").notNull(),
    textTarget: text("text_target"),
    acceptedKnown: text("accepted_known").array().notNull().default(sql`'{}'::text[]`),
    acceptedTarget: text("accepted_target").array().notNull().default(sql`'{}'::text[]`),
    translationStatus: translationStatusEnum("translation_status")
      .notNull()
      .default("manual"),
    knownAudioAssetId: uuid("known_audio_asset_id").references(() => mediaAssets.id, {
      onDelete: "set null",
    }),
    knownAudioStatus: audioStatusEnum("known_audio_status").notNull().default("none"),
    audioAssetId: uuid("audio_asset_id").references(() => mediaAssets.id, {
      onDelete: "set null",
    }),
    audioStatus: audioStatusEnum("audio_status").notNull().default("none"),
    notes: text("notes"),
    // Optional per-item "study note" shown on the learning card. Versioned JSONB
    // (see lib/word-item-comment.ts). Independent of `notes` (legacy `en:` hack).
    comment: jsonb("comment").$type<WordItemComment>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("word_list_items_list_pos_idx").on(table.listId, table.position),
    index("word_list_items_list_cat_pos_idx").on(
      table.listId,
      table.categoryId,
      table.position,
    ),
  ],
);

// Users table - supports device, email, and wallet auth
export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  deviceId: text("device_id").unique(), // Device-based auth
  supabaseAuthId: text("supabase_auth_id").unique(), // Supabase Auth user id (email/Google/social)
  email: text("email").unique(), // Email (when signed in with email/Google/social)
  walletAddress: text("wallet_address").unique(), // Web3 embedded wallet (dormant; future stake/payment)
  authProvider: text("auth_provider"), // "email" | "google" | "apple" | "wallet" etc.
  registeredAt: timestamp("registered_at"), // set once when supabase_auth_id is first attached (created_at = first app use, which may be earlier)
  userRole: text("user_role").notNull().default("user"), // "user" or "editor"
  showEnglish: boolean("show_english").default(true).notNull(),
  showCategoryBadges: boolean("show_category_badges").default(false).notNull(),
  showPronunciation: boolean("show_pronunciation").default(false).notNull(),
  memoryHooksEnabled: boolean("memory_hooks_enabled").default(true).notNull(),
  memoryHooksIntroAnswered: boolean("memory_hooks_intro_answered").default(false).notNull(),
  memoryHookDisableFromStage: integer("memory_hook_disable_from_stage").default(5).notNull(),
  studyNotesEnabled: boolean("study_notes_enabled").default(true).notNull(),
  studyNoteMinimizeFromStage: integer("study_note_minimize_from_stage").default(2).notNull(),
  settingsLanguage: text("settings_language"),
  settingsLanguageSelectedAt: timestamp("settings_language_selected_at"),
  languageFrom: text("language_from"),
  languageTo: text("language_to"),
  onboardingCompletedAt: timestamp("onboarding_completed_at"),
  gameScore: integer("game_score").notNull().default(0),
  categoryOrder: text("category_order").array().notNull().default(sql`'{}'::text[]`),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const schools = pgTable(
  "schools",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    plan: schoolPlanEnum("plan").notNull().default("pilot_v1"),
    status: schoolStatusEnum("status").notNull().default("active"),
    studentSeatLimit: integer("student_seat_limit").notNull().default(30),
    teacherLimit: integer("teacher_limit").notNull().default(5),
    pilotExpiresAt: timestamp("pilot_expires_at"),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("schools_status_idx").on(table.status),
    check("schools_student_seat_limit_nonnegative", sql`${table.studentSeatLimit} >= 0`),
    check("schools_teacher_limit_nonnegative", sql`${table.teacherLimit} >= 0`),
  ],
);

export const schoolAccessCodes = pgTable(
  "school_access_codes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id")
      .notNull()
      .references(() => schools.id, { onDelete: "cascade" }),
    codeHash: text("code_hash").notNull(),
    role: schoolRoleEnum("role").notNull(),
    expiresAt: timestamp("expires_at"),
    revokedAt: timestamp("revoked_at"),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    revokedBy: uuid("revoked_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("school_access_codes_code_hash_unique").on(table.codeHash),
    index("school_access_codes_school_role_idx").on(table.schoolId, table.role),
  ],
);

export const schoolMemberships = pgTable(
  "school_memberships",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id")
      .notNull()
      .references(() => schools.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: schoolRoleEnum("role").notNull(),
    claimedAt: timestamp("claimed_at").defaultNow().notNull(),
    revokedAt: timestamp("revoked_at"),
    revokedBy: uuid("revoked_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("school_memberships_one_active_user_unique")
      .on(table.userId)
      .where(sql`${table.revokedAt} is null`),
    index("school_memberships_active_school_role_idx")
      .on(table.schoolId, table.role, table.claimedAt)
      .where(sql`${table.revokedAt} is null`),
  ],
);

export const schoolFeatureUsage = pgTable(
  "school_feature_usage",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    schoolId: uuid("school_id").references(() => schools.id, { onDelete: "set null" }),
    feature: schoolFeatureEnum("feature").notNull(),
    periodStart: timestamp("period_start").notNull(),
    used: integer("used").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("school_feature_usage_user_feature_period_unique").on(
      table.userId,
      table.feature,
      table.periodStart,
    ),
    index("school_feature_usage_school_period_idx").on(table.schoolId, table.periodStart),
    check("school_feature_usage_used_nonnegative", sql`${table.used} >= 0`),
  ],
);

export const schoolTranslationRequests = pgTable(
  "school_translation_requests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    schoolId: uuid("school_id").references(() => schools.id, { onDelete: "set null" }),
    periodStart: timestamp("period_start").notNull(),
    requestId: text("request_id").notNull(),
    requestHash: text("request_hash").notNull(),
    status: schoolTranslationRequestStatusEnum("status").notNull().default("reserved"),
    itemCount: integer("item_count").notNull(),
    characterCount: integer("character_count").notNull(),
    model: text("model").notNull(),
    providerGenerationId: text("provider_generation_id"),
    providerUsage: jsonb("provider_usage").$type<Record<string, unknown>>(),
    resultJson: jsonb("result_json").$type<Record<string, unknown>>(),
    errorJson: jsonb("error_json").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    completedAt: timestamp("completed_at"),
  },
  (table) => [
    unique("school_translation_requests_user_request_unique").on(
      table.userId,
      table.requestId,
    ),
    index("school_translation_requests_user_created_idx").on(table.userId, table.createdAt),
    index("school_translation_requests_status_created_idx").on(table.status, table.createdAt),
    index("school_translation_requests_school_created_idx").on(table.schoolId, table.createdAt),
    check("school_translation_requests_item_count_nonnegative", sql`${table.itemCount} >= 0`),
    check("school_translation_requests_character_count_nonnegative", sql`${table.characterCount} >= 0`),
  ],
);

export const uiTranslationCache = pgTable(
  "ui_translation_cache",
  {
    languageCode: text("language_code").primaryKey(),
    messages: jsonb("messages").$type<Record<string, string>>().notNull(),
    sourceHash: text("source_hash").notNull(),
    provider: text("provider").notNull().default("google"),
    status: text("status").notNull().default("autogenerated"),
    lastError: text("last_error"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("ui_translation_cache_source_hash_idx").on(table.sourceHash)],
);

// User progress - tracks spaced repetition for each word
export const userProgress = pgTable(
  "user_progress",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Legacy key from the dropped `words` table. Retained (no FK) so historical
    // word_id-keyed progress is not destroyed; new writes use wordListItemId.
    wordId: text("word_id"),
    wordListItemId: uuid("word_list_item_id").references(
      () => wordListItems.id,
      { onDelete: "set null" },
    ),
    // Content identity for progress (see lib/progress-key.ts): "v1:<sha256>" of
    // the normalized [langFrom, langTo, known, target] pair. Nullable during the
    // additive rollout; becomes the unique identity in migration B. After that,
    // word_list_item_id is best-effort/debug metadata only.
    contentKey: text("content_key"),
    stageIndex: integer("stage_index").notNull().default(0), // 0-7 spaced repetition
    knownCount: integer("known_count").notNull().default(0),
    unknownCount: integer("unknown_count").notNull().default(0),
    lastKnownAt: timestamp("last_known_at"),
    lastUnknownAt: timestamp("last_unknown_at"),
    nextDueAt: timestamp("next_due_at"),
    archivedAt: timestamp("archived_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("user_progress_updated_at_idx").on(table.updatedAt),
    unique().on(table.userId, table.wordId),
    // Content key is the progress identity (migration B). The old item-id unique
    // is dropped; word_list_item_id is now best-effort/debug metadata.
    uniqueIndex("user_progress_user_content_key_unique")
      .on(table.userId, table.contentKey)
      .where(sql`${table.contentKey} IS NOT NULL`),
    // Debug/lookup only — not an identity.
    index("user_progress_user_item_idx")
      .on(table.userId, table.wordListItemId)
      .where(sql`${table.wordListItemId} IS NOT NULL`),
  ],
);

export const userDevices = pgTable(
  "user_devices",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    deviceId: text("device_id").notNull(),
    firstSeenAt: timestamp("first_seen_at").defaultNow().notNull(),
    lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(),
  },
  (table) => [unique("user_devices_user_device_unique").on(table.userId, table.deviceId)]
);

export const reviewActionEnum = pgEnum("review_action", [
  "known",
  "really_known",
  "unknown",
]);

export const reviewEvents = pgTable(
  "review_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    clientEventId: text("client_event_id").notNull(),
    deviceId: text("device_id"),
    sessionId: text("session_id"),
    // Legacy key from the dropped `words` table; retained without FK.
    wordId: text("word_id"),
    wordListItemId: uuid("word_list_item_id").references(
      () => wordListItems.id,
      { onDelete: "set null" },
    ),
    action: reviewActionEnum("action").notNull(),
    clientCreatedAt: timestamp("client_created_at").notNull(),
    serverCreatedAt: timestamp("server_created_at").defaultNow().notNull(),
  },
  (table) => [
    unique("review_events_user_client_event_unique").on(
      table.userId,
      table.clientEventId,
    ),
    index("review_events_user_server_created_idx").on(
      table.userId,
      table.serverCreatedAt,
    ),
  ],
);

// User memory hooks - custom notes for words
export const userMemoryHooks = pgTable(
  "user_memory_hooks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Legacy key from the dropped `words` table; retained without FK.
    wordId: text("word_id"),
    wordListItemId: uuid("word_list_item_id").references(
      () => wordListItems.id,
      { onDelete: "cascade" },
    ),
    hookText: text("hook_text").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    // Soft-delete marker. Delta sync (PR 5) returns tombstoned rows so other
    // devices can drop them locally; row stays in the table for LWW arbitration.
    deletedAt: timestamp("deleted_at"),
  },
  (table) => [
    index("user_memory_hooks_updated_at_idx").on(table.updatedAt),
    unique("user_memory_hooks_user_id_word_id_unique").on(table.userId, table.wordId),
    unique("user_memory_hooks_user_id_word_list_item_id_unique").on(
      table.userId,
      table.wordListItemId,
    ),
  ],
);

// User category filters - selected categories for learning
export const userCategoryFilters = pgTable(
  "user_category_filters",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    category: text("category").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("user_category_filters_user_id_idx").on(table.userId),
    unique().on(table.userId, table.category),
  ]
);

// User API keys - BYOK key storage (encrypted)
export const userApiKeys = pgTable(
  "user_api_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    provider: apiKeyProviderEnum("provider").notNull(),
    encryptedKey: text("encrypted_key").notNull(),
    keyLabel: text("key_label"),
    status: text("status").notNull().default("connected"),
    lastValidatedAt: timestamp("last_validated_at"),
    connectedAt: timestamp("connected_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    keyLast4: text("key_last4"),
    connectionMethod: text("connection_method").notNull().default("manual"),
    translationModel: text("translation_model"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [unique("user_api_keys_user_provider_unique").on(table.userId, table.provider)],
);

// OAuth endpoint rate limiting buckets.
export const oauthRateLimits = pgTable(
  "oauth_rate_limits",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    bucketKey: text("bucket_key").notNull(),
    bucketStart: timestamp("bucket_start").notNull(),
    requestCount: integer("request_count").notNull().default(1),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("oauth_rate_limits_bucket_unique").on(table.bucketKey, table.bucketStart),
    index("oauth_rate_limits_bucket_key_idx").on(table.bucketKey, table.bucketStart),
  ],
);

// Google API usage ledger. Units are source text characters for each scope.
export const googleApiUsage = pgTable(
  "google_api_usage",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    scope: googleApiScopeEnum("scope").notNull(),
    periodStart: timestamp("period_start").notNull(),
    units: integer("units").notNull().default(0),
    requestCount: integer("request_count").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("google_api_usage_user_scope_period_unique").on(
      table.userId,
      table.scope,
      table.periodStart,
    ),
    index("google_api_usage_scope_period_idx").on(table.scope, table.periodStart),
    index("google_api_usage_user_period_idx").on(table.userId, table.periodStart),
  ],
);

// User list subscriptions - tracks which curated lists a user follows
export const userListSubscriptions = pgTable(
  "user_list_subscriptions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    listId: uuid("list_id")
      .notNull()
      .references(() => wordLists.id, { onDelete: "cascade" }),
    subscribedAt: timestamp("subscribed_at").defaultNow().notNull(),
  },
  (table) => [
    unique("user_list_subscriptions_user_list_unique").on(
      table.userId,
      table.listId,
    ),
  ],
);

// Durable record that a deleted user's Supabase auth identity still needs to be
// removed. Created inside the account-deletion DB transaction (so it commits
// atomically with the data erasure and survives a crash before the external
// Supabase admin call), then deleted once `auth.users` is gone. Holds only the
// auth id needed to finish erasure — no email or other personal data.
export const accountDeletionJobs = pgTable(
  "account_deletion_jobs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    supabaseAuthId: text("supabase_auth_id").notNull().unique(),
    attempts: integer("attempts").notNull().default(0),
    lastError: text("last_error"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("account_deletion_jobs_created_at_idx").on(table.createdAt)],
)
  // Deny-all RLS: this table is only ever touched server-side via the direct
  // Postgres connection (table owner, which bypasses RLS). Enabling RLS with no
  // policies keeps it unreachable through Supabase's PostgREST/anon API, since
  // it holds auth identifiers and has no reason to be publicly exposed.
  .enableRLS();

// Type exports for use in queries
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type UiTranslationCache = typeof uiTranslationCache.$inferSelect;
export type NewUiTranslationCache = typeof uiTranslationCache.$inferInsert;
export type UserProgress = typeof userProgress.$inferSelect;
export type NewUserProgress = typeof userProgress.$inferInsert;
export type ReviewEvent = typeof reviewEvents.$inferSelect;
export type NewReviewEvent = typeof reviewEvents.$inferInsert;
export type UserDevice = typeof userDevices.$inferSelect;
export type NewUserDevice = typeof userDevices.$inferInsert;
export type UserMemoryHook = typeof userMemoryHooks.$inferSelect;
export type NewUserMemoryHook = typeof userMemoryHooks.$inferInsert;
export type UserCategoryFilter = typeof userCategoryFilters.$inferSelect;
export type NewUserCategoryFilter = typeof userCategoryFilters.$inferInsert;
export type WordList = typeof wordLists.$inferSelect;
export type NewWordList = typeof wordLists.$inferInsert;
export type WordCategory = typeof wordCategories.$inferSelect;
export type NewWordCategory = typeof wordCategories.$inferInsert;
export type WordListItem = typeof wordListItems.$inferSelect;
export type NewWordListItem = typeof wordListItems.$inferInsert;
export type MediaAsset = typeof mediaAssets.$inferSelect;
export type NewMediaAsset = typeof mediaAssets.$inferInsert;
export type UserApiKey = typeof userApiKeys.$inferSelect;
export type NewUserApiKey = typeof userApiKeys.$inferInsert;
export type School = typeof schools.$inferSelect;
export type NewSchool = typeof schools.$inferInsert;
export type SchoolAccessCode = typeof schoolAccessCodes.$inferSelect;
export type NewSchoolAccessCode = typeof schoolAccessCodes.$inferInsert;
export type SchoolMembership = typeof schoolMemberships.$inferSelect;
export type NewSchoolMembership = typeof schoolMemberships.$inferInsert;
export type SchoolFeatureUsage = typeof schoolFeatureUsage.$inferSelect;
export type NewSchoolFeatureUsage = typeof schoolFeatureUsage.$inferInsert;
export type SchoolTranslationRequest = typeof schoolTranslationRequests.$inferSelect;
export type NewSchoolTranslationRequest = typeof schoolTranslationRequests.$inferInsert;
export type OAuthRateLimit = typeof oauthRateLimits.$inferSelect;
export type NewOAuthRateLimit = typeof oauthRateLimits.$inferInsert;
export type GoogleApiUsage = typeof googleApiUsage.$inferSelect;
export type NewGoogleApiUsage = typeof googleApiUsage.$inferInsert;
export type UserListSubscription = typeof userListSubscriptions.$inferSelect;
export type NewUserListSubscription = typeof userListSubscriptions.$inferInsert;
export type AccountDeletionJob = typeof accountDeletionJobs.$inferSelect;
export type NewAccountDeletionJob = typeof accountDeletionJobs.$inferInsert;
