import {
  pgTable,
  text,
  timestamp,
  uuid,
  integer,
  smallint,
  boolean,
  unique,
  uniqueIndex,
  index,
  primaryKey,
  check,
  pgEnum,
  jsonb,
  numeric,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { WordItemComment } from "@/lib/word-item-comment";
import type { LearnerBrief } from "@/lib/learner-brief";
import type { QualityHeuristicFlag } from "@/lib/quality-flags";

// Enums
export const translationStatusEnum = pgEnum("translation_status", [
  "manual",
  "pending",
  "translated",
  "failed",
]);

export const audioStatusEnum = pgEnum("audio_status", [
  "none",
  "pending",
  "ready",
  "failed",
]);

export const storageTypeEnum = pgEnum("storage_type", ["arweave", "r2", "object_store"]);

export const storageProviderEnum = pgEnum("storage_provider", ["b2"]);

export const mediaTypeEnum = pgEnum("media_type", ["audio"]);

export const ttsProviderEnum = pgEnum("tts_provider", [
  "google_tts",
  "elevenlabs",
]);

export const apiKeyProviderEnum = pgEnum("api_key_provider", [
  "openrouter",
  "elevenlabs",
]);

export const googleApiScopeEnum = pgEnum("google_api_scope", [
  "translate",
  "tts",
]);

export const schoolPlanEnum = pgEnum("school_plan", ["pilot_v1"]);

export const schoolStatusEnum = pgEnum("school_status", [
  "active",
  "inactive",
]);

export const schoolRoleEnum = pgEnum("school_role", [
  "student",
  "teacher",
]);

export const schoolFeatureEnum = pgEnum("school_feature", [
  "ai_translation",
  "photo_lab",
]);

export const schoolTranslationRequestStatusEnum = pgEnum(
  "school_translation_request_status",
  ["reserved", "completed", "released", "unknown", "failed_charged"],
);

export const wordChatCallTypeEnum = pgEnum("word_chat_call_type", [
  "chat",
  "proposal",
  "translation",
  "brief",
]);

// Funnel position, not a completed boolean: the useful question is WHERE people
// drop out, and money spent on sessions abandoned at review is a different
// problem from money spent on sessions abandoned during the chat.
export const wordChatStageEnum = pgEnum("word_chat_stage", [
  "started",
  "proposal_completed",
  "review_completed",
  "committed",
]);

export const CONTENT_REPORT_REASONS = [
  "sexual_content",
  "hate_or_harassment",
  "violence_or_danger",
  "illegal_content",
  "spam_or_misleading",
  "copyright",
  "other",
] as const;

export const CONTENT_REPORT_STATUSES = [
  "pending",
  "reviewing",
  "resolved",
  "dismissed",
] as const;

export const LIST_MODERATION_STATUSES = [
  "visible",
  "under_review",
  "rejected",
] as const;

// Word lists - container for vocabulary sets
export const wordLists = pgTable(
  "word_lists",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ownerId: uuid("owner_id").references(() => users.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    description: text("description"),
    languageFrom: text("language_from").notNull(),
    languageTo: text("language_to").notNull(),
    isPublic: boolean("is_public").notNull().default(false),
    isCommon: boolean("is_common").notNull().default(false),
    isRecommended: boolean("is_recommended").notNull().default(false),
    isAutogenerated: boolean("is_autogenerated").notNull().default(false),
    // Ordinary public lists are hidden from discovery as soon as a user report
    // puts them under review. Owners and editors can still inspect them; only an
    // editor can restore visibility or reject the public submission.
    moderationStatus: text("moderation_status").notNull().default("visible"),
    moderationUpdatedAt: timestamp("moderation_updated_at"),
    moderationDecisionCode: text("moderation_decision_code"),
    moderationPublicNote: text("moderation_public_note"),
    // Internal-only moderator note. `serializeWordList` must always remove it
    // from API responses; owners receive the public fields above instead.
    moderationNote: text("moderation_note"),
    // A learner's own word-chat list ("My words"), one per language pair. Public
    // personal lists must be excluded from every "all public lists" query path —
    // sidebar, matches, search, sitemap — or one learner's list shows up in
    // everyone else's app. See lib/db/queries/word-list-items/lists.ts.
    isPersonal: boolean("is_personal").notNull().default(false),
    // Second, separate consent on a personal list: the list itself is private,
    // but its items may be shown to editors WITHOUT the owner, list name, or the
    // learner's own category name, so translation mistakes can be caught.
    reviewOptIn: boolean("review_opt_in").notNull().default(true),
    // Structured memory of what the learner told the word-chat (see
    // lib/learner-brief.ts). Bounded schema on purpose — never a free-text
    // summary, and never a transcript.
    learnerBrief: jsonb("learner_brief").$type<LearnerBrief>(),
    // Capability token for share links. Null = not shared. Generated on demand;
    // rotating it (reset) invalidates old links. Never exposed in normal list
    // responses — only through the owner-only /share endpoints.
    shareToken: text("share_token"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("word_lists_owner_idx").on(table.ownerId),
    index("word_lists_public_idx").on(table.isPublic),
    index("word_lists_public_moderation_idx").on(table.isPublic, table.moderationStatus),
    index("word_lists_common_idx").on(table.isCommon),
    index("word_lists_recommended_idx").on(table.isRecommended),
    check(
      "word_lists_moderation_status_check",
      sql`${table.moderationStatus} in ('visible', 'under_review', 'rejected')`,
    ),
    check(
      "word_lists_moderation_decision_check",
      sql`${table.moderationDecisionCode} is null or ${table.moderationDecisionCode} in ('sexual_content', 'hate_or_harassment', 'violence_or_danger', 'illegal_content', 'spam_or_misleading', 'copyright', 'other_policy_violation')`,
    ),
    check(
      "word_lists_moderation_public_note_length_check",
      sql`${table.moderationPublicNote} is null or char_length(${table.moderationPublicNote}) <= 1000`,
    ),
    uniqueIndex("word_lists_share_token_unique")
      .on(table.shareToken)
      .where(sql`${table.shareToken} is not null`),
    uniqueIndex("word_lists_recommended_pair_unique")
      .on(
        sql`(case when lower(${table.languageFrom}) in ('cz', 'cs') then 'cs' else lower(${table.languageFrom}) end)`,
        sql`(case when lower(${table.languageTo}) in ('cz', 'cs') then 'cs' else lower(${table.languageTo}) end)`,
      )
      .where(sql`${table.isRecommended} = true`),
    // Exactly one personal list per owner per direction. This is what makes
    // find-or-create inside the commit transaction safe against two tabs.
    uniqueIndex("word_lists_personal_pair_unique")
      .on(table.ownerId, table.languageFrom, table.languageTo)
      .where(sql`${table.isPersonal} = true`),
  ],
);

// Word categories - sections within a list
export const wordCategories = pgTable(
  "word_categories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listId: uuid("list_id")
      .notNull()
      .references(() => wordLists.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    position: integer("position").notNull().default(0),
    isSystem: boolean("is_system").notNull().default(false),
    // Client-generated idempotency key for a word-chat commit. The unique index
    // is what makes a double-click, a reload, or a retry produce one category
    // and one quota charge instead of two. Null for every other category.
    creationKey: text("creation_key"),
    // Neutral topic label for the editor review queue. The learner's own
    // category name can be personal ("Doctor visit with Anna"); this one is
    // generated to be safe to show without the owner or the list name.
    reviewLabel: text("review_label"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("word_categories_list_pos_idx").on(table.listId, table.position),
    uniqueIndex("word_categories_creation_key_unique")
      .on(table.creationKey)
      .where(sql`${table.creationKey} is not null`),
  ],
);

// Media assets - shared audio pool (content-addressed)
export const mediaAssets = pgTable(
  "media_assets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contentHash: text("content_hash").notNull(),
    storageType: storageTypeEnum("storage_type").notNull(),
    storageProvider: storageProviderEnum("storage_provider"),
    storageRef: text("storage_ref").notNull(),
    mediaType: mediaTypeEnum("media_type").notNull().default("audio"),
    language: text("language").notNull(),
    textReference: text("text_reference").notNull(),
    provider: ttsProviderEnum("provider").notNull(),
    // The voice that ACTUALLY produced this asset (may be an autofix fallback, not
    // the requested voice). Null on legacy rows created before this column — the UI
    // treats null as "unknown", not "default". The default name-less Google voice is
    // stored as the DEFAULT_GOOGLE_TTS_VOICE_ID sentinel, not null.
    voiceId: text("voice_id"),
    sizeBytes: integer("size_bytes"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [unique("media_assets_content_hash_unique").on(table.contentHash)],
);

// Word list items - individual words within a category
export const wordListItems = pgTable(
  "word_list_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listId: uuid("list_id")
      .notNull()
      .references(() => wordLists.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .references(() => wordCategories.id, { onDelete: "set null" }),
    canonicalWordId: uuid("canonical_word_id"),
    // The item this row was copied from, when word chat matched a proposal onto
    // existing content. Provenance only — nothing reads it at runtime; it is
    // what makes "which pairs came from an unreviewed list" answerable later.
    sourceItemId: uuid("source_item_id"),
    // Durable per-user overlay identity. Unlike `sourceItemId`, this is
    // deliberately NOT a foreign key: deleting a legacy/public source must not
    // erase the fact that the learner explicitly took that item over.
    takeoverSourceItemId: uuid("takeover_source_item_id"),
    position: integer("position").notNull().default(0),
    // Owner/editor decision: when true, this item's text is case-folded when
    // computing its progress content key (see lib/progress-key.ts). Default
    // false = case-sensitive. Toggling it is an identity-changing edit.
    ignoreCase: boolean("ignore_case").notNull().default(false),
    textKnown: text("text_known").notNull(),
    textTarget: text("text_target"),
    acceptedKnown: text("accepted_known").array().notNull().default(sql`'{}'::text[]`),
    acceptedTarget: text("accepted_target").array().notNull().default(sql`'{}'::text[]`),
    translationStatus: translationStatusEnum("translation_status")
      .notNull()
      .default("manual"),
    knownAudioAssetId: uuid("known_audio_asset_id").references(() => mediaAssets.id, {
      onDelete: "set null",
    }),
    knownAudioStatus: audioStatusEnum("known_audio_status").notNull().default("none"),
    audioAssetId: uuid("audio_asset_id").references(() => mediaAssets.id, {
      onDelete: "set null",
    }),
    audioStatus: audioStatusEnum("audio_status").notNull().default("none"),
    notes: text("notes"),
    // Optional per-item "study note" shown on the learning card. Versioned JSONB
    // (see lib/word-item-comment.ts). Independent of `notes` (legacy `en:` hack).
    comment: jsonb("comment").$type<WordItemComment>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("word_list_items_list_pos_idx").on(table.listId, table.position),
    index("word_list_items_list_cat_pos_idx").on(
      table.listId,
      table.categoryId,
      table.position,
    ),
    index("word_list_items_source_item_idx").on(table.sourceItemId),
    uniqueIndex("word_list_items_personal_takeover_unique")
      .on(table.listId, table.takeoverSourceItemId)
      .where(sql`${table.takeoverSourceItemId} is not null`),
  ],
);

// Users table - supports device, email, and wallet auth
export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  deviceId: text("device_id").unique(), // Device-based auth
  supabaseAuthId: text("supabase_auth_id").unique(), // Supabase Auth user id (email/Google/social)
  email: text("email").unique(), // Email (when signed in with email/Google/social)
  walletAddress: text("wallet_address").unique(), // Web3 embedded wallet (dormant; future stake/payment)
  authProvider: text("auth_provider"), // "email" | "google" | "apple" | "wallet" etc.
  // Encrypted Apple refresh token, kept only so account deletion can revoke it
  // as Sign in with Apple requires. See features/auth/server/apple-token.ts.
  appleRefreshToken: text("apple_refresh_token"),
  registeredAt: timestamp("registered_at"), // set once when supabase_auth_id is first attached (created_at = first app use, which may be earlier)
  userRole: text("user_role").notNull().default("user"), // "user" or "editor"
  // Operator-set photo-lab allowance. NULL = whatever the account's normal path
  // grants; a number replaces that limit (school quota included). See
  // scripts/user-limits.ts and features/photo-lab/server/rate-limit.ts.
  photoLabLimitOverride: integer("photo_lab_limit_override"),
  // Account-wide half of the quality-review consent; the per-list half is
  // `wordLists.reviewOptIn`. BOTH must be true for a pair to reach the editor
  // pool, so switching this off does not overwrite the per-list `false` that
  // photo lab sets, and switching it on does not resurrect it.
  reviewOptIn: boolean("review_opt_in").notNull().default(true),
  // Separate, stricter consent: the pair may leave for a third-party LLM
  // (OpenRouter) to be audited automatically. Defaults to false — an editor
  // reading the pair and a provider receiving it are not the same ask.
  aiReviewOptIn: boolean("ai_review_opt_in").notNull().default(false),
  showEnglish: boolean("show_english").default(true).notNull(),
  showCategoryBadges: boolean("show_category_badges").default(false).notNull(),
  showPronunciation: boolean("show_pronunciation").default(false).notNull(),
  memoryHooksEnabled: boolean("memory_hooks_enabled").default(true).notNull(),
  memoryHooksIntroAnswered: boolean("memory_hooks_intro_answered").default(false).notNull(),
  memoryHookDisableFromStage: integer("memory_hook_disable_from_stage").default(5).notNull(),
  studyNotesEnabled: boolean("study_notes_enabled").default(true).notNull(),
  studyNoteMinimizeFromStage: integer("study_note_minimize_from_stage").default(2).notNull(),
  settingsLanguage: text("settings_language"),
  settingsLanguageSelectedAt: timestamp("settings_language_selected_at"),
  settingsLanguageRevision: integer("settings_language_revision").notNull().default(0),
  languageFrom: text("language_from"),
  languageTo: text("language_to"),
  languagePairRevision: integer("language_pair_revision").notNull().default(0),
  onboardingCompletedAt: timestamp("onboarding_completed_at"),
  // How the word chat addresses the learner. Persisted independently from a
  // draft so every new category (and every device) keeps the earlier choice.
  wordChatAddressRegister: text("word_chat_address_register"),
  // Optional onboarding/chat preferences that avoid re-asking the same setup
  // questions and keep generated prompts calibrated to the learner.
  wordChatSalutationGender: text("word_chat_salutation_gender"),
  gameScore: integer("game_score").notNull().default(0),
  categoryOrder: text("category_order").array().notNull().default(sql`'{}'::text[]`),
  // Categories whose items lead the study stream, ahead even of due repeats.
  // Category IDS, not names: names are editable, repeatable across lists, and
  // locale-dependent, unlike `categoryOrder` which is a legacy name-based
  // ordering preference and stays as it is.
  pinnedCategoryIds: uuid("pinned_category_ids")
    .array()
    .notNull()
    .default(sql`'{}'::uuid[]`),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const userLanguagePreferences = pgTable(
  "user_language_preferences",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    languageTo: text("language_to").notNull(),
    languageLevel: text("language_level").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("user_language_preferences_user_language_unique").on(
      table.userId,
      table.languageTo,
    ),
    check(
      "user_language_preferences_language_level_check",
      sql`${table.languageLevel} in ('A0', 'A1', 'A2', 'B1', 'B2', 'C1')`,
    ),
  ],
);

export const schools = pgTable(
  "schools",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    plan: schoolPlanEnum("plan").notNull().default("pilot_v1"),
    status: schoolStatusEnum("status").notNull().default("active"),
    studentSeatLimit: integer("student_seat_limit").notNull().default(30),
    teacherLimit: integer("teacher_limit").notNull().default(5),
    pilotExpiresAt: timestamp("pilot_expires_at"),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("schools_status_idx").on(table.status),
    check("schools_student_seat_limit_nonnegative", sql`${table.studentSeatLimit} >= 0`),
    check("schools_teacher_limit_nonnegative", sql`${table.teacherLimit} >= 0`),
  ],
);

export const schoolAccessCodes = pgTable(
  "school_access_codes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id")
      .notNull()
      .references(() => schools.id, { onDelete: "cascade" }),
    codeHash: text("code_hash").notNull(),
    role: schoolRoleEnum("role").notNull(),
    expiresAt: timestamp("expires_at"),
    revokedAt: timestamp("revoked_at"),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    revokedBy: uuid("revoked_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("school_access_codes_code_hash_unique").on(table.codeHash),
    index("school_access_codes_school_role_idx").on(table.schoolId, table.role),
  ],
);

export const schoolMemberships = pgTable(
  "school_memberships",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id")
      .notNull()
      .references(() => schools.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: schoolRoleEnum("role").notNull(),
    claimedAt: timestamp("claimed_at").defaultNow().notNull(),
    revokedAt: timestamp("revoked_at"),
    revokedBy: uuid("revoked_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("school_memberships_one_active_user_unique")
      .on(table.userId)
      .where(sql`${table.revokedAt} is null`),
    index("school_memberships_active_school_role_idx")
      .on(table.schoolId, table.role, table.claimedAt)
      .where(sql`${table.revokedAt} is null`),
  ],
);

export const schoolFeatureUsage = pgTable(
  "school_feature_usage",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    schoolId: uuid("school_id").references(() => schools.id, { onDelete: "set null" }),
    feature: schoolFeatureEnum("feature").notNull(),
    periodStart: timestamp("period_start").notNull(),
    used: integer("used").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("school_feature_usage_user_feature_period_unique").on(
      table.userId,
      table.feature,
      table.periodStart,
    ),
    index("school_feature_usage_school_period_idx").on(table.schoolId, table.periodStart),
    check("school_feature_usage_used_nonnegative", sql`${table.used} >= 0`),
  ],
);

export const schoolTranslationRequests = pgTable(
  "school_translation_requests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    schoolId: uuid("school_id").references(() => schools.id, { onDelete: "set null" }),
    periodStart: timestamp("period_start").notNull(),
    requestId: text("request_id").notNull(),
    requestHash: text("request_hash").notNull(),
    status: schoolTranslationRequestStatusEnum("status").notNull().default("reserved"),
    itemCount: integer("item_count").notNull(),
    characterCount: integer("character_count").notNull(),
    model: text("model").notNull(),
    providerGenerationId: text("provider_generation_id"),
    providerUsage: jsonb("provider_usage").$type<Record<string, unknown>>(),
    resultJson: jsonb("result_json").$type<Record<string, unknown>>(),
    errorJson: jsonb("error_json").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    completedAt: timestamp("completed_at"),
  },
  (table) => [
    unique("school_translation_requests_user_request_unique").on(
      table.userId,
      table.requestId,
    ),
    index("school_translation_requests_user_created_idx").on(table.userId, table.createdAt),
    index("school_translation_requests_status_created_idx").on(table.status, table.createdAt),
    index("school_translation_requests_school_created_idx").on(table.schoolId, table.createdAt),
    check("school_translation_requests_item_count_nonnegative", sql`${table.itemCount} >= 0`),
    check("school_translation_requests_character_count_nonnegative", sql`${table.characterCount} >= 0`),
  ],
);

export const uiTranslationCache = pgTable(
  "ui_translation_cache",
  {
    languageCode: text("language_code").primaryKey(),
    messages: jsonb("messages").$type<Record<string, string>>().notNull(),
    sourceHash: text("source_hash").notNull(),
    provider: text("provider").notNull().default("google"),
    status: text("status").notNull().default("autogenerated"),
    lastError: text("last_error"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("ui_translation_cache_source_hash_idx").on(table.sourceHash)],
);

// One row per user and requested interface language. Repeated taps refresh the
// timestamp but never inflate demand from the same person.
export const uiLanguageRequests = pgTable(
  "ui_language_requests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    languageCode: text("language_code").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("ui_language_requests_user_language_unique").on(
      table.userId,
      table.languageCode,
    ),
    index("ui_language_requests_language_updated_idx").on(
      table.languageCode,
      table.updatedAt,
    ),
  ],
);

// User progress - tracks spaced repetition for each word
export const userProgress = pgTable(
  "user_progress",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Legacy key from the dropped `words` table. Retained (no FK) so historical
    // word_id-keyed progress is not destroyed; new writes use wordListItemId.
    wordId: text("word_id"),
    wordListItemId: uuid("word_list_item_id").references(
      () => wordListItems.id,
      { onDelete: "set null" },
    ),
    // Content identity for progress (see lib/progress-key.ts): "v1:<sha256>" of
    // the normalized [langFrom, langTo, known, target] pair. Nullable during the
    // additive rollout; becomes the unique identity in migration B. After that,
    // word_list_item_id is best-effort/debug metadata only.
    contentKey: text("content_key"),
    stageIndex: integer("stage_index").notNull().default(0), // 0-7 spaced repetition
    knownCount: integer("known_count").notNull().default(0),
    unknownCount: integer("unknown_count").notNull().default(0),
    lastKnownAt: timestamp("last_known_at"),
    lastUnknownAt: timestamp("last_unknown_at"),
    nextDueAt: timestamp("next_due_at"),
    archivedAt: timestamp("archived_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("user_progress_updated_at_idx").on(table.updatedAt),
    unique().on(table.userId, table.wordId),
    // Content key is the progress identity (migration B). The old item-id unique
    // is dropped; word_list_item_id is now best-effort/debug metadata.
    uniqueIndex("user_progress_user_content_key_unique")
      .on(table.userId, table.contentKey)
      .where(sql`${table.contentKey} IS NOT NULL`),
    // Debug/lookup only — not an identity.
    index("user_progress_user_item_idx")
      .on(table.userId, table.wordListItemId)
      .where(sql`${table.wordListItemId} IS NOT NULL`),
  ],
);

export const userDevices = pgTable(
  "user_devices",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    deviceId: text("device_id").notNull(),
    firstSeenAt: timestamp("first_seen_at").defaultNow().notNull(),
    lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(),
    platform: text("platform"),
    formFactor: text("form_factor"),
  },
  (table) => [unique("user_devices_user_device_unique").on(table.userId, table.deviceId)]
);

export const reviewActionEnum = pgEnum("review_action", [
  "known",
  "really_known",
  "unknown",
]);

export const reviewEvents = pgTable(
  "review_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    clientEventId: text("client_event_id").notNull(),
    deviceId: text("device_id"),
    sessionId: text("session_id"),
    // Legacy key from the dropped `words` table; retained without FK.
    wordId: text("word_id"),
    wordListItemId: uuid("word_list_item_id").references(
      () => wordListItems.id,
      { onDelete: "set null" },
    ),
    action: reviewActionEnum("action").notNull(),
    clientCreatedAt: timestamp("client_created_at").notNull(),
    serverCreatedAt: timestamp("server_created_at").defaultNow().notNull(),
  },
  (table) => [
    unique("review_events_user_client_event_unique").on(
      table.userId,
      table.clientEventId,
    ),
    index("review_events_user_server_created_idx").on(
      table.userId,
      table.serverCreatedAt,
    ),
  ],
);

// Measured foreground time, one row per contiguous run of activity on one
// device. This replaces inferring study time from gaps between review-event
// sync timestamps, which measured how often the outbox flushed rather than how
// long anyone studied.
//
// `timestamptz` throughout, unlike the older tables here: the client sends
// epoch milliseconds and rollups reason about day boundaries, so a naive
// timestamp would invite timezone bugs the moment a per-day figure is shown.
//
// The interval is stored, not just the duration, because `active_ms` alone
// cannot be summed across a user's devices without double-counting overlap.
// Every row satisfies `ended_at - started_at ≈ active_ms` (the tracker closes a
// segment at any interruption), so [started_at, ended_at] is a real activity
// interval that a later user-facing rollup can union.
export const activitySegments = pgTable(
  "activity_segments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Client-generated; the idempotency key for redelivery, exactly as
    // `client_event_id` works for review events.
    clientSegmentId: text("client_segment_id").notNull(),
    deviceId: text("device_id"),
    // Activity separated by less than 30 minutes of inactivity. Unrelated to
    // `review_events.session_id`, which is really a browser-tab id.
    sessionId: text("session_id").notNull(),
    surface: text("surface").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }).notNull(),
    activeMs: integer("active_ms").notNull(),
    interactions: integer("interactions").notNull().default(0),
    serverCreatedAt: timestamp("server_created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique("activity_segments_user_client_unique").on(
      table.userId,
      table.clientSegmentId,
    ),
    index("activity_segments_user_started_idx").on(
      table.userId,
      table.startedAt,
    ),
  ],
);

// Durable acknowledgement ledger for local-first mutations. The composite
// uniqueness is user-scoped because client operation ids are generated on the
// device and need only be stable within one account.
//
// (userId, clientOpId) is the primary key rather than a surrogate uuid: it is
// the only way this table is ever read, and it is the highest-insert-rate table
// in the schema (one row per client operation). A surrogate would add a column
// and a second btree that nothing queries. Rows are pruned by age — see
// scripts/compact-review-events.ts — which is what the createdAt index serves.
export const syncAppliedOperations = pgTable(
  "sync_applied_operations",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    clientOpId: text("client_op_id").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    primaryKey({
      name: "sync_applied_operations_pkey",
      columns: [table.userId, table.clientOpId],
    }),
    index("sync_applied_operations_created_idx").on(table.createdAt),
  ],
);

// Photo-lab analysis events — one row per successfully returned photo analysis.
// Behaviour only: never the image or the produced vocabulary text, just a count.
// Powers the admin dashboard's photo metrics (how many people used it, and how
// many more than once); ON DELETE CASCADE so account erasure removes the trace.
export const photoAnalysisEvents = pgTable(
  "photo_analysis_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    occurredAt: timestamp("occurred_at").defaultNow().notNull(),
    // Number of labels in the final (filtered/deduped) result; 0 is valid.
    labelCount: integer("label_count").notNull().default(0),
    // Normalized language codes (see lib/i18n/languages normalizeLanguageCode).
    languageFrom: text("language_from"),
    languageTo: text("language_to"),
  },
  (table) => [
    index("photo_analysis_events_user_occurred_idx").on(
      table.userId,
      table.occurredAt,
    ),
    index("photo_analysis_events_occurred_idx").on(table.occurredAt),
    check("photo_analysis_events_label_count_nonnegative", sql`${table.labelCount} >= 0`),
  ],
);

// Word-chat model spend, one row per model call. Exists because the real cost
// per session cannot be estimated at a desk: a proposal call carries a corpus
// pool, an exclusion list and the conversation. Answers "cost per started vs
// completed session", "cost per committed item", and "Sonnet vs Opus on the
// same sessions". Never stores prompt or completion text.
export const wordChatUsage = pgTable(
  "word_chat_usage",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Client-generated session id, shared by every call in one chat session so
    // spend can be folded per session and per funnel stage.
    sessionId: text("session_id").notNull(),
    callType: wordChatCallTypeEnum("call_type").notNull(),
    stage: wordChatStageEnum("stage").notNull().default("started"),
    model: text("model").notNull(),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    // Priced from the call's model at request time; models and prices move, so
    // this is stored rather than derived later.
    estimatedCostUsd: numeric("estimated_cost_usd", { precision: 12, scale: 6 })
      .notNull()
      .default("0"),
    // Items the call produced or acted on; null when it does not apply.
    itemCount: integer("item_count"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("word_chat_usage_user_created_idx").on(table.userId, table.createdAt),
    index("word_chat_usage_session_idx").on(table.sessionId),
    index("word_chat_usage_created_idx").on(table.createdAt),
    check(
      "word_chat_usage_tokens_nonnegative",
      sql`${table.inputTokens} >= 0 and ${table.outputTokens} >= 0`,
    ),
  ],
);

// Stable idempotency result for one word-chat commit. Category rows remain
// editable/deletable product data, so the creation key and original counters
// live here instead of being reconstructed from whatever the category contains
// at retry time. list/category ids are durable result values, intentionally not
// foreign keys.
export const wordChatCommits = pgTable(
  "word_chat_commits",
  {
    creationKey: text("creation_key").primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    sessionId: text("session_id").notNull(),
    listId: uuid("list_id"),
    categoryId: uuid("category_id"),
    itemCount: integer("item_count").notNull().default(0),
    takeoverCount: integer("takeover_count").notNull().default(0),
    upgradedTakeoverCount: integer("upgraded_takeover_count").notNull().default(0),
    committedAt: timestamp("committed_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("word_chat_commits_user_created_idx").on(table.userId, table.createdAt),
    check(
      "word_chat_commits_counts_nonnegative",
      sql`${table.itemCount} >= 0
        and ${table.takeoverCount} >= 0
        and ${table.upgradedTakeoverCount} >= 0`,
    ),
  ],
);

// User memory hooks - custom notes for words
export const userMemoryHooks = pgTable(
  "user_memory_hooks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Legacy key from the dropped `words` table; retained without FK.
    wordId: text("word_id"),
    wordListItemId: uuid("word_list_item_id").references(
      () => wordListItems.id,
      { onDelete: "cascade" },
    ),
    hookText: text("hook_text").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    // Soft-delete marker. Delta sync (PR 5) returns tombstoned rows so other
    // devices can drop them locally; row stays in the table for LWW arbitration.
    deletedAt: timestamp("deleted_at"),
  },
  (table) => [
    index("user_memory_hooks_updated_at_idx").on(table.updatedAt),
    unique("user_memory_hooks_user_id_word_id_unique").on(table.userId, table.wordId),
    unique("user_memory_hooks_user_id_word_list_item_id_unique").on(
      table.userId,
      table.wordListItemId,
    ),
  ],
);

// User category filters - selected categories for learning
export const userCategoryFilters = pgTable(
  "user_category_filters",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    category: text("category").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("user_category_filters_user_id_idx").on(table.userId),
    unique().on(table.userId, table.category),
  ]
);

// User API keys - BYOK key storage (encrypted)
export const userApiKeys = pgTable(
  "user_api_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    provider: apiKeyProviderEnum("provider").notNull(),
    encryptedKey: text("encrypted_key").notNull(),
    keyLabel: text("key_label"),
    status: text("status").notNull().default("connected"),
    lastValidatedAt: timestamp("last_validated_at"),
    connectedAt: timestamp("connected_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    keyLast4: text("key_last4"),
    connectionMethod: text("connection_method").notNull().default("manual"),
    translationModel: text("translation_model"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [unique("user_api_keys_user_provider_unique").on(table.userId, table.provider)],
);

// OAuth endpoint rate limiting buckets.
export const oauthRateLimits = pgTable(
  "oauth_rate_limits",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    bucketKey: text("bucket_key").notNull(),
    bucketStart: timestamp("bucket_start").notNull(),
    requestCount: integer("request_count").notNull().default(1),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("oauth_rate_limits_bucket_unique").on(table.bucketKey, table.bucketStart),
    index("oauth_rate_limits_bucket_key_idx").on(table.bucketKey, table.bucketStart),
  ],
);

// Google API usage ledger. Units are source text characters for each scope.
export const googleApiUsage = pgTable(
  "google_api_usage",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    scope: googleApiScopeEnum("scope").notNull(),
    periodStart: timestamp("period_start").notNull(),
    units: integer("units").notNull().default(0),
    requestCount: integer("request_count").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("google_api_usage_user_scope_period_unique").on(
      table.userId,
      table.scope,
      table.periodStart,
    ),
    index("google_api_usage_scope_period_idx").on(table.scope, table.periodStart),
    index("google_api_usage_user_period_idx").on(table.userId, table.periodStart),
  ],
);

// Append-only provider-call ledger. Unlike google_api_usage (the per-user
// reservation/cap table), this records calls that actually reached Google and
// also supports system/operator work where there is no user to charge.
export const googleApiUsageEvents = pgTable(
  "google_api_usage_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),
    scope: googleApiScopeEnum("scope").notNull(),
    source: text("source").notNull(),
    model: text("model"),
    units: integer("units").notNull().default(0),
    requestCount: integer("request_count").notNull().default(1),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("google_api_usage_events_created_idx").on(table.createdAt),
    index("google_api_usage_events_scope_created_idx").on(table.scope, table.createdAt),
    index("google_api_usage_events_source_created_idx").on(table.source, table.createdAt),
    index("google_api_usage_events_user_created_idx").on(table.userId, table.createdAt),
    check("google_api_usage_events_units_nonnegative", sql`${table.units} >= 0`),
    check(
      "google_api_usage_events_request_count_nonnegative",
      sql`${table.requestCount} >= 0`,
    ),
  ],
);

// User list subscriptions - tracks which curated lists a user follows
export const userListSubscriptions = pgTable(
  "user_list_subscriptions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    listId: uuid("list_id")
      .notNull()
      .references(() => wordLists.id, { onDelete: "cascade" }),
    subscribedAt: timestamp("subscribed_at").defaultNow().notNull(),
  },
  (table) => [
    unique("user_list_subscriptions_user_list_unique").on(
      table.userId,
      table.listId,
    ),
  ],
);

// User-controlled safety boundary. The relationship is interpreted
// bidirectionally for content access: once either account blocks the other,
// neither account can discover, join, or fork the other's lists.
export const userBlocks = pgTable(
  "user_blocks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    blockerId: uuid("blocker_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    blockedId: uuid("blocked_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    unique("user_blocks_blocker_blocked_unique").on(table.blockerId, table.blockedId),
    index("user_blocks_blocker_idx").on(table.blockerId),
    index("user_blocks_blocked_idx").on(table.blockedId),
    check("user_blocks_not_self_check", sql`${table.blockerId} <> ${table.blockedId}`),
  ],
).enableRLS();

// List-level user reports. Snapshot fields keep a small, reviewable record if
// the owner edits or deletes the list before a moderator opens the queue. Full
// user content is deliberately not retained here.
export const contentReports = pgTable(
  "content_reports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    reporterId: uuid("reporter_id").references(() => users.id, { onDelete: "set null" }),
    listId: uuid("list_id").references(() => wordLists.id, { onDelete: "set null" }),
    reportedOwnerId: uuid("reported_owner_id").references(() => users.id, {
      onDelete: "set null",
    }),
    reason: text("reason").notNull(),
    details: text("details"),
    listNameSnapshot: text("list_name_snapshot").notNull(),
    listDescriptionSnapshot: text("list_description_snapshot"),
    contentExcerpt: text("content_excerpt"),
    status: text("status").notNull().default("pending"),
    decisionCode: text("decision_code"),
    publicNote: text("public_note"),
    moderatorNote: text("moderator_note"),
    reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "set null" }),
    resolvedAt: timestamp("resolved_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("content_reports_status_created_idx").on(table.status, table.createdAt),
    index("content_reports_list_idx").on(table.listId),
    uniqueIndex("content_reports_open_reporter_list_unique")
      .on(table.reporterId, table.listId)
      .where(
        sql`${table.reporterId} is not null and ${table.listId} is not null and ${table.status} in ('pending', 'reviewing')`,
      ),
    check(
      "content_reports_reason_check",
      sql`${table.reason} in ('sexual_content', 'hate_or_harassment', 'violence_or_danger', 'illegal_content', 'spam_or_misleading', 'copyright', 'other')`,
    ),
    check(
      "content_reports_status_check",
      sql`${table.status} in ('pending', 'reviewing', 'resolved', 'dismissed')`,
    ),
    check(
      "content_reports_decision_check",
      sql`${table.decisionCode} is null or ${table.decisionCode} in ('no_violation', 'sexual_content', 'hate_or_harassment', 'violence_or_danger', 'illegal_content', 'spam_or_misleading', 'copyright', 'other_policy_violation')`,
    ),
    check(
      "content_reports_public_note_length_check",
      sql`${table.publicNote} is null or char_length(${table.publicNote}) <= 1000`,
    ),
    check(
      "content_reports_details_length_check",
      sql`${table.details} is null or char_length(${table.details}) <= 1000`,
    ),
    check(
      "content_reports_excerpt_length_check",
      sql`${table.contentExcerpt} is null or char_length(${table.contentExcerpt}) <= 8000`,
    ),
  ],
).enableRLS();

export const QUALITY_REVIEW_VERDICTS = [
  "unreviewed",
  "ok",
  "suspect",
  "suggested",
] as const;

// The quality pool: one row per normalized word pair found in private owned
// lists, so editors can catch missing audio and bad translations across the
// whole corpus at once. Rows carry NO author identity, list name, or learner
// category name — the pool aggregates by content and counts occurrences.
//
// Not "anonymized": identity and names are stripped, but the text is whatever
// the learner typed and can contain personal detail. Hence the lifecycle below
// and the wording used in the privacy policy.
//
// Gated by `users.reviewOptIn` AND `wordLists.reviewOptIn`; the LLM audit needs
// `users.aiReviewOptIn` from every owner of the pair on top of that.
export const contentQualityReviews = pgTable(
  "content_quality_reviews",
  {
    // `p1:` + md5 over a length-prefixed [langFrom, langTo, known, target].
    // Defined once as a SQL fragment in lib/db/queries/quality-pool.ts and
    // computed nowhere else — see the note there before touching it.
    poolKey: text("pool_key").primaryKey(),
    languageFrom: text("language_from").notNull(),
    languageTo: text("language_to").notNull(),
    textKnown: text("text_known").notNull(),
    textTarget: text("text_target").notNull(),
    heuristicFlags: jsonb("heuristic_flags")
      .$type<QualityHeuristicFlag[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),
    heuristicVersion: integer("heuristic_version"),
    heuristicScannedAt: timestamp("heuristic_scanned_at"),
    // 0..100, higher is better. `smallint` to match migration 0062 — an
    // `integer` here reads identically at runtime but shows up as drift the
    // next time drizzle-kit generates. Cache is keyed by `llmAuditVersion`, so
    // bumping the constant invalidates every old score without a migration.
    llmScore: smallint("llm_score"),
    llmReason: text("llm_reason"),
    llmSuggestedTarget: text("llm_suggested_target"),
    llmModel: text("llm_model"),
    llmAuditVersion: integer("llm_audit_version"),
    llmCheckedAt: timestamp("llm_checked_at"),
    verdict: text("verdict").notNull().default("unreviewed"),
    // Both generations are snapshotted: an editor judges from heuristics,
    // audio, the LLM, and their own knowledge, so one number would lie about
    // what the verdict was actually based on. Null LLM version = never audited.
    reviewedHeuristicVersion: integer("reviewed_heuristic_version"),
    reviewedLlmAuditVersion: integer("reviewed_llm_audit_version"),
    suggestedKnown: text("suggested_known"),
    suggestedTarget: text("suggested_target"),
    suggestionNote: text("suggestion_note"),
    // Bumped whenever the suggestion's content changes, so a learner who
    // dismissed an earlier draft still gets shown an improved one.
    suggestionVersion: integer("suggestion_version").notNull().default(0),
    // The only user id here, and it is the editor — never the author.
    reviewedBy: uuid("reviewed_by").references(() => users.id, { onDelete: "set null" }),
    reviewedAt: timestamp("reviewed_at"),
    // Informational only. Rows are NEVER purged by this timestamp: a scan runs
    // with a limit, so most live rows carry a stale one at any given moment.
    // `purgeStaleQualityReviews` checks for a live source row instead.
    lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("content_quality_reviews_verdict_idx").on(table.verdict),
    index("content_quality_reviews_llm_score_idx").on(table.llmScore),
    check(
      "content_quality_reviews_verdict_check",
      sql`${table.verdict} in ('unreviewed', 'ok', 'suspect', 'suggested')`,
    ),
    check(
      "content_quality_reviews_llm_score_check",
      sql`${table.llmScore} is null or (${table.llmScore} >= 0 and ${table.llmScore} <= 100)`,
    ),
    check(
      "content_quality_reviews_suggestion_note_length_check",
      sql`${table.suggestionNote} is null or char_length(${table.suggestionNote}) <= 1000`,
    ),
  ],
).enableRLS();

// A learner declining one specific version of a suggestion. Keyed on the
// version so an improved suggestion is shown again instead of staying buried.
// The FK cascade is what keeps a purge from leaving orphans behind.
export const contentQualityDismissals = pgTable(
  "content_quality_dismissals",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    poolKey: text("pool_key")
      .notNull()
      .references(() => contentQualityReviews.poolKey, { onDelete: "cascade" }),
    suggestionVersion: integer("suggestion_version").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    primaryKey({
      name: "content_quality_dismissals_pkey",
      columns: [table.userId, table.poolKey, table.suggestionVersion],
    }),
  ],
).enableRLS();

// Durable record that a deleted user's Supabase auth identity still needs to be
// removed. Created inside the account-deletion DB transaction (so it commits
// atomically with the data erasure and survives a crash before the external
// Supabase admin call), then deleted once `auth.users` is gone. Holds only the
// auth id needed to finish erasure — no email or other personal data.
export const accountDeletionJobs = pgTable(
  "account_deletion_jobs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    supabaseAuthId: text("supabase_auth_id").notNull().unique(),
    attempts: integer("attempts").notNull().default(0),
    lastError: text("last_error"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("account_deletion_jobs_created_at_idx").on(table.createdAt)],
)
  // Deny-all RLS: this table is only ever touched server-side via the direct
  // Postgres connection (table owner, which bypasses RLS). Enabling RLS with no
  // policies keeps it unreachable through Supabase's PostgREST/anon API, since
  // it holds auth identifiers and has no reason to be publicly exposed.
  .enableRLS();

// Type exports for use in queries
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type UserLanguagePreference = typeof userLanguagePreferences.$inferSelect;
export type NewUserLanguagePreference = typeof userLanguagePreferences.$inferInsert;
export type UiTranslationCache = typeof uiTranslationCache.$inferSelect;
export type NewUiTranslationCache = typeof uiTranslationCache.$inferInsert;
export type UiLanguageRequest = typeof uiLanguageRequests.$inferSelect;
export type NewUiLanguageRequest = typeof uiLanguageRequests.$inferInsert;
export type UserProgress = typeof userProgress.$inferSelect;
export type NewUserProgress = typeof userProgress.$inferInsert;
export type ReviewEvent = typeof reviewEvents.$inferSelect;
export type NewReviewEvent = typeof reviewEvents.$inferInsert;
export type ActivitySegmentRow = typeof activitySegments.$inferSelect;
export type NewActivitySegment = typeof activitySegments.$inferInsert;
export type UserDevice = typeof userDevices.$inferSelect;
export type NewUserDevice = typeof userDevices.$inferInsert;
export type UserMemoryHook = typeof userMemoryHooks.$inferSelect;
export type NewUserMemoryHook = typeof userMemoryHooks.$inferInsert;
export type UserCategoryFilter = typeof userCategoryFilters.$inferSelect;
export type NewUserCategoryFilter = typeof userCategoryFilters.$inferInsert;
export type WordList = typeof wordLists.$inferSelect;
export type NewWordList = typeof wordLists.$inferInsert;
export type WordCategory = typeof wordCategories.$inferSelect;
export type NewWordCategory = typeof wordCategories.$inferInsert;
export type WordListItem = typeof wordListItems.$inferSelect;
export type NewWordListItem = typeof wordListItems.$inferInsert;
export type MediaAsset = typeof mediaAssets.$inferSelect;
export type NewMediaAsset = typeof mediaAssets.$inferInsert;
export type UserApiKey = typeof userApiKeys.$inferSelect;
export type NewUserApiKey = typeof userApiKeys.$inferInsert;
export type School = typeof schools.$inferSelect;
export type NewSchool = typeof schools.$inferInsert;
export type SchoolAccessCode = typeof schoolAccessCodes.$inferSelect;
export type NewSchoolAccessCode = typeof schoolAccessCodes.$inferInsert;
export type SchoolMembership = typeof schoolMemberships.$inferSelect;
export type NewSchoolMembership = typeof schoolMemberships.$inferInsert;
export type SchoolFeatureUsage = typeof schoolFeatureUsage.$inferSelect;
export type NewSchoolFeatureUsage = typeof schoolFeatureUsage.$inferInsert;
export type SchoolTranslationRequest = typeof schoolTranslationRequests.$inferSelect;
export type NewSchoolTranslationRequest = typeof schoolTranslationRequests.$inferInsert;
export type OAuthRateLimit = typeof oauthRateLimits.$inferSelect;
export type NewOAuthRateLimit = typeof oauthRateLimits.$inferInsert;
export type GoogleApiUsage = typeof googleApiUsage.$inferSelect;
export type NewGoogleApiUsage = typeof googleApiUsage.$inferInsert;
export type UserListSubscription = typeof userListSubscriptions.$inferSelect;
export type NewUserListSubscription = typeof userListSubscriptions.$inferInsert;
export type UserBlock = typeof userBlocks.$inferSelect;
export type NewUserBlock = typeof userBlocks.$inferInsert;
export type ContentReport = typeof contentReports.$inferSelect;
export type NewContentReport = typeof contentReports.$inferInsert;
export type AccountDeletionJob = typeof accountDeletionJobs.$inferSelect;
export type NewAccountDeletionJob = typeof accountDeletionJobs.$inferInsert;
export type WordChatUsage = typeof wordChatUsage.$inferSelect;
export type NewWordChatUsage = typeof wordChatUsage.$inferInsert;
export type WordChatCommit = typeof wordChatCommits.$inferSelect;
export type NewWordChatCommit = typeof wordChatCommits.$inferInsert;
