import { and, asc, desc, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import {
  mediaAssets,
  oauthRateLimits,
  userListSubscriptions,
  users,
  wordCategories,
  wordListItems,
  wordLists,
  type MediaAsset,
  type WordCategory,
  type WordList,
  type WordListItem,
} from "@/lib/db/schema";
import {
  countGoogleApiTextUnits,
  reserveGoogleApiUsage,
} from "@/lib/db/queries/google-api-usage";
import {
  getListLanguageCodeVariants,
  normalizeListLanguageCode,
} from "@/lib/db/queries/word-list-items/lists";
import { isPlayableAudioAsset } from "@/lib/audio-assets";
import { googleTranslate } from "@/lib/translation";
import { getLocalizedLanguageName, normalizeLanguageCode } from "@/lib/i18n/languages";

export const SERVER_AUTOGENERATE_MODEL = "anthropic/claude-sonnet-4.6";

const OPENROUTER_API_URL =
  process.env.OPENROUTER_API_BASE_URL?.replace(/\/+$/, "")
    ? `${process.env.OPENROUTER_API_BASE_URL.replace(/\/+$/, "")}/chat/completions`
    : "https://openrouter.ai/api/v1/chat/completions";
const MAX_GENERATED_ITEMS = 400;
const DEFAULT_LLM_ITEM_COUNT = 120;
const OPENROUTER_BATCH_SIZE = 80;
const MAX_PROMPT_CHARS = 36_000;
const RATE_BUCKET_PREFIX = "onboarding_common_autogenerate";
const RESOURCE_LANGUAGE_RANKS = new Map([
  ["en", 0],
  ["es", 1],
  ["fr", 2],
  ["de", 3],
  ["pt", 4],
  ["it", 5],
  ["cs", 6],
  ["uk", 7],
  ["vi", 8],
]);

type SourceSide = "known" | "target";
type GenerationProvider = "openrouter" | "google_fallback" | "seed_copy" | "reused_existing";
type SeedKind = "exact_pair" | "translation_base" | "llm_generated";

export type AutogeneratedCommonListResult = {
  list: WordList;
  itemCount: number;
  provider: GenerationProvider;
  seedKind: SeedKind | "existing_recommended";
  seedListId: string | null;
  reusedExisting: boolean;
};

type SeedCandidate = WordList & { itemCount: number };

type PreparedItem = {
  textKnown: string;
  textTarget: string;
  categoryName: string;
  knownAudioAssetId?: string | null;
  knownAudioStatus?: "none" | "pending" | "ready" | "failed";
  audioAssetId?: string | null;
  audioStatus?: "none" | "pending" | "ready" | "failed";
  canonicalWordId?: string | null;
  notes?: string | null;
};

type GeneratedCommonItem = {
  known: string;
  target: string;
  category?: string | null;
};

class OpenRouterServerGenerationError extends Error {
  constructor(message: string, readonly retryable: boolean) {
    super(message);
    this.name = "OpenRouterServerGenerationError";
  }
}

function parsePositiveInt(value: string | undefined, fallback: number) {
  if (!value) return fallback;
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : fallback;
}

function getMaxUserGenerationsPerDay() {
  return parsePositiveInt(process.env.OPENROUTER_SERVER_AUTOGENERATE_USER_DAILY_LIMIT, 3);
}

function getMaxGlobalGenerationsPerDay() {
  return parsePositiveInt(process.env.OPENROUTER_SERVER_AUTOGENERATE_GLOBAL_DAILY_LIMIT, 50);
}

function getUtcDayStart(date = new Date()) {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
}

function pairKey(languageFrom: string, languageTo: string) {
  return `${normalizeListLanguageCode(languageFrom)}:${normalizeListLanguageCode(languageTo)}`;
}

function lockKey(languageFrom: string, languageTo: string) {
  return `word_lists:recommended:${pairKey(languageFrom, languageTo)}`;
}

function getTextForSide(item: WordListItem, side: SourceSide) {
  return side === "known" ? item.textKnown : item.textTarget;
}

function getLanguageForSide(list: WordList, side: SourceSide) {
  return normalizeLanguageCode(side === "known" ? list.languageFrom : list.languageTo);
}

function getBaseLanguage(code: string) {
  return normalizeListLanguageCode(code).split("-")[0];
}

function getResourceRank(code: string) {
  return RESOURCE_LANGUAGE_RANKS.get(getBaseLanguage(code)) ?? 100;
}

function chooseSourceSide(seed: WordList, targetFrom: string, targetTo: string): SourceSide {
  const seedFrom = normalizeLanguageCode(seed.languageFrom);
  const seedTo = normalizeLanguageCode(seed.languageTo);
  if (seedFrom === targetFrom || seedFrom === targetTo) return "known";
  if (seedTo === targetFrom || seedTo === targetTo) return "target";
  return getResourceRank(seedFrom) <= getResourceRank(seedTo) ? "known" : "target";
}

function capitalizeFirst(value: string) {
  return value ? value.charAt(0).toUpperCase() + value.slice(1) : value;
}

// Names the autogenerated list in the user's known language, e.g. "Angličtina - Vietnamština".
function buildAutogeneratedListName(languageFrom: string, languageTo: string) {
  const fromName = getLocalizedLanguageName(languageFrom, languageFrom);
  const toName = getLocalizedLanguageName(languageTo, languageFrom);
  const from = fromName ? capitalizeFirst(fromName) : languageFrom.toUpperCase();
  const to = toName ? capitalizeFirst(toName) : languageTo.toUpperCase();
  return `${from} - ${to}`;
}

function cleanText(value: unknown) {
  return typeof value === "string" ? value.trim().replace(/\s+/g, " ") : "";
}

function cleanCategory(value: unknown) {
  const cleaned = cleanText(value);
  return cleaned || "Common";
}

// Matches the fork route's bilingual "<known> - <target>" category title format.
const CATEGORY_TITLE_SEPARATOR = " - ";

// Pull the single side to translate out of a (possibly already-bilingual)
// category title so "základ - basic" is not re-translated as a whole.
function extractCategorySourceText(
  name: string,
  seedLanguageFrom: string,
  seedLanguageTo: string,
  sourceLanguage: string,
): string {
  const idx = name.indexOf(CATEGORY_TITLE_SEPARATOR);
  if (idx === -1) return name;
  const fromSide = name.slice(0, idx);
  const toSide = name.slice(idx + CATEGORY_TITLE_SEPARATOR.length);
  return sourceLanguage === seedLanguageTo ? toSide : fromSide;
}

function parseGeneratedItems(value: unknown): GeneratedCommonItem[] {
  if (!value || typeof value !== "object") return [];
  const items = Array.isArray((value as { items?: unknown }).items)
    ? (value as { items: unknown[] }).items
    : [];
  const result: GeneratedCommonItem[] = [];
  const seen = new Set<string>();
  for (const item of items) {
    if (!item || typeof item !== "object") continue;
    const known = cleanText((item as { known?: unknown }).known);
    const target = cleanText((item as { target?: unknown }).target);
    if (!known || !target) continue;
    const key = `${known.toLowerCase()}\u0000${target.toLowerCase()}`;
    if (seen.has(key)) continue;
    seen.add(key);
    result.push({
      known,
      target,
      category: cleanCategory((item as { category?: unknown }).category),
    });
    if (result.length >= MAX_GENERATED_ITEMS) break;
  }
  return result;
}

async function reserveAutogenerateRateLimit(userId: string) {
  const bucketStart = getUtcDayStart();
  const bucketStartSql = bucketStart.toISOString();
  const buckets = [
    {
      key: `${RATE_BUCKET_PREFIX}:user:${userId}`,
      limit: getMaxUserGenerationsPerDay(),
      message: "Daily autogenerated list limit reached for this account.",
    },
    {
      key: `${RATE_BUCKET_PREFIX}:global`,
      limit: getMaxGlobalGenerationsPerDay(),
      message: "Daily autogenerated list limit reached. Please try again tomorrow.",
    },
  ];

  for (const bucket of buckets) {
    const rows = await db.execute(
      sql`
        INSERT INTO ${oauthRateLimits} (
          bucket_key,
          bucket_start,
          request_count,
          created_at,
          updated_at
        )
        VALUES (${bucket.key}, ${bucketStartSql}::timestamp, 1, now(), now())
        ON CONFLICT (bucket_key, bucket_start)
        DO UPDATE SET
          request_count = ${oauthRateLimits.requestCount} + 1,
          updated_at = now()
        WHERE ${oauthRateLimits.requestCount} < ${bucket.limit}
        RETURNING request_count
      `,
    );
    if (rows.length === 0) {
      throw new Error(bucket.message);
    }
  }
}

async function callOpenRouterJson(prompt: string) {
  const apiKey = process.env.OPENROUTER_SERVER_API_KEY;
  if (!apiKey) {
    throw new OpenRouterServerGenerationError("OpenRouter server key is not configured.", false);
  }

  const res = await fetch(OPENROUTER_API_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: SERVER_AUTOGENERATE_MODEL,
      response_format: { type: "json_object" },
      messages: [
        {
          role: "system",
          content:
            "You create high-quality beginner word lists for a language-learning app. Return only valid JSON matching the requested schema.",
        },
        { role: "user", content: prompt.slice(0, MAX_PROMPT_CHARS) },
      ],
      max_tokens: 12_000,
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => `${res.status} ${res.statusText}`);
    throw new OpenRouterServerGenerationError(
      `OpenRouter API error: ${res.status} ${detail.slice(0, 200)}`,
      res.status === 402 || res.status === 408 || res.status === 409 || res.status === 429 || res.status >= 500,
    );
  }

  const data = await res.json();
  const content = data?.choices?.[0]?.message?.content;
  if (typeof content !== "string") {
    throw new OpenRouterServerGenerationError("OpenRouter returned no JSON content.", true);
  }

  try {
    return JSON.parse(content) as unknown;
  } catch {
    throw new OpenRouterServerGenerationError("OpenRouter returned invalid JSON.", true);
  }
}

function buildSeedPrompt(input: {
  languageFrom: string;
  languageTo: string;
  sourceLanguage: string;
  sourceList: WordList;
  items: { source: string; known?: string | null; target?: string | null; category: string }[];
}) {
  return `
Create a common beginner word list for ${input.languageFrom} -> ${input.languageTo}.

Use the seed list "${input.sourceList.name}" as the source concept inventory.
Translate meanings naturally. Prefer common, everyday language and short beginner-friendly words or phrases.
Preserve the item count and order as much as possible.

Return JSON with this exact shape:
{
  "items": [
    { "known": "word in ${input.languageFrom}", "target": "word in ${input.languageTo}", "category": "short category name" }
  ]
}

Seed items, where source is ${input.sourceLanguage}:
${JSON.stringify(input.items)}
`.trim();
}

function buildNewListPrompt(languageFrom: string, languageTo: string, count: number) {
  return `
Create a common beginner word list for ${languageFrom} -> ${languageTo}.

Generate ${count} useful everyday entries across greetings, people, home, food, travel, time, numbers, feelings, verbs, adjectives, questions, and practical phrases.
Use natural native-speaker wording. Avoid duplicates, obscure vocabulary, proper names, and long explanations.

Return JSON with this exact shape:
{
  "items": [
    { "known": "word in ${languageFrom}", "target": "word in ${languageTo}", "category": "short category name" }
  ]
}
`.trim();
}

async function generateFromOpenRouterSeed(input: {
  languageFrom: string;
  languageTo: string;
  sourceLanguage: string;
  sourceList: WordList;
  sourceItems: { source: string; known?: string | null; target?: string | null; category: string }[];
}) {
  const generated: GeneratedCommonItem[] = [];
  for (let i = 0; i < input.sourceItems.length; i += OPENROUTER_BATCH_SIZE) {
    const chunk = input.sourceItems.slice(i, i + OPENROUTER_BATCH_SIZE);
    const parsed = await callOpenRouterJson(
      buildSeedPrompt({
        ...input,
        items: chunk,
      }),
    );
    generated.push(...parseGeneratedItems(parsed));
  }
  return generated.slice(0, MAX_GENERATED_ITEMS);
}

async function generateNewOpenRouterList(languageFrom: string, languageTo: string) {
  const parsed = await callOpenRouterJson(
    buildNewListPrompt(languageFrom, languageTo, DEFAULT_LLM_ITEM_COUNT),
  );
  return parseGeneratedItems(parsed).slice(0, DEFAULT_LLM_ITEM_COUNT);
}

async function translateTextsWithGoogle(input: {
  userId: string;
  texts: string[];
  from: string;
  to: string;
}) {
  const uniqueTexts = Array.from(new Set(input.texts.filter(Boolean)));
  if (uniqueTexts.length === 0 || input.from === input.to) {
    return new Map(uniqueTexts.map((text) => [text, text]));
  }

  const quota = await reserveGoogleApiUsage({
    userId: input.userId,
    scope: "translate",
    units: countGoogleApiTextUnits(uniqueTexts),
    requestCount: uniqueTexts.length,
  });
  if (!quota.allowed) {
    throw new Error(quota.message ?? "Google translation fallback limit reached.");
  }

  const results = await googleTranslate(uniqueTexts, input.from, input.to);
  return new Map(
    results
      .filter((result) => result.status === "ok" && result.translated)
      .map((result) => [result.text, result.translated as string]),
  );
}

// Translates seed category names into the same bilingual "<known> - <target>"
// titles a fork produces, keyed by the cleaned origin name. Falls back to the
// origin names if translation is disabled or the quota is unavailable.
async function buildSeedCategoryMapping(input: {
  userId: string;
  categories: WordCategory[];
  seedLanguageFrom: string;
  seedLanguageTo: string;
  sourceLanguage: string;
  languageFrom: string;
  languageTo: string;
  translate: boolean;
}): Promise<{ nameMap: Map<string, string>; orderedNames: string[] }> {
  const originNames = input.categories
    .map((category) => cleanCategory(category.name))
    .filter((name) => Boolean(name));
  const identity = () => {
    const nameMap = new Map(originNames.map((name) => [name, name]));
    return { nameMap, orderedNames: [...nameMap.values()] };
  };
  if (!input.translate || originNames.length === 0) return identity();

  const baseByName = new Map(
    originNames.map((name) => [
      name,
      extractCategorySourceText(
        name,
        input.seedLanguageFrom,
        input.seedLanguageTo,
        input.sourceLanguage,
      ),
    ]),
  );
  const baseTexts = Array.from(new Set([...baseByName.values()].filter(Boolean)));

  let knownMap: Map<string, string>;
  let targetMap: Map<string, string>;
  try {
    [knownMap, targetMap] = await Promise.all([
      translateTextsWithGoogle({
        userId: input.userId,
        texts: baseTexts,
        from: input.sourceLanguage,
        to: input.languageFrom,
      }),
      translateTextsWithGoogle({
        userId: input.userId,
        texts: baseTexts,
        from: input.sourceLanguage,
        to: input.languageTo,
      }),
    ]);
  } catch (err) {
    console.warn("[Get Word onboarding] category name translation failed; keeping origin names", {
      error: err instanceof Error ? err.message : err,
    });
    return identity();
  }

  const nameMap = new Map<string, string>();
  for (const name of originNames) {
    const base = baseByName.get(name) ?? name;
    const known = knownMap.get(base) ?? base;
    const target = targetMap.get(base) ?? base;
    nameMap.set(name, known === target ? known : `${known}${CATEGORY_TITLE_SEPARATOR}${target}`);
  }
  return { nameMap, orderedNames: originNames.map((name) => nameMap.get(name) ?? name) };
}

async function generateFromGoogleFallback(input: {
  userId: string;
  languageFrom: string;
  languageTo: string;
  sourceLanguage: string;
  seedItems: { source: string; category: string }[];
}) {
  const [known, target] = await Promise.all([
    translateTextsWithGoogle({
      userId: input.userId,
      texts: input.seedItems.map((item) => item.source),
      from: input.sourceLanguage,
      to: input.languageFrom,
    }),
    translateTextsWithGoogle({
      userId: input.userId,
      texts: input.seedItems.map((item) => item.source),
      from: input.sourceLanguage,
      to: input.languageTo,
    }),
  ]);

  return input.seedItems
    .map((item) => ({
      known: known.get(item.source) ?? "",
      target: target.get(item.source) ?? "",
      category: item.category,
    }))
    .filter((item) => item.known && item.target)
    .slice(0, MAX_GENERATED_ITEMS);
}

function toPreparedItems(
  items: GeneratedCommonItem[],
  options: {
    seedItems?: WordListItem[];
    seedSide?: SourceSide;
    seedLanguage?: string;
    languageFrom: string;
    languageTo: string;
    mediaById?: Map<string, MediaAsset>;
    // When provided, the item's category follows the (translated) origin list
    // instead of the per-item category returned by the generator.
    resolveCategoryName?: (seedItem: WordListItem) => string;
  },
): PreparedItem[] {
  return items.map((item, index) => {
    const seedItem = options.seedItems?.[index] ?? null;
    const categoryName = options.resolveCategoryName && seedItem
      ? options.resolveCategoryName(seedItem)
      : cleanCategory(item.category);
    const prepared: PreparedItem = {
      textKnown: item.known,
      textTarget: item.target,
      categoryName,
      canonicalWordId: seedItem?.id ?? null,
      notes: seedItem?.notes ?? null,
    };

    if (seedItem && options.seedSide && options.seedLanguage) {
      const copied =
        options.seedSide === "known"
          ? {
              assetId: seedItem.knownAudioAssetId,
              status: seedItem.knownAudioStatus,
            }
          : {
              assetId: seedItem.audioAssetId,
              status: seedItem.audioStatus,
            };
      const asset = copied.assetId ? options.mediaById?.get(copied.assetId) : null;
      if (asset && isPlayableAudioAsset(asset)) {
        if (options.seedLanguage === options.languageFrom) {
          prepared.knownAudioAssetId = copied.assetId;
          prepared.knownAudioStatus = copied.status;
        }
        if (options.seedLanguage === options.languageTo) {
          prepared.audioAssetId = copied.assetId;
          prepared.audioStatus = copied.status;
        }
      }
    }

    return prepared;
  });
}

async function findSeedCandidates() {
  const itemCounts = db
    .select({
      listId: wordListItems.listId,
      itemCount: sql<number>`count(*)::int`.as("item_count"),
    })
    .from(wordListItems)
    .groupBy(wordListItems.listId)
    .as("item_counts");

  return db
    .select({
      id: wordLists.id,
      ownerId: wordLists.ownerId,
      name: wordLists.name,
      description: wordLists.description,
      languageFrom: wordLists.languageFrom,
      languageTo: wordLists.languageTo,
      isPublic: wordLists.isPublic,
      isCommon: wordLists.isCommon,
      isRecommended: wordLists.isRecommended,
      isAutogenerated: wordLists.isAutogenerated,
      createdAt: wordLists.createdAt,
      updatedAt: wordLists.updatedAt,
      itemCount: sql<number>`coalesce(${itemCounts.itemCount}, 0)::int`,
    })
    .from(wordLists)
    .leftJoin(itemCounts, eq(wordLists.id, itemCounts.listId))
    .where(eq(wordLists.isPublic, true))
    .orderBy(desc(wordLists.isCommon), desc(wordLists.isRecommended), desc(wordLists.updatedAt))
    .limit(80);
}

function scoreTranslationSeed(seed: SeedCandidate, languageFrom: string, languageTo: string) {
  const seedFrom = normalizeListLanguageCode(seed.languageFrom);
  const seedTo = normalizeListLanguageCode(seed.languageTo);
  const targetFrom = normalizeListLanguageCode(languageFrom);
  const targetTo = normalizeListLanguageCode(languageTo);
  const overlaps = [seedFrom, seedTo].filter((code) => code === targetFrom || code === targetTo).length;
  const bestResourceRank = Math.min(getResourceRank(seedFrom), getResourceRank(seedTo));
  let score = 0;
  if (seed.isCommon) score += 1000;
  if (seed.isRecommended) score += 200;
  score += overlaps * 100;
  score += Math.min(seed.itemCount, MAX_GENERATED_ITEMS);
  score -= bestResourceRank * 5;
  return score;
}

function pickExactSeed(candidates: SeedCandidate[], languageFrom: string, languageTo: string) {
  const fromVariants = getListLanguageCodeVariants(languageFrom);
  const toVariants = getListLanguageCodeVariants(languageTo);
  return candidates
    .filter((seed) =>
      fromVariants.includes(normalizeListLanguageCode(seed.languageFrom)) &&
      toVariants.includes(normalizeListLanguageCode(seed.languageTo)) &&
      seed.itemCount > 0
    )
    .sort((a, b) =>
      Number(b.isRecommended) - Number(a.isRecommended) ||
      Number(b.isCommon) - Number(a.isCommon) ||
      b.itemCount - a.itemCount ||
      b.updatedAt.getTime() - a.updatedAt.getTime()
    )[0] ?? null;
}

function pickTranslationSeed(candidates: SeedCandidate[], languageFrom: string, languageTo: string) {
  return candidates
    .filter((seed) => seed.itemCount > 0)
    .sort((a, b) =>
      scoreTranslationSeed(b, languageFrom, languageTo) -
        scoreTranslationSeed(a, languageFrom, languageTo) ||
      b.updatedAt.getTime() - a.updatedAt.getTime()
    )[0] ?? null;
}

async function loadSeedDetails(seed: WordList) {
  const [categories, items] = await Promise.all([
    db
      .select()
      .from(wordCategories)
      .where(eq(wordCategories.listId, seed.id))
      .orderBy(asc(wordCategories.position)),
    db
      .select()
      .from(wordListItems)
      .where(eq(wordListItems.listId, seed.id))
      .orderBy(asc(wordListItems.position))
      .limit(MAX_GENERATED_ITEMS),
  ]);
  return { categories, items };
}

function categoryNameForItem(
  item: WordListItem,
  categoriesById: Map<string, WordCategory>,
) {
  return cleanCategory(item.categoryId ? categoriesById.get(item.categoryId)?.name : null);
}

async function buildPreparedItems(input: {
  userId: string;
  languageFrom: string;
  languageTo: string;
}): Promise<{
  items: PreparedItem[];
  // Final category names in origin order; insertion preserves this ordering.
  categories: string[];
  provider: GenerationProvider;
  seedKind: SeedKind;
  seedListId: string | null;
  description: string;
}> {
  const candidates = await findSeedCandidates();
  const exactSeed = pickExactSeed(candidates, input.languageFrom, input.languageTo);

  if (exactSeed) {
    const { categories, items } = await loadSeedDetails(exactSeed);
    const categoriesById = new Map(categories.map((category) => [category.id, category]));
    const assetIds = items
      .flatMap((item) => [item.knownAudioAssetId, item.audioAssetId])
      .filter((id): id is string => Boolean(id));
    const assets = assetIds.length > 0
      ? await db
          .select()
          .from(mediaAssets)
          .where(inArray(mediaAssets.id, assetIds))
      : [];
    const mediaById = new Map(assets.map((asset) => [asset.id, asset]));
    // Exact seed is already in the requested language pair, so category names are
    // kept as-is; we only preserve their origin order.
    const { orderedNames: categoryNames } = await buildSeedCategoryMapping({
      userId: input.userId,
      categories,
      seedLanguageFrom: getLanguageForSide(exactSeed, "known"),
      seedLanguageTo: getLanguageForSide(exactSeed, "target"),
      sourceLanguage: getLanguageForSide(exactSeed, "known"),
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      translate: false,
    });
    return {
      provider: "seed_copy",
      seedKind: "exact_pair",
      seedListId: exactSeed.id,
      categories: categoryNames,
      description: `Autogenerated common list copied from exact seed "${exactSeed.name}".`,
      items: items.map((item) => ({
        textKnown: item.textKnown,
        textTarget: item.textTarget ?? "",
        categoryName: categoryNameForItem(item, categoriesById),
        canonicalWordId: item.id,
        notes: item.notes,
        knownAudioAssetId: isPlayableAudioAsset(mediaById.get(item.knownAudioAssetId ?? ""))
          ? item.knownAudioAssetId
          : null,
        knownAudioStatus: item.knownAudioAssetId ? item.knownAudioStatus : "none",
        audioAssetId: isPlayableAudioAsset(mediaById.get(item.audioAssetId ?? ""))
          ? item.audioAssetId
          : null,
        audioStatus: item.audioAssetId ? item.audioStatus : "none",
      })).filter((item) => item.textKnown && item.textTarget),
    };
  }

  const translationSeed = pickTranslationSeed(candidates, input.languageFrom, input.languageTo);
  if (translationSeed) {
    const { categories, items } = await loadSeedDetails(translationSeed);
    const categoriesById = new Map(categories.map((category) => [category.id, category]));
    const sourceSide = chooseSourceSide(translationSeed, input.languageFrom, input.languageTo);
    const sourceLanguage = getLanguageForSide(translationSeed, sourceSide);
    const seedItems = items
      .map((item) => ({
        source: cleanText(getTextForSide(item, sourceSide)),
        known: item.textKnown,
        target: item.textTarget,
        category: categoryNameForItem(item, categoriesById),
      }))
      .filter((item) => item.source);
    // Categories follow the origin list (same order), translated into the same
    // bilingual titles a fork produces.
    const categoryMapping = await buildSeedCategoryMapping({
      userId: input.userId,
      categories,
      seedLanguageFrom: getLanguageForSide(translationSeed, "known"),
      seedLanguageTo: getLanguageForSide(translationSeed, "target"),
      sourceLanguage,
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      translate: true,
    });
    const resolveCategoryName = (seedItem: WordListItem) => {
      const originName = categoryNameForItem(seedItem, categoriesById);
      return categoryMapping.nameMap.get(originName) ?? originName;
    };
    const assetIds = items
      .flatMap((item) => [item.knownAudioAssetId, item.audioAssetId])
      .filter((id): id is string => Boolean(id));
    const assets = assetIds.length > 0
      ? await db
          .select()
          .from(mediaAssets)
          .where(inArray(mediaAssets.id, assetIds))
      : [];
    const mediaById = new Map(assets.map((asset) => [asset.id, asset]));

    try {
      await reserveAutogenerateRateLimit(input.userId);
      const generated = await generateFromOpenRouterSeed({
        languageFrom: input.languageFrom,
        languageTo: input.languageTo,
        sourceLanguage,
        sourceList: translationSeed,
        sourceItems: seedItems,
      });
      if (generated.length > 0) {
        return {
          provider: "openrouter",
          seedKind: "translation_base",
          seedListId: translationSeed.id,
          categories: categoryMapping.orderedNames,
          description: `Autogenerated with Claude Sonnet 4.6 via OpenRouter from seed "${translationSeed.name}".`,
          items: toPreparedItems(generated, {
            seedItems: items,
            seedSide: sourceSide,
            seedLanguage: sourceLanguage,
            languageFrom: input.languageFrom,
            languageTo: input.languageTo,
            mediaById,
            resolveCategoryName,
          }),
        };
      }
    } catch (err) {
      if (err instanceof OpenRouterServerGenerationError && !err.retryable) throw err;
      console.warn("[Get Word onboarding] OpenRouter common list generation fell back to Google", {
        error: err instanceof Error ? err.message : err,
      });
    }

    const generated = await generateFromGoogleFallback({
      userId: input.userId,
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      sourceLanguage,
      seedItems,
    });
    return {
      provider: "google_fallback",
      seedKind: "translation_base",
      seedListId: translationSeed.id,
      categories: categoryMapping.orderedNames,
      description: `Autogenerated with machine-generated Google Translate fallback from seed "${translationSeed.name}". Review translations before reusing broadly.`,
      items: toPreparedItems(generated, {
        seedItems: items,
        seedSide: sourceSide,
        seedLanguage: sourceLanguage,
        languageFrom: input.languageFrom,
        languageTo: input.languageTo,
        mediaById,
        resolveCategoryName,
      }),
    };
  }

  await reserveAutogenerateRateLimit(input.userId);
  const generated = await generateNewOpenRouterList(input.languageFrom, input.languageTo);
  return {
    provider: "openrouter",
    seedKind: "llm_generated",
    seedListId: null,
    // No origin list to mirror; categories follow the generator's own labels.
    categories: [],
    description: "Autogenerated with Claude Sonnet 4.6 via OpenRouter without an existing seed list.",
    items: toPreparedItems(generated, {
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
    }),
  };
}

async function findExistingRecommendedForPair(
  tx: Parameters<Parameters<typeof db.transaction>[0]>[0],
  languageFrom: string,
  languageTo: string,
) {
  const [existing] = await tx
    .select()
    .from(wordLists)
    .where(
      and(
        eq(wordLists.isRecommended, true),
        inArray(wordLists.languageFrom, getListLanguageCodeVariants(languageFrom)),
        inArray(wordLists.languageTo, getListLanguageCodeVariants(languageTo)),
      ),
    )
    .orderBy(desc(wordLists.isAutogenerated), desc(wordLists.updatedAt))
    .limit(1);
  return existing ?? null;
}

async function subscribeUserToList(
  tx: Parameters<Parameters<typeof db.transaction>[0]>[0],
  userId: string,
  listId: string,
) {
  await tx
    .insert(userListSubscriptions)
    .values({ userId, listId })
    .onConflictDoNothing();
}

async function reuseExistingRecommendedList(input: {
  userId: string;
  languageFrom: string;
  languageTo: string;
}): Promise<AutogeneratedCommonListResult | null> {
  return db.transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey(input.languageFrom, input.languageTo)})::bigint)`);
    const existing = await findExistingRecommendedForPair(tx, input.languageFrom, input.languageTo);
    if (!existing) return null;

    if (existing.ownerId !== input.userId) {
      await subscribeUserToList(tx, input.userId, existing.id);
    }
    const [{ itemCount } = { itemCount: 0 }] = await tx
      .select({ itemCount: sql<number>`count(*)::int` })
      .from(wordListItems)
      .where(eq(wordListItems.listId, existing.id));
    return {
      list: existing,
      itemCount,
      provider: "reused_existing",
      seedKind: "existing_recommended",
      seedListId: null,
      reusedExisting: true,
    };
  });
}

export async function autogenerateCommonWordListForUser(input: {
  userId: string;
  languageFrom: string;
  languageTo: string;
}): Promise<AutogeneratedCommonListResult> {
  const languageFrom = normalizeLanguageCode(input.languageFrom);
  const languageTo = normalizeLanguageCode(input.languageTo);
  if (!languageFrom || !languageTo || languageFrom === languageTo) {
    throw new Error("language_from and language_to are required and must be different");
  }

  const existing = await reuseExistingRecommendedList({
    userId: input.userId,
    languageFrom,
    languageTo,
  });
  if (existing) return existing;

  const prepared = await buildPreparedItems({
    userId: input.userId,
    languageFrom,
    languageTo,
  });
  if (prepared.items.length === 0) {
    throw new Error("Could not generate any usable words for this language pair.");
  }

  return db.transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey(languageFrom, languageTo)})::bigint)`);

    const existing = await findExistingRecommendedForPair(tx, languageFrom, languageTo);
    if (existing) {
      if (existing.ownerId !== input.userId) {
        await subscribeUserToList(tx, input.userId, existing.id);
      }
      const [{ itemCount } = { itemCount: 0 }] = await tx
        .select({ itemCount: sql<number>`count(*)::int` })
        .from(wordListItems)
        .where(eq(wordListItems.listId, existing.id));
      return {
        list: existing,
        itemCount,
        provider: "reused_existing" as const,
        seedKind: "existing_recommended" as const,
        seedListId: null,
        reusedExisting: true,
      };
    }

    const [editor] = await tx
      .select({ id: users.id })
      .from(users)
      .where(eq(users.userRole, "editor"))
      .orderBy(asc(users.createdAt))
      .limit(1);
    if (!editor) {
      throw new Error("No editor account is configured to own autogenerated common lists.");
    }

    const [list] = await tx
      .insert(wordLists)
      .values({
        ownerId: editor.id,
        name: buildAutogeneratedListName(languageFrom, languageTo),
        description: prepared.description,
        languageFrom,
        languageTo,
        isPublic: true,
        isRecommended: true,
        isAutogenerated: true,
      })
      .returning();

    // Create categories in the origin list's order first (only those actually
    // used), then append any leftover labels (e.g. the "Common" fallback or
    // generator-only categories) in their first-seen order.
    const usedCategoryNames = new Set(prepared.items.map((item) => item.categoryName));
    const categoryNames = Array.from(
      new Set([
        ...prepared.categories.filter((name) => usedCategoryNames.has(name)),
        ...prepared.items.map((item) => item.categoryName),
      ]),
    );
    const createdCategories = await tx
      .insert(wordCategories)
      .values(
        categoryNames.map((name, position) => ({
          listId: list.id,
          name,
          position,
          isSystem: false,
        })),
      )
      .returning();
    const categoryByName = new Map(createdCategories.map((category) => [category.name, category.id]));

    await tx.insert(wordListItems).values(
      prepared.items.map((item, position) => ({
        listId: list.id,
        categoryId: categoryByName.get(item.categoryName) ?? null,
        canonicalWordId: item.canonicalWordId ?? null,
        position,
        textKnown: item.textKnown,
        textTarget: item.textTarget,
        translationStatus: "translated" as const,
        knownAudioAssetId: item.knownAudioAssetId ?? null,
        knownAudioStatus: item.knownAudioAssetId ? item.knownAudioStatus ?? "ready" : "none",
        audioAssetId: item.audioAssetId ?? null,
        audioStatus: item.audioAssetId ? item.audioStatus ?? "ready" : "none",
        notes: item.notes ?? null,
      })),
    );

    if (list.ownerId !== input.userId) {
      await subscribeUserToList(tx, input.userId, list.id);
    }

    return {
      list,
      itemCount: prepared.items.length,
      provider: prepared.provider,
      seedKind: prepared.seedKind,
      seedListId: prepared.seedListId,
      reusedExisting: false,
    };
  });
}
