import { beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  cacheRows: [] as Array<{ sourceHash: string; messages: Record<string, string> }>,
  select: vi.fn(),
  insert: vi.fn(),
  values: vi.fn(),
  onConflictDoUpdate: vi.fn(),
  googleTranslate: vi.fn(),
}));

vi.mock('@/lib/db/client', () => ({
  db: {
    select: mocks.select,
    insert: mocks.insert,
  },
}));

vi.mock('@/lib/translation', () => ({
  googleTranslate: (...args: unknown[]) => mocks.googleTranslate(...args),
}));

import { getMessagesForLanguage, getSourceHash } from '../server';

describe('i18n server messages', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mocks.cacheRows = [];
    mocks.select.mockReturnValue({
      from: () => ({
        where: () => ({
          limit: () => mocks.cacheRows,
        }),
      }),
    });
    mocks.onConflictDoUpdate.mockResolvedValue(undefined);
    mocks.values.mockReturnValue({ onConflictDoUpdate: mocks.onConflictDoUpdate });
    mocks.insert.mockReturnValue({ values: mocks.values });
    mocks.googleTranslate.mockImplementation((values: string[]) =>
      Promise.resolve(values.map((value) => ({ status: 'ok', translated: `de:${value}` }))),
    );
  });

  it('serves bundled generated languages without Google', async () => {
    const payload = await getMessagesForLanguage('vi');

    expect(payload.language).toBe('vi');
    expect(payload.status).toBe('autogenerated');
    expect(mocks.select).not.toHaveBeenCalled();
    expect(mocks.googleTranslate).not.toHaveBeenCalled();
  });

  it('serves valid database cache before Google', async () => {
    mocks.cacheRows = [{
      sourceHash: getSourceHash(),
      messages: { 'common.settings': 'Einstellungen' },
    }];

    const payload = await getMessagesForLanguage('de');

    expect(payload.status).toBe('autogenerated');
    expect(payload.messages['common.settings']).toBe('Einstellungen');
    expect(mocks.googleTranslate).not.toHaveBeenCalled();
  });

  it('regenerates and updates cache when source hash is stale', async () => {
    mocks.cacheRows = [{
      sourceHash: 'old-hash',
      messages: { 'common.settings': 'Alt' },
    }];

    const payload = await getMessagesForLanguage('de');

    expect(payload.status).toBe('autogenerated');
    expect(mocks.googleTranslate).toHaveBeenCalledWith(expect.any(Array), 'en', 'de');
    expect(mocks.values).toHaveBeenCalledWith(expect.objectContaining({
      languageCode: 'de',
      sourceHash: getSourceHash(),
      provider: 'google',
      status: 'autogenerated',
    }));
    expect(payload.messages['common.settings']).toBe('de:Settings');
  });
});
