import { describe, expect, it, vi } from 'vitest';

import {
  fetchGoogleSupportedLanguages,
  getMessagesForLanguage,
  getSourceHash,
} from '../server';

describe('i18n server messages', () => {
  it('serves the supported-language catalog without a Google request', async () => {
    const fetchSpy = vi.spyOn(globalThis, 'fetch');

    const languages = await fetchGoogleSupportedLanguages('cs');

    expect(languages.some((language) => language.code === 'de')).toBe(true);
    expect(fetchSpy).not.toHaveBeenCalled();
    fetchSpy.mockRestore();
  });

  it('serves bundled generated languages without runtime translation', async () => {
    const payload = await getMessagesForLanguage('vi');

    expect(payload.language).toBe('vi');
    expect(payload.status).toBe('autogenerated');
  });

  it('always falls back to English for non-bundled languages', async () => {
    // A stale production variable must not be able to re-enable the expensive
    // runtime path while it is intentionally disabled in code.
    vi.stubEnv('RUNTIME_GOOGLE_UI_TRANSLATION_ENABLED', 'true');

    try {
      const payload = await getMessagesForLanguage('de');

      expect(payload.language).toBe('de');
      expect(payload.status).toBe('fallback');
      expect(payload.messages['common.settings']).toBe('Settings');
      expect(payload.sourceHash).toBe(getSourceHash());
    } finally {
      vi.unstubAllEnvs();
    }
  });
});
