import { describe, expect, it, vi } from 'vitest';
import { NextRequest } from 'next/server';

const mockGetMessagesForLanguage = vi.fn();

vi.mock('@/lib/i18n/server', () => ({
  getMessagesForLanguage: (...args: unknown[]) => mockGetMessagesForLanguage(...args),
}));

import { GET } from '../messages/route';

describe('GET /api/i18n/messages', () => {
  it('returns localized messages for the requested language', async () => {
    mockGetMessagesForLanguage.mockResolvedValue({
      language: 'de',
      status: 'autogenerated',
      sourceHash: 'hash',
      messages: { 'common.settings': 'Einstellungen' },
    });

    const res = await GET(new NextRequest('http://localhost/api/i18n/messages?language=de'));
    const body = await res.json();

    expect(res.status).toBe(200);
    expect(mockGetMessagesForLanguage).toHaveBeenCalledWith('de');
    expect(body.status).toBe('autogenerated');
    expect(body.messages['common.settings']).toBe('Einstellungen');
  });
});

