'use client';

import { useI18n } from '@/components/I18nProvider';
import type { WordList } from '@/features/lists/types';

export function ForkIcon({ className = '' }: { className?: string }) {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" className={className} aria-hidden="true">
      <circle cx="6" cy="5" r="2.25" stroke="currentColor" strokeWidth="2" />
      <circle cx="18" cy="6" r="2.25" stroke="currentColor" strokeWidth="2" />
      <circle cx="6" cy="19" r="2.25" stroke="currentColor" strokeWidth="2" />
      <path d="M6 7.25v9.5M8.25 5.75h4.5A5.25 5.25 0 0118 11v-2.75" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function ListBadges({ list }: { list: WordList }) {
  const { t } = useI18n();
  return (
    <>
      {list.isCommon && <span className="rounded bg-fresh/10 px-1.5 py-0.5 text-[10px] font-medium text-fresh">{t('lists.badgeCommon')}</span>}
      {list.isRecommended && <span className="rounded bg-accent/10 px-1.5 py-0.5 text-[10px] font-medium text-accent">{t('lists.badgeRecommended')}</span>}
      {list.isAutogenerated && <span className="rounded bg-text-soft/10 px-1.5 py-0.5 text-[10px] font-medium text-text-soft" title={t('lists.badgeAutogeneratedHint')}>{t('lists.badgeAutogenerated')}</span>}
      {list.audioIncomplete && <span className="rounded bg-fresh/10 px-1.5 py-0.5 text-[10px] font-medium text-fresh" title={t('lists.badgeAudioMissingHint')}>{t('lists.badgeAudioMissing')}</span>}
      {list.isPublic && <span className="rounded bg-done/10 px-1.5 py-0.5 text-[10px] font-medium text-done">{t('lists.badgePublic')}</span>}
      {!list.isPublic && !list.isCommon && <span className="rounded bg-text-soft/10 px-1.5 py-0.5 text-[10px] font-medium text-text-soft">{t('lists.badgePrivate')}</span>}
    </>
  );
}

export function ListSidebarItemButton({
  list,
  selected,
  ownedStyle = false,
  onSelect,
}: {
  list: WordList;
  selected: boolean;
  ownedStyle?: boolean;
  onSelect: () => void;
}) {
  return (
    <button
      type="button"
      className={ownedStyle
        ? `min-w-0 flex-1 text-left ${selected ? 'text-accent' : 'text-text'}`
        : `min-w-0 flex-1 rounded-md px-2 py-1.5 text-left transition-colors ${selected ? 'bg-background/60 text-accent' : 'text-text hover:bg-background/60'}`}
      onClick={onSelect}
    >
      <div className="truncate font-medium">{list.name}</div>
      <div className="mt-0.5 flex flex-wrap items-center gap-1 text-xs text-text-soft">
        <span>{list.languageFrom} → {list.languageTo}</span>
        <ListBadges list={list} />
      </div>
    </button>
  );
}
