const { execSync } = require('child_process');

const optionalWalletPackages = [
  '@coinbase/wallet-sdk',
  '@gemini-wallet/core',
  '@metamask/sdk',
  'porto/internal',
  'porto',
];

function createOptionalWalletAliases(emptyModule) {
  return Object.fromEntries(
    optionalWalletPackages.map((packageName) => [packageName, emptyModule])
  );
}

function getBuildVersion() {
  const base = require('./package.json').version;
  const explicitVersion = process.env.NEXT_PUBLIC_APP_VERSION || process.env.APP_VERSION;
  if (explicitVersion) {
    return explicitVersion;
  }

  const deployCommitSha = [
    process.env.VERCEL_GIT_COMMIT_SHA,
    process.env.GITHUB_SHA,
    process.env.COMMIT_SHA,
  ]
    .find((value) => typeof value === 'string' && value.trim().length > 0)
    ?.trim()
    .slice(0, 7);

  // Hosted deploy providers often use shallow git clones. On Vercel this made
  // `git rev-list --count HEAD` report values like 10, so use the deployment
  // commit SHA there instead of showing a misleading sequential version.
  if (process.env.VERCEL && deployCommitSha) {
    return `${base}-${deployCommitSha}`;
  }

  try {
    const isShallow = execSync('git rev-parse --is-shallow-repository', { stdio: ['pipe', 'pipe', 'ignore'] })
      .toString()
      .trim();
    if (isShallow === 'true') {
      throw new Error('Shallow git repository');
    }

    const count = execSync('git rev-list --count HEAD', { stdio: ['pipe', 'pipe', 'ignore'] })
      .toString()
      .trim();
    const [major, minor] = base.split('.');
    return `${major}.${minor}.${count}`;
  } catch {
    if (deployCommitSha) {
      return `${base}-${deployCommitSha}`;
    }

    try {
      const gitSha = execSync('git rev-parse --short HEAD', { stdio: ['pipe', 'pipe', 'ignore'] })
        .toString()
        .trim();
      return `${base}-${gitSha}`;
    } catch {
      // Fall through to package version when git metadata is not available.
    }

    return base;
  }
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_APP_VERSION: getBuildVersion(),
  },
  reactStrictMode: true,
  distDir: process.env.NODE_ENV === 'production' ? '.next' : '.next-dev',
  // Standalone output is only generated by `next build`; keeping it out of
  // `next dev` avoids dev serving production route bundles.
  ...(process.env.NODE_ENV === 'production' && { output: 'standalone' }),
  turbopack: {
    resolveAlias: createOptionalWalletAliases('./lib/wagmi-empty-module.js'),
  },
  async headers() {
    return [
      {
        source: '/sw.js',
        headers: [
          { key: 'Cache-Control', value: 'no-store, no-cache, must-revalidate' },
        ],
      },
      {
        source: '/:path*',
        headers: [
          // Popup-based social auth flows may need access to the opener window.
          { key: 'Cross-Origin-Opener-Policy', value: 'same-origin-allow-popups' },
        ],
      },
    ];
  },
};

module.exports = nextConfig;
