const { execSync } = require('child_process');

const optionalWalletPackages = [
  '@coinbase/wallet-sdk',
  '@gemini-wallet/core',
  '@metamask/sdk',
  'porto/internal',
  'porto',
];

function createOptionalWalletAliases(emptyModule) {
  return Object.fromEntries(
    optionalWalletPackages.map((packageName) => [packageName, emptyModule])
  );
}

function getBuildVersion() {
  const base = require('./package.json').version;
  if (process.env.NODE_ENV !== 'production') {
    return base;
  }

  try {
    const count = execSync('git rev-list --count HEAD', { stdio: ['pipe', 'pipe', 'ignore'] })
      .toString()
      .trim();
    // Replace patch segment with commit count so version auto-increments per commit
    const [major, minor] = base.split('.');
    return `${major}.${minor}.${count}`;
  } catch {
    return base;
  }
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_APP_VERSION: getBuildVersion(),
  },
  reactStrictMode: true,
  distDir: process.env.NODE_ENV === 'production' ? '.next' : '.next-dev',
  // Standalone output is only generated by `next build`; keeping it out of
  // `next dev` avoids dev serving production route bundles.
  ...(process.env.NODE_ENV === 'production' && { output: 'standalone' }),
  turbopack: {
    resolveAlias: createOptionalWalletAliases('./lib/wagmi-empty-module.js'),
  },
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          // Popup-based social auth flows may need access to the opener window.
          { key: 'Cross-Origin-Opener-Policy', value: 'same-origin-allow-popups' },
        ],
      },
    ];
  },
};

module.exports = nextConfig;
