const { execSync } = require('child_process');

function getVersionFromBuildNumber(base, buildNumber) {
  if (!/^\d+$/.test(buildNumber)) {
    return null;
  }

  const [major, minor] = base.split('.');
  return `${major}.${minor}.${buildNumber}`;
}

function getBuildVersion() {
  const base = require('./package.json').version;
  const explicitVersion = process.env.NEXT_PUBLIC_APP_VERSION || process.env.APP_VERSION;
  if (explicitVersion) {
    return explicitVersion;
  }

  // version.json is regenerated by the pre-commit hook so hosted builds (which
  // use shallow git clones) get an accurate version without reading git.
  try {
    const { version } = require('./version.json');
    if (typeof version === 'string' && version.trim().length > 0) {
      return version.trim();
    }
  } catch {
    // Fall through to build-number / git resolution below.
  }

  const explicitBuildNumber = [
    process.env.NEXT_PUBLIC_BUILD_NUMBER,
    process.env.BUILD_NUMBER,
    process.env.GITHUB_RUN_NUMBER,
    process.env.CI_PIPELINE_IID,
    process.env.CIRCLE_BUILD_NUM,
    process.env.TRAVIS_BUILD_NUMBER,
    process.env.BITBUCKET_BUILD_NUMBER,
  ]
    .find((value) => typeof value === 'string' && value.trim().length > 0)
    ?.trim();

  if (explicitBuildNumber) {
    const versionFromBuildNumber = getVersionFromBuildNumber(base, explicitBuildNumber);
    if (versionFromBuildNumber) {
      return versionFromBuildNumber;
    }
  }

  try {
    const isShallow = execSync('git rev-parse --is-shallow-repository', { stdio: ['pipe', 'pipe', 'ignore'] })
      .toString()
      .trim();
    if (isShallow === 'true') {
      throw new Error('Shallow git repository');
    }

    const count = execSync('git rev-list --count HEAD', { stdio: ['pipe', 'pipe', 'ignore'] })
      .toString()
      .trim();
    const [major, minor] = base.split('.');
    return `${major}.${minor}.${count}`;
  } catch {
    return base;
  }
}

function getAllowedDevOrigins() {
  const configured = process.env.NEXT_ALLOWED_DEV_ORIGINS;
  const origins = configured
    ? configured
        .split(',')
        .map((origin) => origin.trim())
        .filter(Boolean)
    : [];

  return Array.from(new Set(origins));
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_APP_VERSION: getBuildVersion(),
  },
  allowedDevOrigins: getAllowedDevOrigins(),
  devIndicators: false,
  reactStrictMode: true,
  distDir: process.env.NODE_ENV === 'production' ? '.next' : '.next-dev',
  // Standalone output is only generated by `next build`; keeping it out of
  // `next dev` avoids dev serving production route bundles.
  ...(process.env.NODE_ENV === 'production' && { output: 'standalone' }),
  async headers() {
    return [
      {
        source: '/sw.js',
        headers: [
          { key: 'Cache-Control', value: 'no-store, no-cache, must-revalidate' },
        ],
      },
      {
        source: '/:path*',
        headers: [
          // Popup-based social auth flows may need access to the opener window.
          { key: 'Cross-Origin-Opener-Policy', value: 'same-origin-allow-popups' },
        ],
      },
    ];
  },
};

module.exports = nextConfig;
