export const WORDS = [
  { "id": "w217", "category": ["basic", "word"], "cz": "Děkuji", "en": "Thank you", "vi": "Cảm ơn", "czPron": "DYE-ku-yi", "viPron": "gam un", "czAudio": "speech/cz/dekuji.mp3", "viAudio": "speech/vi/cam-on.mp3" },
  { "id": "w218", "category": ["basic", "word"], "cz": "Promiň", "en": "Sorry", "vi": "Xin lỗi", "czPron": "PRO-miň", "viPron": "sin loi", "czAudio": "speech/cz/promin.mp3", "viAudio": "speech/vi/xin-loi.mp3" },
  { "id": "w219", "category": ["basic", "word"], "cz": "Prosím", "en": "Please", "vi": "Làm ơn", "czPron": "PRO-sim", "viPron": "lam un", "czAudio": "speech/cz/prosim.mp3", "viAudio": "speech/vi/lam-on.mp3" },
  { "id": "w220", "category": ["basic", "word"], "cz": "to", "en": "it / that", "vi": "cái đó", "czPron": "to", "viPron": "kai dó", "czAudio": "speech/cz/to.mp3", "viAudio": "speech/vi/cai-do.mp3" },
  { "id": "w221", "category": ["basic", "word"], "cz": "láska", "en": "love (noun)", "vi": "tình yêu", "czPron": "LAS-ka", "viPron": "tiň jeu", "czAudio": "speech/cz/laska.mp3", "viAudio": "speech/vi/tinh-yeu.mp3" },
  { "id": "w222", "category": ["basic", "word"], "cz": "milovat", "en": "to love", "vi": "yêu", "czPron": "MI-lo-vat", "viPron": "jeu", "czAudio": "speech/cz/milovat.mp3", "viAudio": "speech/vi/yeu.mp3" },

  { "id": "w223", "category": ["basic", "word"], "cz": "jak", "en": "how", "vi": "như thế nào", "czPron": "yak", "viPron": "ňu thê nao", "czAudio": "speech/cz/jak.mp3", "viAudio": "speech/vi/nhu-the-nao.mp3" },
  { "id": "w224", "category": ["basic", "word"], "cz": "kdy", "en": "when", "vi": "khi nào", "czPron": "kdi", "viPron": "kchi nao", "czAudio": "speech/cz/kdy.mp3", "viAudio": "speech/vi/khi-nao.mp3" },
  { "id": "w225", "category": ["basic", "word"], "cz": "kde", "en": "where", "vi": "ở đâu", "czPron": "kde", "viPron": "ö dau", "czAudio": "speech/cz/kde.mp3", "viAudio": "speech/vi/o-dau.mp3" },
  { "id": "w226", "category": ["basic", "word"], "cz": "kdo", "en": "who", "vi": "ai", "czPron": "kdo", "viPron": "ai", "czAudio": "speech/cz/kdo.mp3", "viAudio": "speech/vi/ai.mp3" },
  { "id": "w227", "category": ["basic", "word"], "cz": "proč", "en": "why", "vi": "tại sao", "czPron": "proch", "viPron": "tai sao", "czAudio": "speech/cz/proc.mp3", "viAudio": "speech/vi/tai-sao.mp3" },
  { "id": "w228", "category": ["basic", "word"], "cz": "kolik", "en": "how much / how many", "vi": "bao nhiêu", "czPron": "KO-lik", "viPron": "bao ňieu", "czAudio": "speech/cz/kolik.mp3", "viAudio": "speech/vi/bao-nhieu.mp3" },
  { "id": "w229", "category": ["basic", "word"], "cz": "co", "en": "what", "vi": "cái gì", "czPron": "co", "viPron": "kai zi", "czAudio": "speech/cz/co.mp3", "viAudio": "speech/vi/cai-gi.mp3" },

  { "id": "w230", "category": ["basic", "word"], "cz": "v", "en": "in", "vi": "trong", "czPron": "v", "viPron": "trong", "czAudio": "speech/cz/v.mp3", "viAudio": "speech/vi/trong.mp3" },
  { "id": "w231", "category": ["basic", "word"], "cz": "s", "en": "with", "vi": "với", "czPron": "s", "viPron": "voi", "czAudio": "speech/cz/s.mp3", "viAudio": "speech/vi/voi.mp3" },
  { "id": "w232", "category": ["basic", "word"], "cz": "nad", "en": "above", "vi": "trên", "czPron": "nad", "viPron": "tren", "czAudio": "speech/cz/nad.mp3", "viAudio": "speech/vi/tren.mp3" },
  { "id": "w233", "category": ["basic", "word"], "cz": "pod", "en": "under", "vi": "dưới", "czPron": "pod", "viPron": "zuoi", "czAudio": "speech/cz/pod.mp3", "viAudio": "speech/vi/duoi.mp3" },
  { "id": "w234", "category": ["basic", "word"], "cz": "na", "en": "on", "vi": "trên", "czPron": "na", "viPron": "tren", "czAudio": "speech/cz/na.mp3", "viAudio": "speech/vi/tren.mp3" },
  { "id": "w235", "category": ["basic", "word"], "cz": "vedle", "en": "next to", "vi": "bên cạnh", "czPron": "VED-le", "viPron": "ben kanh", "czAudio": "speech/cz/vedle.mp3", "viAudio": "speech/vi/ben-canh.mp3" },
  { "id": "w236", "category": ["basic", "word"], "cz": "před", "en": "in front of", "vi": "trước", "czPron": "przhed", "viPron": "truok", "czAudio": "speech/cz/pred.mp3", "viAudio": "speech/vi/truoc.mp3" },
  { "id": "w237", "category": ["basic", "word"], "cz": "za", "en": "behind / after", "vi": "sau", "czPron": "za", "viPron": "sau", "czAudio": "speech/cz/za.mp3", "viAudio": "speech/vi/sau.mp3" },

  { "id": "w238", "category": ["basic", "word"], "cz": "vlevo", "en": "left", "vi": "bên trái", "czPron": "VLE-vo", "viPron": "ben trai", "czAudio": "speech/cz/vlevo.mp3", "viAudio": "speech/vi/ben-trai.mp3" },
  { "id": "w239", "category": ["basic", "word"], "cz": "vpravo", "en": "right", "vi": "bên phải", "czPron": "VPRA-vo", "viPron": "ben fai", "czAudio": "speech/cz/vpravo.mp3", "viAudio": "speech/vi/ben-phai.mp3" },
  { "id": "w240", "category": ["basic", "word"], "cz": "vepředu", "en": "in front", "vi": "phía trước", "czPron": "VE-przhe-du", "viPron": "fia truok", "czAudio": "speech/cz/vepredu.mp3", "viAudio": "speech/vi/phia-truoc.mp3" },
  { "id": "w241", "category": ["basic", "word"], "cz": "vzadu", "en": "behind", "vi": "phía sau", "czPron": "VZA-du", "viPron": "fia sau", "czAudio": "speech/cz/vzadu.mp3", "viAudio": "speech/vi/phia-sau.mp3" },
  { "id": "w242", "category": ["basic", "word"], "cz": "dole", "en": "down / below", "vi": "phía dưới", "czPron": "DO-le", "viPron": "fia zuoi", "czAudio": "speech/cz/dole.mp3", "viAudio": "speech/vi/phia-duoi.mp3" },
  { "id": "w243", "category": ["basic", "word"], "cz": "nahoře", "en": "up / above", "vi": "phía trên", "czPron": "NA-ho-rzhe", "viPron": "fia tren", "czAudio": "speech/cz/nahore.mp3", "viAudio": "speech/vi/phia-tren.mp3" },

  { "id": "w244", "category": ["basic", "word"], "cz": "rok", "en": "year", "vi": "năm", "czPron": "rok", "viPron": "nam", "czAudio": "speech/cz/rok.mp3", "viAudio": "speech/vi/nam.mp3" },
  { "id": "w245", "category": ["basic", "word"], "cz": "měsíc", "en": "month", "vi": "tháng", "czPron": "MYE-sic", "viPron": "thang", "czAudio": "speech/cz/mesic.mp3", "viAudio": "speech/vi/thang.mp3" },
  { "id": "w246", "category": ["basic", "word"], "cz": "den", "en": "day", "vi": "ngày", "czPron": "den", "viPron": "ngai", "czAudio": "speech/cz/den.mp3", "viAudio": "speech/vi/ngay.mp3" },
  { "id": "w247", "category": ["basic", "word"], "cz": "hodina", "en": "hour", "vi": "giờ", "czPron": "HO-di-na", "viPron": "zo", "czAudio": "speech/cz/hodina.mp3", "viAudio": "speech/vi/gio.mp3" },
  { "id": "w248", "category": ["basic", "word"], "cz": "minuta", "en": "minute", "vi": "phút", "czPron": "MI-nu-ta", "viPron": "fut", "czAudio": "speech/cz/minuta.mp3", "viAudio": "speech/vi/phut.mp3" },
  { "id": "w249", "category": ["basic", "word"], "cz": "vteřina", "en": "second", "vi": "giây", "czPron": "VTE-rzhi-na", "viPron": "zaj", "czAudio": "speech/cz/vterina.mp3", "viAudio": "speech/vi/giay.mp3" },

  { "id": "w250", "category": ["basic", "word"], "cz": "pondělí", "en": "Monday", "vi": "thứ hai", "czPron": "PON-dye-li", "viPron": "tu hai", "czAudio": "speech/cz/pondeli.mp3", "viAudio": "speech/vi/thu-hai.mp3" },
  { "id": "w251", "category": ["basic", "word"], "cz": "úterý", "en": "Tuesday", "vi": "thứ ba", "czPron": "U-te-ri", "viPron": "tu ba", "czAudio": "speech/cz/utery.mp3", "viAudio": "speech/vi/thu-ba.mp3" },
  { "id": "w252", "category": ["basic", "word"], "cz": "středa", "en": "Wednesday", "vi": "thứ tư", "czPron": "STRZHE-da", "viPron": "tu tu", "czAudio": "speech/cz/streda.mp3", "viAudio": "speech/vi/thu-tu.mp3" },
  { "id": "w253", "category": ["basic", "word"], "cz": "čtvrtek", "en": "Thursday", "vi": "thứ năm", "czPron": "CHTVER-tek", "viPron": "tu nam", "czAudio": "speech/cz/ctvrtek.mp3", "viAudio": "speech/vi/thu-nam.mp3" },
  { "id": "w254", "category": ["basic", "word"], "cz": "pátek", "en": "Friday", "vi": "thứ sáu", "czPron": "PA-tek", "viPron": "tu sau", "czAudio": "speech/cz/patek.mp3", "viAudio": "speech/vi/thu-sau.mp3" },
  { "id": "w255", "category": ["basic", "word"], "cz": "sobota", "en": "Saturday", "vi": "thứ bảy", "czPron": "SO-bo-ta", "viPron": "tu baj", "czAudio": "speech/cz/sobota.mp3", "viAudio": "speech/vi/thu-bay.mp3" },
  { "id": "w256", "category": ["basic", "word"], "cz": "neděle", "en": "Sunday", "vi": "chủ nhật", "czPron": "NE-dye-le", "viPron": "chu ňat", "czAudio": "speech/cz/nedele.mp3", "viAudio": "speech/vi/chu-nhat.mp3" },

  { "id": "w257", "category": ["basic", "word"], "cz": "leden", "en": "January", "vi": "tháng một", "czPron": "LE-den", "viPron": "thang mot", "czAudio": "speech/cz/leden.mp3", "viAudio": "speech/vi/thang-mot.mp3" },
  { "id": "w258", "category": ["basic", "word"], "cz": "únor", "en": "February", "vi": "tháng hai", "czPron": "U-nor", "viPron": "thang hai", "czAudio": "speech/cz/unor.mp3", "viAudio": "speech/vi/thang-hai.mp3" },
  { "id": "w259", "category": ["basic", "word"], "cz": "březen", "en": "March", "vi": "tháng ba", "czPron": "BRZHE-zen", "viPron": "thang ba", "czAudio": "speech/cz/brezen.mp3", "viAudio": "speech/vi/thang-ba.mp3" },
  { "id": "w260", "category": ["basic", "word"], "cz": "duben", "en": "April", "vi": "tháng tư", "czPron": "DU-ben", "viPron": "thang tu", "czAudio": "speech/cz/duben.mp3", "viAudio": "speech/vi/thang-tu.mp3" },
  { "id": "w261", "category": ["basic", "word"], "cz": "květen", "en": "May", "vi": "tháng năm", "czPron": "KVYE-ten", "viPron": "thang nam", "czAudio": "speech/cz/kveten.mp3", "viAudio": "speech/vi/thang-nam.mp3" },
  { "id": "w262", "category": ["basic", "word"], "cz": "červen", "en": "June", "vi": "tháng sáu", "czPron": "CHER-ven", "viPron": "thang sau", "czAudio": "speech/cz/cerven.mp3", "viAudio": "speech/vi/thang-sau.mp3" },
  { "id": "w263", "category": ["basic", "word"], "cz": "červenec", "en": "July", "vi": "tháng bảy", "czPron": "CHER-ve-nec", "viPron": "thang baj", "czAudio": "speech/cz/cervenec.mp3", "viAudio": "speech/vi/thang-bay.mp3" },
  { "id": "w264", "category": ["basic", "word"], "cz": "srpen", "en": "August", "vi": "tháng tám", "czPron": "SR-pen", "viPron": "thang tam", "czAudio": "speech/cz/srpen.mp3", "viAudio": "speech/vi/thang-tam.mp3" },
  { "id": "w265", "category": ["basic", "word"], "cz": "září", "en": "September", "vi": "tháng chín", "czPron": "ZA-rzhi", "viPron": "thang chin", "czAudio": "speech/cz/zari.mp3", "viAudio": "speech/vi/thang-chin.mp3" },
  { "id": "w266", "category": ["basic", "word"], "cz": "říjen", "en": "October", "vi": "tháng mười", "czPron": "RZHI-yen", "viPron": "thang muoi", "czAudio": "speech/cz/rijen.mp3", "viAudio": "speech/vi/thang-muoi.mp3" },
  { "id": "w267", "category": ["basic", "word"], "cz": "listopad", "en": "November", "vi": "tháng mười một", "czPron": "LIS-to-pad", "viPron": "thang muoi mot", "czAudio": "speech/cz/listopad.mp3", "viAudio": "speech/vi/thang-muoi-mot.mp3" },
  { "id": "w268", "category": ["basic", "word"], "cz": "prosinec", "en": "December", "vi": "tháng mười hai", "czPron": "PRO-si-nec", "viPron": "thang muoi hai", "czAudio": "speech/cz/prosinec.mp3", "viAudio": "speech/vi/thang-muoi-hai.mp3" },

  { "id": "w269", "category": ["basic", "word"], "cz": "nula", "en": "zero", "vi": "không", "czPron": "NU-la", "viPron": "khong", "czAudio": "speech/cz/nula.mp3", "viAudio": "speech/vi/khong.mp3" },
  { "id": "w270", "category": ["basic", "word"], "cz": "jedna", "en": "one", "vi": "một", "czPron": "YED-na", "viPron": "mot", "czAudio": "speech/cz/jedna.mp3", "viAudio": "speech/vi/mot.mp3" },
  { "id": "w271", "category": ["basic", "word"], "cz": "dvě", "en": "two", "vi": "hai", "czPron": "dvye", "viPron": "hai", "czAudio": "speech/cz/dve.mp3", "viAudio": "speech/vi/hai.mp3" },
  { "id": "w272", "category": ["basic", "word"], "cz": "tři", "en": "three", "vi": "ba", "czPron": "trzhi", "viPron": "ba", "czAudio": "speech/cz/tri.mp3", "viAudio": "speech/vi/ba.mp3" },
  { "id": "w273", "category": ["basic", "word"], "cz": "čtyři", "en": "four", "vi": "bốn", "czPron": "CHTI-rzhi", "viPron": "bon", "czAudio": "speech/cz/ctyri.mp3", "viAudio": "speech/vi/bon.mp3" },
  { "id": "w274", "category": ["basic", "word"], "cz": "pět", "en": "five", "vi": "năm", "czPron": "pyet", "viPron": "nam", "czAudio": "speech/cz/pet.mp3", "viAudio": "speech/vi/nam.mp3" },
  { "id": "w275", "category": ["basic", "word"], "cz": "šest", "en": "six", "vi": "sáu", "czPron": "shest", "viPron": "sau", "czAudio": "speech/cz/sest.mp3", "viAudio": "speech/vi/sau.mp3" },
  { "id": "w276", "category": ["basic", "word"], "cz": "sedm", "en": "seven", "vi": "bảy", "czPron": "sedm", "viPron": "baj", "czAudio": "speech/cz/sedm.mp3", "viAudio": "speech/vi/bay.mp3" },
  { "id": "w277", "category": ["basic", "word"], "cz": "osm", "en": "eight", "vi": "tám", "czPron": "osm", "viPron": "tam", "czAudio": "speech/cz/osm.mp3", "viAudio": "speech/vi/tam.mp3" },
  { "id": "w278", "category": ["basic", "word"], "cz": "devět", "en": "nine", "vi": "chín", "czPron": "DE-vyet", "viPron": "chin", "czAudio": "speech/cz/devet.mp3", "viAudio": "speech/vi/chin.mp3" },
  { "id": "w279", "category": ["basic", "word"], "cz": "deset", "en": "ten", "vi": "mười", "czPron": "DE-set", "viPron": "muoi", "czAudio": "speech/cz/deset.mp3", "viAudio": "speech/vi/muoi.mp3" },
  { "id": "w280", "category": ["basic", "word"], "cz": "jedenáct", "en": "eleven", "vi": "mười một", "czPron": "YE-de-nact", "viPron": "muoi mot", "czAudio": "speech/cz/jedenact.mp3", "viAudio": "speech/vi/muoi-mot.mp3" },
  { "id": "w281", "category": ["basic", "word"], "cz": "dvanáct", "en": "twelve", "vi": "mười hai", "czPron": "DVA-nact", "viPron": "muoi hai", "czAudio": "speech/cz/dvanact.mp3", "viAudio": "speech/vi/muoi-hai.mp3" },
  { "id": "w282", "category": ["basic", "word"], "cz": "dvacet", "en": "twenty", "vi": "hai mươi", "czPron": "DVA-cet", "viPron": "hai muoi", "czAudio": "speech/cz/dvacet.mp3", "viAudio": "speech/vi/hai-muoi.mp3" },
  { "id": "w283", "category": ["basic", "word"], "cz": "dvacet dva", "en": "twenty-two", "vi": "hai mươi hai", "czPron": "DVA-cet DVA", "viPron": "hai muoi hai", "czAudio": "speech/cz/dvacet-dva.mp3", "viAudio": "speech/vi/hai-muoi-hai.mp3" },
  { "id": "w284", "category": ["basic", "word"], "cz": "třicet", "en": "thirty", "vi": "ba mươi", "czPron": "TRZHI-cet", "viPron": "ba muoi", "czAudio": "speech/cz/tricet.mp3", "viAudio": "speech/vi/ba-muoi.mp3" },
  { "id": "w285", "category": ["basic", "word"], "cz": "sto", "en": "hundred", "vi": "một trăm", "czPron": "sto", "viPron": "mot tram", "czAudio": "speech/cz/sto.mp3", "viAudio": "speech/vi/mot-tram.mp3" },
  { "id": "w286", "category": ["basic", "word"], "cz": "tisíc", "en": "thousand", "vi": "một nghìn", "czPron": "TI-sic", "viPron": "mot ngin", "czAudio": "speech/cz/tisic.mp3", "viAudio": "speech/vi/mot-nghin.mp3" },
  { "id": "w287", "category": ["basic", "word"], "cz": "milion", "en": "million", "vi": "một triệu", "czPron": "MI-li-on", "viPron": "mot trieu", "czAudio": "speech/cz/milion.mp3", "viAudio": "speech/vi/mot-trieu.mp3" },
  { "id": "w288", "category": ["basic", "word"], "cz": "miliarda", "en": "billion", "vi": "một tỷ", "czPron": "MI-li-ar-da", "viPron": "mot ti", "czAudio": "speech/cz/miliarda.mp3", "viAudio": "speech/vi/mot-ty.mp3" },
  { "id": "w289", "category": ["basic", "word"], "cz": "bilion", "en": "trillion", "vi": "một nghìn tỷ", "czPron": "BI-li-on", "viPron": "mot ngin ti", "czAudio": "speech/cz/bilion.mp3", "viAudio": "speech/vi/mot-nghin-ty.mp3" },
  { "id": "w290", "category": ["basic", "word"], "cz": "trilion", "en": "quadrillion", "vi": "một triệu tỷ", "czPron": "TRI-li-on", "viPron": "mot trieu ti", "czAudio": "speech/cz/trilion.mp3", "viAudio": "speech/vi/mot-trieu-ty.mp3" },
  { "id": "w291", "category": ["basic", "word"], "cz": "sto deset tisíc pětset třicet šest", "en": "110,536", "vi": "một trăm mười nghìn năm trăm ba mươi sáu", "czPron": "sto DE-set TI-sic PYET-set TRZHI-cet shest", "viPron": "mot tram muoi ngin nam tram ba muoi sau", "czAudio": "speech/cz/sto-deset-tisic-petset-tricet-sest.mp3", "viAudio": "speech/vi/110536.mp3" },

  { "id": "w292", "category": ["basic", "word"], "cz": "plus", "en": "plus", "vi": "cộng", "czPron": "plus", "viPron": "kong", "czAudio": "speech/cz/plus.mp3", "viAudio": "speech/vi/cong.mp3" },
  { "id": "w293", "category": ["basic", "word"], "cz": "mínus", "en": "minus", "vi": "trừ", "czPron": "MI-nus", "viPron": "tru", "czAudio": "speech/cz/minus.mp3", "viAudio": "speech/vi/tru.mp3" },
  { "id": "w294", "category": ["basic", "word"], "cz": "krát", "en": "times", "vi": "nhân", "czPron": "krat", "viPron": "ňan", "czAudio": "speech/cz/krat.mp3", "viAudio": "speech/vi/nhan.mp3" },
  { "id": "w295", "category": ["basic", "word"], "cz": "děleno", "en": "divided by", "vi": "chia", "czPron": "DYE-le-no", "viPron": "chia", "czAudio": "speech/cz/deleno.mp3", "viAudio": "speech/vi/chia.mp3" },

  { "id": "w296", "category": ["basic", "word"], "cz": "tma", "en": "darkness", "vi": "bóng tối", "czPron": "tma", "viPron": "bong toi", "czAudio": "speech/cz/tma.mp3", "viAudio": "speech/vi/bong-toi.mp3" },
  { "id": "w297", "category": ["basic", "word"], "cz": "světlo", "en": "light", "vi": "ánh sáng", "czPron": "SVYET-lo", "viPron": "anh sang", "czAudio": "speech/cz/svetlo.mp3", "viAudio": "speech/vi/anh-sang.mp3" },
  { "id": "w298", "category": ["basic", "word"], "cz": "slunce", "en": "sun", "vi": "mặt trời", "czPron": "SLUN-ce", "viPron": "mat troi", "czAudio": "speech/cz/slunce.mp3", "viAudio": "speech/vi/mat-troi.mp3" },

  { "id": "w299", "category": ["basic", "word"], "cz": "dům", "en": "house", "vi": "nhà", "czPron": "dum", "viPron": "ňa", "czAudio": "speech/cz/dum.mp3", "viAudio": "speech/vi/nha.mp3" },
  { "id": "w300", "category": ["basic", "word"], "cz": "obchod", "en": "shop", "vi": "cửa hàng", "czPron": "OB-khod", "viPron": "cua hang", "czAudio": "speech/cz/obchod.mp3", "viAudio": "speech/vi/cua-hang.mp3" },
  { "id": "w301", "category": ["basic", "word"], "cz": "pokoj", "en": "room", "vi": "phòng", "czPron": "PO-koy", "viPron": "fong", "czAudio": "speech/cz/pokoj.mp3", "viAudio": "speech/vi/phong.mp3" },
  { "id": "w302", "category": ["basic", "word"], "cz": "ulice", "en": "street", "vi": "đường phố", "czPron": "U-li-ce", "viPron": "duong fo", "czAudio": "speech/cz/ulice.mp3", "viAudio": "speech/vi/duong-pho.mp3" },
  { "id": "w303", "category": ["basic", "word"], "cz": "město", "en": "city", "vi": "thành phố", "czPron": "MYES-to", "viPron": "thanh fo", "czAudio": "speech/cz/mesto.mp3", "viAudio": "speech/vi/thanh-pho.mp3" },
  { "id": "w304", "category": ["basic", "word"], "cz": "vesnice", "en": "village", "vi": "làng", "czPron": "VES-ni-ce", "viPron": "lang", "czAudio": "speech/cz/vesnice.mp3", "viAudio": "speech/vi/lang.mp3" },

  { "id": "w305", "category": ["basic", "phrase"], "cz": "Pracuji jako", "en": "I work as", "vi": "Tôi làm việc như", "czPron": "PRA-cu-yi YA-ko", "viPron": "toi lam viek ňu", "czAudio": "speech/cz/pracuji-jako.mp3", "viAudio": "speech/vi/toi-lam-viec-nhu.mp3" },
  { "id": "w306", "category": ["basic", "phrase"], "cz": "Bydlím v", "en": "I live in", "vi": "Tôi sống ở", "czPron": "BID-lim v", "viPron": "toi song ö", "czAudio": "speech/cz/bydlim-v.mp3", "viAudio": "speech/vi/toi-song-o.mp3" },
  { "id": "w307", "category": ["basic", "phrase"], "cz": "Jsem v Česku 1 rok", "en": "I've been in the Czech Republic for 1 year", "vi": "Tôi ở Séc được 1 năm", "czPron": "ysem v CHES-ku YED-na rok", "viPron": "toi ö sek duok mot nam", "czAudio": "speech/cz/jsem-v-cesku-1-rok.mp3", "viAudio": "speech/vi/toi-o-sec-mot-nam.mp3" },
  { "id": "w308", "category": ["basic", "phrase"], "cz": "Jmenuji se", "en": "My name is", "vi": "Tên tôi là", "czPron": "YME-nu-yi se", "viPron": "ten toi la", "czAudio": "speech/cz/jmenuji-se.mp3", "viAudio": "speech/vi/ten-toi-la.mp3" }
]