export const WORDS = [
  {
    cz: "Dobrý den",
    en: "Good day",
    vi: "Xin chào",
    czPron: "DO-bri den",
    viPron: "sin čao",
    czAudio: "speech/cz/dobry-den.mp3",
    viHint: "(đô) (bởi) (đến) with r in the middle",
  },
  {
    cz: "Děkuji 🙏",
    en: "Thank you",
    vi: "Cảm ơn",
    czPron: "DĚ-ku-ji",
    viPron: "kam ən",
    czAudio: "speech/cz/dekuji.mp3",
    viHint: "(dê) (cú) (gì): goat bows head.",
  },
  {
    cz: "Prosím 🙏",
    en: "Please",
    vi: "Làm ơn",
    czPron: "PRO-sím",
    viPron: "lam ən",
    czAudio: "speech/cz/prosim.mp3",
    czHint: "(lam)pa je (on)zapnutá",
    viHint: "(pro)fessional (xin)",
  },
  {
    cz: "Jak se máte? 🙂",
    en: "How are you?",
    vi: "Bạn khỏe không?",
    czPron: "JAK se MÁ-te?",
    viPron: "ban kchue khong",
    czAudio: "speech/cz/jak-se-mate.mp3",
    viAudio: "speech/vi/ban-khoe-khong.mp3",
    czHint: "Banán křupe, Kong zívá.",
    viHint: "(giắc xe) (má tê) lift up/start conversation",
  },
  {
    cz: "Posaďte se, prosím. 💺",
    en: "Please sit down.",
    vi: "Mời bạn ngồi.",
    czPron: "PO-sať-te se PRO-sím",
    viPron: "moi ban ngoi",
    czAudio: "speech/cz/posadte-se-prosim.mp3",
    viAudio: "speech/vi/xin-moi-ngoi.mp3",
    viHint: "phở sát-tê-sờ pro-xin",
  },
  {
    cz: "Bolí to? 😬",
    en: "Does it hurt?",
    vi: "Có đau không?",
    czPron: "BO-lí to?",
    viPron: "ko dau khong",
    czAudio: "speech/cz/boli-to.mp3",
    viAudio: "speech/vi/co-djau-khong.mp3",
    viHint: "(Boli)via country with injured knee",
  },
  {
    cz: "Tady? 👉",
    en: "Here?",
    vi: "Ở đây hả?",
    czPron: "TA-di?",
    viPron: "a daj ha",
    czAudio: "speech/cz/tady.mp3",
    viAudio: "speech/vi/o-djay.mp3",
    czHint: "A dej hák; někdo po mně chce hák",
    viHint: "Ta đi? finger points at map.",
  },
  {
    cz: "Nashle / Na shledanou 👋",
    en: "Goodbye",
    vi: "Tạm biệt",
    czPron: "NA-shle / NA skhle-da-no",
    viPron: "tam biet",
    czAudio: "speech/cz/na-shledanou.mp3",
    viAudio: "speech/vi/tam-biet.mp3",
    czHint: "Tam běž; mává na rozloučenou",
    viHint: "(NAS)A -the space company, +hle - look at this; spaceship flies away",
  },
  {
    cz: "Máte představu? 💡",
    en: "Do you have an idea?",
    vi: "Bạn có ý tưởng gì không?",
    czPron: "MÁ-te PŘED-sta-vu?",
    viPron: "ban ko i tuong zi khong",
    czAudio: "speech/cz/mate-predstavu.mp3",
    viAudio: "speech/vi/ban-co-y-tuong-gi-khong.mp3",
  },
  {
    cz: "Jakou barvu? 🎨",
    en: "What colour?",
    vi: "Màu nào?",
    czPron: "JA-kou BAR-vu?",
    viPron: "mau nao",
    czAudio: "speech/cz/jakou-barvu.mp3",
    czHint: "Mňau! Nao! kočka kouše pastelku.",
  },
  {
    cz: "Tvar (nehtu)",
    en: "(Nail) shape",
    vi: "Hình dạng (móng)",
    czPron: "TVAR (NE-tu)",
    viPron: "hin jang mong",
    czAudio: "speech/cz/tvar-nehtu.mp3",
    viHint: "(TV) b(ar)",
  },
  {
    cz: "Kulatý ⭕",
    en: "Round",
    vi: "Tròn",
    czPron: "KU-la-tý",
    viPron: "tron",
    czAudio: "speech/cz/kulaty.mp3",
  },
  {
    cz: "Hranatý ⬛",
    en: "Square",
    vi: "Vuông",
    czPron: "HRA-na-tý",
    viPron: "vuong",
    czAudio: "speech/cz/hranaty.mp3",
    czHint: "Vůně písmena g",
    viHint: "Hạt nát",
  },
  {
    cz: "Lak",
    en: "Nail polish",
    vi: "Sơn móng",
    czPron: "LAK",
    viPron: "son mong",
    czAudio: "speech/cz/lak.mp3",
    czHint: "Syn mongola",
    viHint: "Lắc! shaking with hand",
  },
  {
    cz: "Manikúra 💅",
    en: "Manicure",
    vi: "Làm móng tay",
    czPron: "MA-ni-kú-ra",
    viPron: "lam mong taj",
    czAudio: "speech/cz/manikura.mp3",
    viAudio: "speech/vi/lam-mong-tay.mp3",
    viHint: "Ma-ni cưa",
  },
  {
    cz: "Pedikúra 🦶",
    en: "Pedicure",
    vi: "Chăm sóc chân",
    czPron: "PE-di-kú-ra",
    viPron: "čam sok čan",
    czAudio: "speech/cz/pedikura.mp3",
    viAudio: "speech/vi/lam-mong-chan.mp3",
  },
  {
    cz: "Gelové nehty ✨",
    en: "Gel nails",
    vi: "Móng gel",
    czPron: "GE-lo-vé NE-ty",
    viPron: "mong gel",
    czAudio: "speech/cz/gelove-nehty.mp3",
    viAudio: "speech/vi/mong-gel.mp3",
  },
  {
    cz: "Hotovo ✅",
    en: "Finished / Done",
    vi: "Xong rồi",
    czPron: "HO-to-vo",
    viPron: "xong zoj",
    czAudio: "speech/cz/hotovo.mp3",
    viAudio: "speech/vi/xong-roi.mp3",
  },
  {
    cz: "Ruka / Ruce",
    en: "Hand / Hands",
    vi: "Tay / Hai tay",
    czPron: "RU-ka / RU-ce",
    viPron: "taj / haj taj",
    czAudio: ["speech/cz/ruka.mp3", "speech/cz/ruce.mp3"],
    viAudio: ["speech/vi/tay.mp3", "speech/vi/hai-tay.mp3"],
  },
  {
    cz: "Noha / Nohy",
    en: "Foot / Feet",
    vi: "Chân / Hai chân",
    czPron: "NO-ha / NO-hy",
    viPron: "čan / haj čan",
    czAudio: ["speech/cz/noha.mp3", "speech/cz/nohy.mp3"],
    viAudio: ["speech/vi/chan.mp3", "speech/vi/hai-chan.mp3"],
  },
  {
    cz: "Nehet / Nehty",
    en: "Nail / Nails",
    vi: "Móng tay / Móng",
    czPron: "NE-het / NE-ty",
    viPron: "mong taj / mong",
    czAudio: ["speech/cz/nehet.mp3", "speech/cz/nehty.mp3"],
    viAudio: "speech/vi/mong-tay.mp3",
  },
  {
    cz: "Pilník",
    en: "Nail file",
    vi: "Cây dũa móng",
    czPron: "PIL-ník",
    viPron: "kaj zua mong",
    czAudio: "speech/cz/pilnik.mp3",
    viAudio: "speech/vi/dua.mp3",
  },
  {
    cz: "Nůžky ✂️",
    en: "Scissors",
    vi: "Cái kéo",
    czPron: "NŮŠ-ky",
    viPron: "kaj keo",
    czAudio: "speech/cz/nuzky.mp3",
    viAudio: "speech/vi/keo.mp3",
  },
  {
    cz: "Suché",
    en: "Dry",
    vi: "Khô",
    czPron: "SU-ché",
    viPron: "kho",
    czAudio: "speech/cz/suche.mp3",
    viAudio: "speech/vi/kho.mp3",
  },
  {
    cz: "Mokré",
    en: "Wet",
    vi: "Ướt",
    czPron: "MO-kré",
    viPron: "uot",
    czAudio: "speech/cz/mokre.mp3",
    viAudio: "speech/vi/uot.mp3",
  },
  {
    cz: "Voda 💧",
    en: "Water",
    vi: "Nước",
    czPron: "VO-da",
    viPron: "nuok",
    czAudio: "speech/cz/voda.mp3",
    viAudio: "speech/vi/nuoc.mp3",
  },
  {
    section: "🎨 BARVY A ČAS",
    cz: "Barva",
    en: "Color",
    vi: "Màu sắc",
    czPron: "BAR-va",
    viPron: "mau sak",
    czAudio: "speech/cz/barva.mp3",
    viAudio: "speech/vi/mau-sac.mp3",
    czHint: "Mňau sáček; pastelky se rozsypou.",
    viHint: "Bar va; on the bar and my friend",
  },
  {
    cz: "Červená 🔴",
    en: "Red",
    vi: "Đỏ",
    czPron: "ČER-ve-ná",
    viPron: "do",
    czAudio: "speech/cz/cervena.mp3",
    viAudio: "speech/vi/djo.mp3",
  },
  {
    cz: "Růžová 🌸",
    en: "Pink",
    vi: "Hồng",
    czPron: "RŮ-žo-vá",
    viPron: "hong",
    czAudio: "speech/cz/ruzova.mp3",
    viAudio: "speech/vi/hong.mp3",
  },
  {
    cz: "Černá ⚫",
    en: "Black",
    vi: "Đen",
    czPron: "ČER-ná",
    viPron: "den",
    czAudio: "speech/cz/cerna.mp3",
    viAudio: "speech/vi/djen.mp3",
  },
  {
    cz: "Bílá ⚪",
    en: "White",
    vi: "Trắng",
    czPron: "BÍ-lá",
    viPron: "čang",
    czAudio: "speech/cz/bila.mp3",
    viAudio: "speech/vi/trang.mp3",
  },
  {
    cz: "Dnes 📅",
    en: "Today",
    vi: "Hôm nay",
    czPron: "DNES",
    viPron: "hom naj",
    viAudio: "speech/vi/hom-nay.mp3",
  },
  {
    cz: "Zítra ⏭️",
    en: "Tomorrow",
    vi: "Ngày mai",
    czPron: "ZÍ-tra",
    viPron: "ngaj maj",
    czAudio: "speech/cz/zitra.mp3",
    viAudio: "speech/vi/ngay-mai.mp3",
  },
  {
    section: "PENÍZE A PLATBA",
    cz: "Cena / Kolik to stojí? 💵",
    en: "Price / How much does it cost?",
    vi: "Giá bao nhiêu?",
    czPron: "CE-na / KO-lik to STO-jí?",
    viPron: "za bao nju",
    czAudio: ["speech/cz/cena.mp3", "speech/cz/kolik-to-stoji.mp3"],
    viAudio: ["speech/vi/gia.mp3", "speech/vi/bao-nhieu-tien.mp3"],
  },
  {
    cz: "Můžete platit.",
    en: "You can pay.",
    vi: "Bạn có thể thanh toán.",
    czPron: "MŮ-že-te PLA-tit",
    viPron: "ban ko tche tan toan",
    czAudio: "speech/cz/muzete-platit.mp3",
    viAudio: "speech/vi/ban-co-the-thanh-toan.mp3",
  },
  {
    cz: "Hotově 💶",
    en: "Cash",
    vi: "Tiền mặt",
    czPron: "HO-to-vě",
    viPron: "tjen mat",
    czAudio: "speech/cz/hotove.mp3",
    viAudio: "speech/vi/tien-mat.mp3",
  },
  {
    cz: "Kartou 💳",
    en: "By card",
    vi: "Bằng thẻ",
    czPron: "KAR-tou",
    viPron: "bang te",
    czAudio: "speech/cz/kartou.mp3",
    viAudio: "speech/vi/the.mp3",
  },
  {
    cz: "Perfektní ✨",
    en: "Perfect",
    vi: "Hoàn hảo",
    czPron: "PER-fek-tní",
    viPron: "hoan hao",
    czAudio: "speech/cz/perfektni.mp3",
    viAudio: "speech/vi/hoan-hao.mp3",
  },
  {
    cz: "Moment ⏱️",
    en: "Moment",
    vi: "Khoảnh khắc",
    czPron: "MO-ment",
    viPron: "khoanh khak",
    czAudio: "speech/cz/moment.mp3",
    viAudio: "speech/vi/mot-chut.mp3",
  },
  {
    cz: "Kafe ☕",
    en: "Coffee",
    vi: "Cà phê",
    czPron: "KA-fe",
    viPron: "ka fe",
    czAudio: "speech/cz/kafe.mp3",
    viAudio: "speech/vi/ca-phe.mp3",
  },
  {
    cz: "Klient (muž) / Klientka (žena)",
    en: "Client",
    vi: "Khách hàng",
    czPron: "KLI-ent / KLI-ent-ka",
    viPron: "khak hang",
    czAudio: ["speech/cz/klient.mp3", "speech/cz/klientka.mp3"],
    viAudio: ["speech/vi/khach-hang.mp3", "speech/vi/khach-hang-nu.mp3"],
  },
  {
    cz: "Salon",
    en: "Salon",
    vi: "Tiệm / Thẩm mỹ viện",
    czPron: "SA-lon",
    viPron: "tiem",
    czAudio: "speech/cz/salon.mp3",
    viAudio: "speech/vi/tiem.mp3",
  },
  {
    cz: "Design 🎨",
    en: "Design",
    vi: "Thiết kế",
    czPron: "DE-zajn",
    viPron: "thjet ke",
    czAudio: "speech/cz/design.mp3",
    viAudio: "speech/vi/thiet-ke.mp3",
  },
  {
    cz: "Problém ⚠️",
    en: "Problem",
    vi: "Vấn đề",
    czPron: "PRO-blém",
    viPron: "van de",
    czAudio: "speech/cz/problem.mp3",
    viAudio: "speech/vi/van-dje.mp3",
  },
  {
    cz: "Detail 🔍",
    en: "Detail",
    vi: "Chi tiết",
    czPron: "DE-tajl",
    viPron: "či tiet",
    viAudio: "speech/vi/chi-tiet.mp3",
  },
  {
    cz: "Materiál",
    en: "Material",
    vi: "Vật liệu",
    czPron: "MA-te-ri-ál",
    viPron: "vat lijeu",
    czAudio: "speech/cz/material.mp3",
    viAudio: "speech/vi/vat-lieu.mp3",
  },
  {
    cz: "Informace ℹ️",
    en: "Information",
    vi: "Thông tin",
    czPron: "IN-for-ma-ce",
    viPron: "thong tin",
    czAudio: "speech/cz/informace.mp3",
    viAudio: "speech/vi/thong-tin.mp3",
  },
  {
    cz: "Super 😄",
    en: "Super",
    vi: "Tuyệt vời",
    czPron: "SU-per",
    viPron: "tujet voj",
    czAudio: "speech/cz/super.mp3",
    viAudio: "speech/vi/tuyet-voi.mp3",
  },
  {
    cz: "Akryl",
    en: "Acrylic",
    vi: "Acrylic",
    czPron: "A-kryl",
    viPron: "ak-ril",
    czAudio: "speech/cz/akryl.mp3",
    viAudio: "speech/vi/acrylic.mp3",
  },
  {
    cz: "Gel",
    en: "Gel",
    vi: "Gel",
    czPron: "GEL",
    viPron: "zel",
    czAudio: "speech/cz/gel.mp3",
    viAudio: "speech/vi/gel.mp3",
  },
  {
    section: "ZÁKLADNÍ SLOVESA A ZÁJMENA",
    cz: "já",
    en: "I",
    vi: "tôi",
    czPron: "JÁ",
    viPron: "toj",
    czAudio: "speech/cz/ja.mp3",
    viAudio: "speech/vi/toi.mp3",
  },
  {
    cz: "ty",
    en: "you (singular)",
    vi: "bạn",
    czPron: "TI",
    viPron: "ban",
    czAudio: "speech/cz/ty.mp3",
  },
  {
    cz: "on",
    en: "he",
    vi: "anh ấy / ông ấy",
    czPron: "ON",
    viPron: "anh ej / ong ej",
    czAudio: "speech/cz/on.mp3",
    viAudio: ["speech/vi/anh-ay.mp3", "speech/vi/ong-ay.mp3"],
  },
  {
    cz: "ona",
    en: "she",
    vi: "cô ấy / bà ấy",
    czPron: "O-na",
    viPron: "ko ej / ba ej",
    czAudio: "speech/cz/ona.mp3",
    viAudio: ["speech/vi/co-ay.mp3", "speech/vi/ba-ay.mp3"],
  },
  {
    cz: "my",
    en: "we",
    vi: "chúng tôi",
    czPron: "MI",
    viPron: "čung toj",
    czAudio: "speech/cz/my.mp3",
    viAudio: "speech/vi/chung-toi.mp3",
  },
  {
    cz: "vy",
    en: "you (plural)",
    vi: "các bạn",
    czPron: "VI",
    viPron: "kak ban",
    czAudio: "speech/cz/vy.mp3",
    viAudio: "speech/vi/cac-ban.mp3",
  },
  {
    cz: "ano",
    en: "yes",
    vi: "vâng / có",
    czPron: "A-no",
    viPron: "vang / ko",
    czAudio: "speech/cz/ano.mp3",
    viAudio: ["speech/vi/vang.mp3", "speech/vi/co.mp3"],
  },
  {
    cz: "ne",
    en: "no",
    vi: "không",
    czPron: "NE",
    viPron: "kong",
    czAudio: "speech/cz/ne.mp3",
  },
  {
    cz: "špatný",
    en: "bad",
    vi: "xấu",
    czPron: "ŠPAT-ný",
    viPron: "sau",
    czAudio: "speech/cz/spatny.mp3",
    viAudio: "speech/vi/xau.mp3",
  },
  {
    cz: "mít",
    en: "to have",
    vi: "có",
    czPron: "MÍT",
    viPron: "ko",
    czAudio: "speech/cz/mit.mp3",
    viAudio: "speech/vi/co.mp3",
  },
  {
    cz: "být",
    en: "to be",
    vi: "là",
    czPron: "BÍT",
    viPron: "la",
    czAudio: "speech/cz/byt.mp3",
    viAudio: "speech/vi/la.mp3",
  },
  {
    cz: "dělat",
    en: "to do",
    vi: "làm",
    czPron: "DĚ-lat",
    viPron: "lam",
    czAudio: "speech/cz/delat.mp3",
  },
  {
    cz: "jít",
    en: "to go",
    vi: "đi",
    czPron: "JÍT",
    viPron: "dji",
    czAudio: "speech/cz/jit.mp3",
    viAudio: "speech/vi/dji.mp3",
  },
  {
    cz: "chtít",
    en: "to want",
    vi: "muốn",
    czPron: "CHTÍT",
    viPron: "muon",
    czAudio: "speech/cz/chtit.mp3",
    viAudio: "speech/vi/muon.mp3",
  },
  {
    cz: "moci",
    en: "can / to be able",
    vi: "có thể",
    czPron: "MO-ci",
    viPron: "ko te",
    czAudio: "speech/cz/moci.mp3",
  },
  {
    cz: "potřebovat",
    en: "to need",
    vi: "cần",
    czPron: "PO-tře-bo-vat",
    viPron: "kan",
    czAudio: "speech/cz/potrebovat.mp3",
    viAudio: "speech/vi/can.mp3",
  },
  {
    cz: "tam",
    en: "there",
    vi: "ở đó",
    czPron: "TAM",
    viPron: "o djo",
    czAudio: "speech/cz/tam.mp3",
    viAudio: "speech/vi/o-djo.mp3",
  },
  {
    cz: "teď",
    en: "now",
    vi: "bây giờ",
    czPron: "TEĎ",
    viPron: "bej zo",
    czAudio: "speech/cz/ted.mp3",
    viAudio: "speech/vi/bay-gio.mp3",
  },
  {
    cz: "čas",
    en: "time",
    vi: "thời gian",
    czPron: "ČAS",
    viPron: "toj zan",
    czAudio: "speech/cz/cas.mp3",
    viAudio: "speech/vi/thoi-gian.mp3",
  },
  {
    cz: "peníze",
    en: "money",
    vi: "tiền",
    czPron: "PE-ní-ze",
    viPron: "tien",
    czAudio: "speech/cz/penize.mp3",
  },
  {
    cz: "práce",
    en: "work",
    vi: "công việc",
    czPron: "PRÁ-ce",
    viPron: "kong viek",
    czAudio: "speech/cz/prace.mp3",
    viAudio: "speech/vi/cong-viec.mp3",
  },
  {
    cz: "dobře",
    en: "well / good",
    vi: "tốt",
    czPron: "DO-bře",
    viPron: "tot",
    czAudio: "speech/cz/dobre.mp3",
    viAudio: "speech/vi/tot.mp3",
  },
  {
    cz: "špatně",
    en: "badly",
    vi: "không tốt",
    czPron: "ŠPAT-ňe",
    viPron: "kong tot",
    czAudio: "speech/cz/spatne.mp3",
  },
  {
    cz: "prsty",
    en: "fingers",
    vi: "ngón tay",
    czPron: "PRS-ty",
    viPron: "ngon taj",
    czAudio: "speech/cz/prsty.mp3",
    viAudio: "speech/vi/ngon-tay.mp3",
  },
  {
    cz: "kůžička",
    en: "cuticle",
    vi: "da quanh móng",
    czPron: "KŮ-žič-ka",
    viPron: "za kuanh mong",
    czAudio: "speech/cz/kuzicka.mp3",
  },
  {
    cz: "délka",
    en: "length",
    vi: "độ dài",
    czPron: "DÉL-ka",
    viPron: "do zaj",
    czAudio: "speech/cz/delka.mp3",
    viAudio: "speech/vi/djo-dai.mp3",
  },
  {
    cz: "krátké",
    en: "short",
    vi: "ngắn",
    czPron: "KRÁT-ké",
    viPron: "ngan",
    czAudio: "speech/cz/kratke.mp3",
    viAudio: "speech/vi/ngan.mp3",
  },
  {
    cz: "dlouhé",
    en: "long",
    vi: "dài",
    czPron: "DLOU-hé",
    viPron: "zaj",
    czAudio: "speech/cz/dlouhe.mp3",
    viAudio: "speech/vi/dai.mp3",
  },
  {
    cz: "lampa",
    en: "lamp",
    vi: "đèn",
    czPron: "LAM-pa",
    viPron: "djen",
    czAudio: "speech/cz/lampa.mp3",
    viAudio: "speech/vi/djen.mp3",
  },
  {
    cz: "chvilku",
    en: "a moment",
    vi: "một chút",
    czPron: "CHVIL-ku",
    viPron: "mot čut",
    czAudio: "speech/cz/chvilku.mp3",
    viAudio: "speech/vi/mot-chut.mp3",
  },
  {
    cz: "opravit",
    en: "to fix",
    vi: "sửa",
    czPron: "O-pra-vit",
    viPron: "sua",
    czAudio: "speech/cz/opravit.mp3",
    viAudio: "speech/vi/sua.mp3",
  },
  {
    cz: "zkrátit",
    en: "to shorten",
    vi: "cắt ngắn",
    czPron: "ZKRÁ-tit",
    viPron: "kat ngan",
    czAudio: "speech/cz/zkratit.mp3",
    viAudio: "speech/vi/cat-ngan.mp3",
  },
  {
    cz: "prodloužit",
    en: "to lengthen",
    vi: "làm dài",
    czPron: "PRO-dlou-žit",
    viPron: "lam zaj",
    czAudio: "speech/cz/prodlouzit.mp3",
    viAudio: "speech/vi/lam-dai.mp3",
  },
  {
    cz: "změna",
    en: "change",
    vi: "thay đổi",
    czPron: "ZMĚ-na",
    viPron: "thaj doj",
    czAudio: "speech/cz/zmena.mp3",
    viAudio: "speech/vi/thay-djoi.mp3",
  },
  {
    cz: "líbí se",
    en: "to like",
    vi: "thích",
    czPron: "LÍ-bí se",
    viPron: "thik",
    czAudio: "speech/cz/libi-se.mp3",
    viAudio: "speech/vi/thich.mp3",
  },
  {
    cz: "nelíbí se",
    en: "to not like",
    vi: "không thích",
    czPron: "NE-lí-bí se",
    viPron: "kong thik",
    czAudio: "speech/cz/nelibi-se.mp3",
  },
  {
    cz: "levné",
    en: "cheap",
    vi: "rẻ",
    czPron: "LEV-né",
    viPron: "ze",
    czAudio: "speech/cz/levne.mp3",
    viAudio: "speech/vi/re.mp3",
  },
  {
    cz: "drahé",
    en: "expensive",
    vi: "đắt",
    czPron: "DRA-hé",
    viPron: "dat",
    czAudio: "speech/cz/drahe.mp3",
    viAudio: "speech/vi/djat.mp3",
  },
  {
    cz: "čisté",
    en: "clean",
    vi: "sạch",
    czPron: "ČIS-té",
    viPron: "sach",
    czAudio: "speech/cz/ciste.mp3",
    viAudio: "speech/vi/sach.mp3",
  },
  {
    cz: "dezinfekce",
    en: "disinfection",
    vi: "khử trùng",
    czPron: "DE-zin-fek-ce",
    viPron: "khu čung",
    czAudio: "speech/cz/dezinfekce.mp3",
    viAudio: "speech/vi/khu-trung.mp3",
  },
  {
    cz: "zákaznice",
    en: "customer (female)",
    vi: "khách hàng",
    czPron: "ZÁ-kaz-ni-ce",
    viPron: "kach hang",
    czAudio: "speech/cz/zakaznice.mp3",
    viAudio: "speech/vi/khach-hang.mp3",
  },
  {
    cz: "Je to v pořádku",
    en: "It's okay",
    vi: "Không sao",
    czPron: "JE to v po-ŘÁD-ku",
    viPron: "chom sao",
    czAudio: "speech/cz/je-to-v-poradku.mp3",
    viAudio: "speech/vi/khong-sao.mp3",
  },
  {
    cz: "Ano, rozumím",
    en: "Yes, I understand",
    vi: "Vâng, tôi hiểu",
    czPron: "A-no ro-ZU-mím",
    viPron: "vang toj hieu",
    czAudio: "speech/cz/ano-rozumim.mp3",
    viAudio: "speech/vi/vang-toi-hieu.mp3",
  },
  {
    cz: "Ne, nerozumím",
    en: "No, I don't understand",
    vi: "Không, tôi không hiểu",
    czPron: "NE ne-ro-ZU-mím",
    viPron: "chom toj chom hieu",
    czAudio: "speech/cz/ne-nerozumim.mp3",
    viAudio: "speech/vi/khong-toi-khong-hieu.mp3",
  },
  {
    cz: "Můžete to zopakovat?",
    en: "Can you repeat it?",
    vi: "Bạn có thể nhắc lại không?",
    czPron: "MŮ-že-te to zo-pa-KO-vat",
    viPron: "ban ko tche ňak laj chom",
    czAudio: "speech/cz/muzete-to-zopakovat.mp3",
    viAudio: "speech/vi/ban-co-the-nhac-lai-khong.mp3",
  },
  {
    cz: "Mluvte prosím pomalu",
    en: "Please speak slowly",
    vi: "Làm ơn nói chậm",
    czPron: "MLUV-te PRO-sím po-MA-lu",
    viPron: "lam ən noj čam",
    czAudio: "speech/cz/mluvte-prosim-pomalu.mp3",
    viAudio: "speech/vi/lam-on-noi-cham.mp3",
  },
  {
    cz: "Počkejte prosím chvilku",
    en: "Please wait a moment",
    vi: "Làm ơn chờ một chút",
    czPron: "POČ-kej-te chvil-ku",
    viPron: "lam ən čo mot čut",
    czAudio: "speech/cz/pockejte-prosim-chvilku.mp3",
    viAudio: "speech/vi/lam-on-cho-mot-chut.mp3",
  },
  {
    cz: "Teď nemám čas",
    en: "I don't have time now",
    vi: "Bây giờ tôi không có thời gian",
    czPron: "TEĎ ne-mám čas",
    viPron: "baj zə toj chom ko thoj zan",
    czAudio: "speech/cz/ted-nemam-cas.mp3",
    viAudio: "speech/vi/bay-gio-toi-khong-co-thoi-gian.mp3",
  },
  {
    cz: "Teď je to možné",
    en: "It's possible now",
    vi: "Bây giờ được",
    czPron: "TEĎ je to MOŽ-né",
    viPron: "baj zə duk",
    czAudio: "speech/cz/ted-je-to-mozne.mp3",
    viAudio: "speech/vi/bay-gio-djuoc.mp3",
  },
  {
    cz: "Chci se zeptat",
    en: "I want to ask",
    vi: "Tôi muốn hỏi",
    czPron: "CHCI se ZEP-tat",
    viPron: "toj muon hoj",
    czAudio: "speech/cz/chci-se-zeptat.mp3",
    viAudio: "speech/vi/toi-muon-hoi.mp3",
  },
  {
    cz: "Kolik to stojí?",
    en: "How much is it?",
    vi: "Bao nhiêu tiền?",
    czPron: "KO-lik to STO-jí",
    viPron: "bao ňjeu tien",
    czAudio: "speech/cz/kolik-to-stoji.mp3",
    viAudio: "speech/vi/bao-nhieu-tien.mp3",
  },
  {
    cz: "Kde to je?",
    en: "Where is it?",
    vi: "Ở đâu?",
    czPron: "GDE to je",
    viPron: "ə dau",
    czAudio: "speech/cz/kde-to-je.mp3",
    viAudio: "speech/vi/o-djau.mp3",
  },
  {
    cz: "Kdy to bude?",
    en: "When will it be?",
    vi: "Khi nào?",
    czPron: "GDI to BU-de",
    viPron: "chi nao",
    czAudio: "speech/cz/kdy-to-bude.mp3",
    viAudio: "speech/vi/khi-nao.mp3",
  },
  {
    cz: "Dnes to stačí",
    en: "That's enough for today",
    vi: "Hôm nay như vậy đủ rồi",
    czPron: "DNES to STA-čí",
    viPron: "hom naj ňu vaj du zoj",
    czAudio: "speech/cz/dnes-to-staci.mp3",
    viAudio: "speech/vi/hom-nay-nhu-vay-dju-roi.mp3",
  },
  {
    cz: "Zítra to bude lepší",
    en: "Tomorrow will be better",
    vi: "Ngày mai sẽ tốt hơn",
    czPron: "ZÍT-ra to BU-de LEP-ší",
    viPron: "ngaj maj se tot hon",
    czAudio: "speech/cz/zitra-to-bude-lepsi.mp3",
    viAudio: "speech/vi/ngay-mai-se-tot-hon.mp3",
  },
  {
    cz: "To je dobré",
    en: "That's good",
    vi: "Như vậy tốt",
    czPron: "TO je DO-bré",
    viPron: "ňu vaj tot",
    czAudio: "speech/cz/to-je-dobre.mp3",
    viAudio: "speech/vi/nhu-vay-tot.mp3",
  },
  {
    cz: "To není dobré",
    en: "That's not good",
    vi: "Không tốt",
    czPron: "TO NE-ní DO-bré",
    viPron: "chom tot",
    czAudio: "speech/cz/to-neni-dobre.mp3",
    viAudio: "speech/vi/khong-tot.mp3",
  },
  {
    cz: "Můžete se posadit",
    en: "You can sit down",
    vi: "Bạn có thể ngồi",
    czPron: "MŮ-že-te se po-SA-dit",
    viPron: "ban ko tche ngoj",
    czAudio: "speech/cz/muzete-se-posadit.mp3",
    viAudio: "speech/vi/ban-co-the-ngoi.mp3",
  },
  {
    cz: "Začneme teď",
    en: "We will start now",
    vi: "Bắt đầu bây giờ",
    czPron: "ZAČ-ne-me teď",
    viPron: "bat dau baj zə",
    czAudio: "speech/cz/zacneme-ted.mp3",
    viAudio: "speech/vi/bat-djau-bay-gio.mp3",
  },
  {
    cz: "Už je to hotové",
    en: "It's finished",
    vi: "Xong rồi",
    czPron: "UŽ je to HO-to-vé",
    viPron: "song zoj",
    czAudio: "speech/cz/uz-je-to-hotove.mp3",
    viAudio: "speech/vi/xong-roi.mp3",
  },
  {
    cz: "Počkejte prosím chvilku",
    en: "Please wait a moment",
    vi: "Làm ơn chờ một chút",
    czPron: "POČ-kej-te chvil-ku",
    viPron: "lam ən čo mot čut",
    czAudio: "speech/cz/pockejte-prosim-chvilku.mp3",
    viAudio: "speech/vi/lam-on-cho-mot-chut.mp3",
  },
  {
    cz: "Nebude to bolet",
    en: "It won't hurt",
    vi: "Không đau đâu",
    czPron: "NE-bu-de to BO-let",
    viPron: "chom zau dau",
    czAudio: "speech/cz/nebude-to-bolet.mp3",
    viAudio: "speech/vi/khong-djau-djau.mp3",
  },
  {
    cz: "Líbí se vám to?",
    en: "Do you like it?",
    vi: "Bạn có thích không?",
    czPron: "LÍ-bí se vám to",
    viPron: "ban ko thik chom",
    czAudio: "speech/cz/libi-se-vam-to.mp3",
    viAudio: "speech/vi/ban-co-thich-khong.mp3",
  },
  {
    cz: "Je to hezké?",
    en: "Is it nice?",
    vi: "Đẹp không?",
    czPron: "JE to HEZ-ké",
    viPron: "dep chom",
    czAudio: "speech/cz/je-to-hezke.mp3",
    viAudio: "speech/vi/djep-khong.mp3",
  },
  {
    cz: "Chcete jinou barvu?",
    en: "Do you want another color?",
    vi: "Bạn muốn màu khác không?",
    czPron: "CHCE-te JI-nou BAR-vu",
    viPron: "ban muon mau chac chom",
    czAudio: "speech/cz/chcete-jinou-barvu.mp3",
    viAudio: "speech/vi/ban-muon-mau-khac-khong.mp3",
  },
  {
    cz: "Krátké nebo dlouhé?",
    en: "Shorter or longer?",
    vi: "Ngắn hay dài?",
    czPron: "KRÁT-ké ne-bo DLOU-hé?",
    viPron: "ngan haj zaj",
    czAudio: "speech/cz/kratke-nebo-dlouhe.mp3",
    viAudio: "speech/vi/ngan-hay-dai.mp3",
  },
  {
    cz: "Uděláme to kratší",
    en: "We will make it shorter",
    vi: "Làm ngắn lại",
    czPron: "U-DĚ-lá-me to KRAT-ší",
    viPron: "lam ngan laj",
    czAudio: "speech/cz/udelame-to-kratsi.mp3",
    viAudio: "speech/vi/lam-ngan-lai.mp3",
  },
  {
    cz: "Uděláme to delší",
    en: "We will make it longer",
    vi: "Làm dài hơn",
    czPron: "U-DĚ-lá-me to DEL-ší",
    viPron: "lam zaj hon",
    czAudio: "speech/cz/udelame-to-delsi.mp3",
    viAudio: "speech/vi/lam-dai-hon.mp3",
  },
  {
    cz: "Necháme to takto",
    en: "We'll leave it like this",
    vi: "Giữ như vậy",
    czPron: "NE-CHÁ-me to TAK-to",
    viPron: "zu ňu vaj",
    czAudio: "speech/cz/nechame-to-takto.mp3",
    viAudio: "speech/vi/giu-nhu-vay.mp3",
  },
  {
    cz: "Trochu to upravím",
    en: "I'll adjust it a bit",
    vi: "Sửa một chút",
    czPron: "TRO-chu to U-PRA-vím",
    viPron: "sua mot čut",
    czAudio: "speech/cz/trochu-to-upravim.mp3",
    viAudio: "speech/vi/sua-mot-chut.mp3",
  },
  {
    cz: "Musíme to opravit",
    en: "We need to fix it",
    vi: "Cần sửa lại",
    czPron: "MU-sí-me to O-PRA-vit",
    viPron: "kan sua laj",
    czAudio: "speech/cz/musime-to-opravit.mp3",
    viAudio: "speech/vi/can-sua-lai.mp3",
  },
  {
    cz: "Cena je tady",
    en: "The price is here",
    vi: "Giá là thế này",
    czPron: "CE-na je TA-dy",
    viPron: "za la the naj",
    czAudio: "speech/cz/cena-je-tady.mp3",
    viAudio: "speech/vi/gia-la-the-nay.mp3",
  },
  {
    cz: "Je to trochu drahé",
    en: "It's a bit expensive",
    vi: "Hơi đắt",
    czPron: "JE to TRO-chu DRA-hé",
    viPron: "hoj dat",
    czAudio: "speech/cz/je-to-trochu-drahe.mp3",
    viAudio: "speech/vi/hoi-djat.mp3",
  },
  {
    cz: "Je to levnější",
    en: "It's cheaper",
    vi: "Rẻ hơn",
    czPron: "JE to LEV-něj-ší",
    viPron: "re hon",
    czAudio: "speech/cz/je-to-levnejsi.mp3",
    viAudio: "speech/vi/re-hon.mp3",
  },
  {
    cz: "Bude to trvat chvíli",
    en: "It will take a while",
    vi: "Sẽ mất một chút thời gian",
    czPron: "BU-de to TR-vat CHVÍ-li",
    viPron: "se mat mot čut thoj zan",
    czAudio: "speech/cz/bude-to-trvat-chvili.mp3",
    viAudio: "speech/vi/se-mat-mot-chut-thoi-gian.mp3",
  },
  {
    cz: "Děkuji, nashledanou",
    en: "Thank you, goodbye",
    vi: "Cảm ơn, hẹn gặp lại",
    czPron: "DĚ-ku-ji na-SCHLE-da-nou",
    viPron: "kam ən hen gap laj",
    czAudio: "speech/cz/dekuji-nashledanou.mp3",
    viAudio: "speech/vi/cam-on-hen-gap-lai.mp3",
  },
  {
    cz: "Přijít",
    en: "To come",
    vi: "Đến",
    czPron: "PŘI-jít",
    viPron: "den",
  },
  {
    cz: "Vidět",
    en: "To see",
    vi: "Thấy",
    czPron: "VI-dět",
    viPron: "thaj",
  },
  {
    cz: "Slyšet",
    en: "To hear",
    vi: "Nghe",
    czPron: "SLY-šet",
    viPron: "nge",
  },
  {
    cz: "Říct",
    en: "To say",
    vi: "Nói",
    czPron: "Říct",
    viPron: "noj",
  },
  {
    cz: "Mluvit",
    en: "To speak",
    vi: "Nói chuyện",
    czPron: "MLU-vit",
    viPron: "noj čuen",
  },
  {
    cz: "Rozumět",
    en: "To understand",
    vi: "Hiểu",
    czPron: "RO-zu-mět",
    viPron: "hieu",
  },
  {
    cz: "Nevědět",
    en: "Not to know",
    vi: "Không biết",
    czPron: "NE-vě-dět",
    viPron: "chom bjet",
  },
  {
    cz: "Vědět",
    en: "To know",
    vi: "Biết",
    czPron: "VĚ-dět",
    viPron: "bjet",
  },
  {
    cz: "Dobrý",
    en: "Good",
    vi: "Tốt",
    czPron: "DO-brý",
    viPron: "tot",
  },
  {
    cz: "Velký",
    en: "Big",
    vi: "Lớn",
    czPron: "VEL-ký",
    viPron: "lon",
  },
  {
    cz: "Malý",
    en: "Small",
    vi: "Nhỏ",
    czPron: "MA-lý",
    viPron: "ňo",
  },
  {
    cz: "Nový",
    en: "New",
    vi: "Mới",
    czPron: "NO-vý",
    viPron: "moj",
  },
  {
    cz: "Starý",
    en: "Old",
    vi: "Cũ",
    czPron: "STA-rý",
    viPron: "ku",
  },
  {
    cz: "Včera",
    en: "Yesterday",
    vi: "Hôm qua",
    czPron: "VČE-ra",
    viPron: "hom kua",
  },
  {
    cz: "Levný",
    en: "Cheap",
    vi: "Rẻ",
    czPron: "LEV-ný",
    viPron: "re",
  },
  {
    cz: "Drahý",
    en: "Expensive",
    vi: "Đắt",
    czPron: "DRA-hý",
    viPron: "dat",
  },
  {
    cz: "Možnost",
    en: "Possibility",
    vi: "Có thể",
    czPron: "MOŽ-nost",
    viPron: "ko tche",
  },
  {
    cz: "Pomoc",
    en: "Help",
    vi: "Giúp",
    czPron: "PO-moc",
    viPron: "zup",
  },
  {
    cz: "Čekat",
    en: "To wait",
    vi: "Chờ",
    czPron: "ČE-kat",
    viPron: "čo",
  },
  {
    cz: "Najít",
    en: "To find",
    vi: "Tìm",
    czPron: "NA-jít",
    viPron: "tim",
  },
  {
    cz: "Ztratit",
    en: "To lose",
    vi: "Mất",
    czPron: "ZTRA-tit",
    viPron: "mat",
  },
  {
    cz: "Začít",
    en: "To start",
    vi: "Bắt đầu",
    czPron: "ZA-čít",
    viPron: "bat dau",
  },
  {
    cz: "Skončit",
    en: "To finish",
    vi: "Kết thúc",
    czPron: "SKON-čit",
    viPron: "ket thuk",
  },
  {
    cz: "Člověk",
    en: "Person",
    vi: "Người",
    czPron: "ČLO-věk",
    viPron: "nguoj",
  },
  {
    cz: "Lidé",
    en: "People",
    vi: "Mọi người",
    czPron: "LI-dé",
    viPron: "moj nguoj",
  },
  {
    cz: "Věc",
    en: "Thing",
    vi: "Vật",
    czPron: "Věc",
    viPron: "vat",
  },
  {
    cz: "Místo",
    en: "Place",
    vi: "Nơi",
    czPron: "MÍ-sto",
    viPron: "noj",
  },
  {
    cz: "Cesta",
    en: "Way / road",
    vi: "Đường",
    czPron: "CES-ta",
    viPron: "duong",
  },
  {
    cz: "Otázka",
    en: "Question",
    vi: "Câu hỏi",
    czPron: "O-TÁZ-ka",
    viPron: "kau hoj",
  },
  {
    cz: "Odpověď",
    en: "Answer",
    vi: "Trả lời",
    czPron: "OD-po-věď",
    viPron: "ča loj",
  },
  {
    cz: "Plán",
    en: "Plan",
    vi: "Kế hoạch",
    czPron: "Plán",
    viPron: "ke hoak",
  },
  {
    cz: "Situace",
    en: "Situation",
    vi: "Tình huống",
    czPron: "SI-tu-a-ce",
    viPron: "tin huong",
  },
  {
    cz: "Důvod",
    en: "Reason",
    vi: "Lý do",
    czPron: "DŮ-vod",
    viPron: "li zo",
  },
  {
    cz: "Pomalu",
    en: "Slowly",
    vi: "Chậm",
    czPron: "PO-ma-lu",
    viPron: "čam",
  },
  {
    cz: "Rychle",
    en: "Fast",
    vi: "Nhanh",
    czPron: "RYCH-le",
    viPron: "ňanh",
  },
  {
    cz: "Vždy",
    en: "Always",
    vi: "Luôn luôn",
    czPron: "VŽDY",
    viPron: "luon luon",
  },
  {
    cz: "Nikdy",
    en: "Never",
    vi: "Không bao giờ",
    czPron: "NIK-dy",
    viPron: "chom bao zə",
  },
  {
    cz: "Někdy",
    en: "Sometimes",
    vi: "Đôi khi",
    czPron: "NĚK-dy",
    viPron: "doj chi",
  },
  {
    cz: "Proto",
    en: "Therefore",
    vi: "Vì vậy",
    czPron: "PRO-to",
    viPron: "vi zəj",
  },
  {
    cz: "Protože",
    en: "Because",
    vi: "Bởi vì",
    czPron: "PRO-to-že",
    viPron: "boj vi",
  },
  {
    cz: "Jestli",
    en: "If",
    vi: "Nếu",
    czPron: "JES-tli",
    viPron: "neu",
  },
  {
    cz: "Když",
    en: "When / if",
    vi: "Khi",
    czPron: "Když",
    viPron: "chi",
  },
  {
    cz: "Ale",
    en: "But",
    vi: "Nhưng",
    czPron: "A-le",
    viPron: "ňung",
  },
  {
    cz: "Nebo",
    en: "Or",
    vi: "Hoặc",
    czPron: "NE-bo",
    viPron: "huak",
  },
  {
    cz: "Také",
    en: "Also",
    vi: "Cũng",
    czPron: "TA-ké",
    viPron: "kung",
  },
  {
    cz: "Jen",
    en: "Only",
    vi: "Chỉ",
    czPron: "Jen",
    viPron: "či",
  },
  {
    cz: "Už",
    en: "Already",
    vi: "Đã",
    czPron: "Už",
    viPron: "da",
  },
  {
    cz: "Ještě",
    en: "Still",
    vi: "Vẫn",
    czPron: "JEŠ-tě",
    viPron: "van",
  },
  {
    cz: "Zase",
    en: "Again",
    vi: "Lại",
    czPron: "ZA-se",
    viPron: "laj",
  },
  {
    cz: "Hned",
    en: "Immediately",
    vi: "Ngay",
    czPron: "Hned",
    viPron: "ngaj",
  },
  {
    cz: "Brzy",
    en: "Soon",
    vi: "Sớm",
    czPron: "Brzy",
    viPron: "som",
  },
  {
    cz: "Pozdě",
    en: "Late",
    vi: "Muộn",
    czPron: "POZ-dě",
    viPron: "muon",
  },
  {
    cz: "Dlouho",
    en: "Long (time)",
    vi: "Lâu",
    czPron: "DLOU-ho",
    viPron: "lau",
  },
  {
    cz: "Krátce",
    en: "Briefly",
    vi: "Ngắn",
    czPron: "KRÁT-ce",
    viPron: "ngan",
  },
  {
    cz: "Hodně",
    en: "A lot",
    vi: "Nhiều",
    czPron: "HOD-ně",
    viPron: "ňieu",
  },
  {
    cz: "Málo",
    en: "Little",
    vi: "Ít",
    czPron: "MÁ-lo",
    viPron: "it",
  },
  {
    cz: "Všechno",
    en: "Everything",
    vi: "Mọi thứ",
    czPron: "VŠECH-no",
    viPron: "moj thu",
  },
  {
    cz: "Nic",
    en: "Nothing",
    vi: "Không có gì",
    czPron: "Nic",
    viPron: "chom ko zi",
  },
  {
    cz: "Něco",
    en: "Something",
    vi: "Cái gì đó",
    czPron: "NĚ-co",
    viPron: "kaj zi do",
  },
  {
    cz: "Někdo",
    en: "Someone",
    vi: "Ai đó",
    czPron: "NĚK-do",
    viPron: "aj do",
  },
  {
    cz: "Každý",
    en: "Everyone",
    vi: "Mỗi người",
    czPron: "KAŽ-dý",
    viPron: "moj nguoj",
  },
  {
    cz: "Jeden",
    en: "One",
    vi: "Một",
    czPron: "JE-den",
    viPron: "mot",
  },
  {
    cz: "Dva",
    en: "Two",
    vi: "Hai",
    czPron: "Dva",
    viPron: "haj",
  },
  {
    cz: "Více",
    en: "More",
    vi: "Hơn",
    czPron: "VÍ-ce",
    viPron: "hon",
  },
  {
    cz: "Méně",
    en: "Less",
    vi: "Ít hơn",
    czPron: "MÉ-ně",
    viPron: "it hon",
  },
  {
    cz: "Stejně",
    en: "Same",
    vi: "Giống",
    czPron: "STEJ-ně",
    viPron: "zong",
  },
  {
    cz: "Jinak",
    en: "Differently",
    vi: "Khác",
    czPron: "JI-nak",
    viPron: "chak",
  },
  {
    cz: "Správně",
    en: "Correctly",
    vi: "Đúng",
    czPron: "SPRÁV-ně",
    viPron: "dung",
  },
  {
    cz: "Snadno",
    en: "Easily",
    vi: "Dễ",
    czPron: "SNAD-no",
    viPron: "ze",
  },
  {
    cz: "Těžko",
    en: "Hard",
    vi: "Khó",
    czPron: "TĚŽ-ko",
    viPron: "cho",
  },
  {
    cz: "Rád",
    en: "Gladly / like",
    vi: "Thích",
    czPron: "Rád",
    viPron: "thich",
  },
  {
    cz: "Myslet",
    en: "To think",
    vi: "Nghĩ",
    czPron: "MY-slet",
    viPron: "ňi",
  },
  {
    cz: "Věřit",
    en: "To believe",
    vi: "Tin",
    czPron: "VĚ-řit",
    viPron: "tin",
  },
  {
    cz: "Doufat",
    en: "To hope",
    vi: "Hy vọng",
    czPron: "DOU-fat",
    viPron: "hi vong",
  },
  {
    cz: "Zkusit",
    en: "To try",
    vi: "Thử",
    czPron: "ZKU-sit",
    viPron: "thu",
  },
  {
    cz: "Rozhodnout",
    en: "To decide",
    vi: "Quyết định",
    czPron: "ROZ-hod-nout",
    viPron: "kvet din",
  },
  {
    cz: "Změnit",
    en: "To change",
    vi: "Thay đổi",
    czPron: "ZMĚ-nit",
    viPron: "thaj doj",
  },
  {
    cz: "Zůstat",
    en: "To stay",
    vi: "Ở lại",
    czPron: "ZŮ-stat",
    viPron: "ə laj",
  },
  {
    cz: "Vrátit",
    en: "To return",
    vi: "Quay lại",
    czPron: "VRÁ-tit",
    viPron: "kuaj laj",
  },
  {
    cz: "Vzít",
    en: "To take",
    vi: "Lấy",
    czPron: "Vzít",
    viPron: "lej",
  },
  {
    cz: "Dát",
    en: "To give",
    vi: "Cho",
    czPron: "Dát",
    viPron: "čo",
  },
  {
    cz: "Držet",
    en: "To hold",
    vi: "Giữ",
    czPron: "DR-žet",
    viPron: "zu",
  },
  {
    cz: "Nechat",
    en: "To let",
    vi: "Để",
    czPron: "NE-chat",
    viPron: "de",
  },
  {
    cz: "Patřit",
    en: "To belong",
    vi: "Thuộc",
    czPron: "PA-třit",
    viPron: "thuok",
  },
  {
    cz: "Platí",
    en: "It applies",
    vi: "Áp dụng",
    czPron: "PLA-tí",
    viPron: "ap zun",
  },
  {
    cz: "Zdát se",
    en: "To seem",
    vi: "Có vẻ",
    czPron: "ZDÁT se",
    viPron: "ko ve",
  },
  {
    cz: "Stačit",
    en: "To be enough",
    vi: "Đủ",
    czPron: "STA-čit",
    viPron: "du",
  },
  {
    cz: "Chybět",
    en: "To be missing",
    vi: "Thiếu",
    czPron: "CHY-bět",
    viPron: "thieu",
  },
  {
    cz: "Přesně",
    en: "Exactly",
    vi: "Chính xác",
    czPron: "PŘES-ně",
    viPron: "činh sak",
  },
  {
    cz: "Přibližně",
    en: "Approximately",
    vi: "Khoảng",
    czPron: "PŘI-bliž-ně",
    viPron: "chuoang",
  },
  {
    cz: "Opravdu",
    en: "Really",
    vi: "Thật sự",
    czPron: "O-PRA-vdu",
    viPron: "that su",
  },
  {
    cz: "Možná",
    en: "Maybe",
    vi: "Có lẽ",
    czPron: "MOŽ-ná",
    viPron: "ko le",
  }
];

