'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { createPortal } from 'react-dom';
import { useI18n } from '@/components/I18nProvider';
import type { WordCategory, WordList, WordListItem } from '@/features/lists/types';
import type { RepairAutogeneratedListPreview } from '@/features/lists/client/actions';
import { ConfirmModal } from '@/components/ConfirmModal';
import { copyTextToClipboard } from '@/lib/clipboard';
import { ShareVisibilityDialog } from '../ShareVisibilityDialog';
import { ForkIcon, ListBadges } from './ListMetadata';
import { useAutogeneratedListRepair } from './useAutogeneratedListRepair';

const ALL_WORDS_CATEGORY_ID = '__all_words__';

interface CategoryBrowserProps {
  list: WordList;
  categories: WordCategory[];
  itemsByCategory: Map<string, WordListItem[]>;
  languages?: { code: string; name: string }[];
  isOwner: boolean;
  isEditor: boolean;
  forkedFromListName?: string | null;
  triggerEditSignal?: number;
  onEditCategory: (categoryId: string, inputLang: 'known' | 'target') => void;
  onEditAllWords: () => void;
  onCreateCategory: (name: string) => Promise<string | null | void>;
  onUpdateList: (listId: string, data: Pick<WordList, 'name' | 'description' | 'isPublic'> & {
    isCommon?: boolean;
    isRecommended?: boolean;
    languageFrom?: string;
    languageTo?: string;
  }) => Promise<void>;
  onDismissForkNotice?: () => void;
  onRenameCategory: (categoryId: string, name: string) => Promise<void>;
  onReorderCategories: (orderedIds: string[]) => Promise<void>;
  onDeleteCategory: (categoryId: string) => Promise<void>;
  onFork?: (listId: string) => Promise<void>;
  onDeleteList?: (listId: string) => Promise<void>;
  onListUpdated?: (list: WordList) => void;
  onPreviewAutogeneratedRepair?: (listId: string) => Promise<RepairAutogeneratedListPreview>;
  onRepairAutogenerated?: (
    listId: string,
    preview?: RepairAutogeneratedListPreview,
    selectedRepairItemIds?: string[],
  ) => Promise<void>;
}

function RepairPreviewModal({
  list,
  preview,
  currentWordCount,
  currentCategoryCount,
  repairing,
  onConfirm,
  onCancel,
}: {
  list: WordList;
  preview: RepairAutogeneratedListPreview;
  currentWordCount: number;
  currentCategoryCount: number;
  repairing: boolean;
  onConfirm: (selectedRepairItemIds: string[]) => void;
  onCancel: () => void;
}) {
  const { t } = useI18n();
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'failed'>('idle');
  const [selectedIds, setSelectedIds] = useState<Set<string>>(
    () => new Set(preview.repairs.filter((repair) => repair.selectedByDefault).map((repair) => repair.currentItemId)),
  );
  const selectedCount = selectedIds.size;
  const unchangedPreview = preview.unchanged.slice(0, 20);
  const hasMoreUnchanged = preview.unchanged.length > unchangedPreview.length;

  function toggleRepair(itemId: string) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(itemId)) next.delete(itemId);
      else next.add(itemId);
      return next;
    });
  }

  function buildCopyText() {
    const selected = preview.repairs.filter((repair) => selectedIds.has(repair.currentItemId));
    const skipped = preview.repairs.filter((repair) => !selectedIds.has(repair.currentItemId));
    const lines = [
      `Repair preview for: ${list.name}`,
      `Language pair: ${list.languageFrom} -> ${list.languageTo}`,
      `Source: ${preview.seedKind || preview.provider}${preview.seedListId ? ` (${preview.seedListId})` : ''}`,
      `Current list: ${currentWordCount} words, ${currentCategoryCount} categories`,
      `Suggested repairs: ${preview.repairs.length}; selected: ${selected.length}; skipped: ${skipped.length}`,
      `Unchanged: ${preview.unchanged.length}; ignored generated suggestions: ${preview.ignoredSuggestionCount}`,
      '',
      'Please review whether the selected repairs are correct. Focus on whether the Thai source text and Chinese target text match each other, and flag any repairs that should not be applied.',
      '',
      'SELECTED REPAIRS',
      ...selected.flatMap((repair, index) => [
        `${index + 1}. ${repair.reason === 'known_side' ? 'source text' : 'translation'} | ${repair.currentItemId}`,
        `   current known: ${repair.textKnown}`,
        `   proposed known: ${repair.proposedTextKnown}`,
        `   current target: ${repair.currentTextTarget ?? ''}`,
        `   proposed target: ${repair.proposedTextTarget}`,
        `   category: ${repair.currentCategoryName}`,
      ]),
      '',
      'SKIPPED SUGGESTED REPAIRS',
      ...skipped.flatMap((repair, index) => [
        `${index + 1}. ${repair.reason === 'known_side' ? 'source text' : 'translation'} | ${repair.currentItemId}`,
        `   current known: ${repair.textKnown}`,
        `   proposed known: ${repair.proposedTextKnown}`,
        `   current target: ${repair.currentTextTarget ?? ''}`,
        `   proposed target: ${repair.proposedTextTarget}`,
        `   category: ${repair.currentCategoryName}`,
      ]),
      '',
      'UNCHANGED ITEMS',
      ...preview.unchanged.map((item, index) =>
        `${index + 1}. ${item.textKnown}\t${item.textTarget ?? ''}\t${item.categoryName}`,
      ),
    ];
    return lines.join('\n');
  }

  async function handleCopyPreview() {
    try {
      await copyTextToClipboard(buildCopyText());
      setCopyStatus('copied');
    } catch {
      setCopyStatus('failed');
    }
  }

  const modal = (
    <div
      className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 p-4"
      onClick={onCancel}
    >
      <div
        className="flex max-h-[88vh] w-full max-w-5xl flex-col rounded-2xl border border-border-subtle bg-background shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="border-b border-border-subtle p-5">
          <h2 className="text-base font-semibold text-text">
            {t('lists.repairPreviewTitle', { name: list.name })}
          </h2>
          <p className="mt-2 text-sm text-text-soft">{t('lists.repairPreviewMessage')}</p>
        </div>

        <div className="flex-1 overflow-y-auto p-5">
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <div className="rounded-lg border border-border-subtle bg-background-elevated p-3">
              <div className="text-xs font-medium uppercase text-text-soft">{t('lists.repairPreviewBefore')}</div>
              <div className="mt-1 text-sm text-text">
                {t('lists.repairPreviewCounts', { words: currentWordCount, categories: currentCategoryCount })}
              </div>
            </div>
            <div className="rounded-lg border border-fresh/25 bg-fresh/10 p-3">
              <div className="text-xs font-medium uppercase text-text-soft">{t('lists.repairPreviewSuggested')}</div>
              <div className="mt-1 text-sm text-text">
                {t('lists.repairPreviewRepairCount', { count: preview.repairs.length })}
              </div>
            </div>
            <div className="rounded-lg border border-border-subtle bg-background-elevated p-3">
              <div className="text-xs font-medium uppercase text-text-soft">{t('lists.repairPreviewSource')}</div>
              <div className="mt-1 text-sm text-text">{preview.seedKind || preview.provider}</div>
            </div>
            <div className="rounded-lg border border-border-subtle bg-background-elevated p-3">
              <div className="text-xs font-medium uppercase text-text-soft">{t('lists.repairPreviewTranslations')}</div>
              <div className="mt-1 text-sm text-text">
                {t('lists.repairPreviewTranslationCounts', {
                  reused: preview.translationStats.reused,
                  generated: preview.translationStats.generated,
                })}
              </div>
            </div>
          </div>

          {preview.description ? (
            <p className="mt-4 rounded-lg border border-border-subtle bg-background-elevated p-3 text-sm text-text-soft">
              {preview.description}
            </p>
          ) : null}
          {preview.ignoredSuggestionCount > 0 ? (
            <p className="mt-3 rounded-lg border border-border-subtle bg-background-elevated p-3 text-sm text-text-soft">
              {t('lists.repairPreviewIgnoredSuggestions', { count: preview.ignoredSuggestionCount })}
            </p>
          ) : null}

          <div className="mt-5 space-y-4">
            <section className="rounded-lg border border-border-subtle">
              <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border-subtle bg-background-elevated px-3 py-2">
                <h3 className="text-sm font-semibold text-text">{t('lists.repairPreviewSuggestedTitle')}</h3>
                <div className="flex items-center gap-2 text-xs text-text-soft">
                  <span>{t('lists.repairPreviewSelectedCount', { selected: selectedCount, total: preview.repairs.length })}</span>
                  <button
                    type="button"
                    className="rounded border border-border-subtle px-2 py-1 hover:bg-background"
                    onClick={handleCopyPreview}
                    disabled={repairing}
                  >
                    {copyStatus === 'copied'
                      ? t('lists.repairPreviewCopied')
                      : copyStatus === 'failed'
                        ? t('lists.repairPreviewCopyFailed')
                        : t('lists.repairPreviewCopy')}
                  </button>
                  <button
                    type="button"
                    className="rounded border border-border-subtle px-2 py-1 hover:bg-background"
                    onClick={() => setSelectedIds(new Set(preview.repairs.map((repair) => repair.currentItemId)))}
                    disabled={repairing}
                  >
                    {t('lists.repairPreviewSelectAll')}
                  </button>
                  <button
                    type="button"
                    className="rounded border border-border-subtle px-2 py-1 hover:bg-background"
                    onClick={() => setSelectedIds(new Set())}
                    disabled={repairing}
                  >
                    {t('lists.repairPreviewSelectNone')}
                  </button>
                </div>
              </div>

              {preview.repairs.length > 0 ? (
                <div className="divide-y divide-border-subtle">
                  {preview.repairs.map((repair) => (
                    <label
                      key={repair.currentItemId}
                      className="grid cursor-pointer gap-2 px-3 py-3 text-sm sm:grid-cols-[auto_1fr]"
                    >
                      <input
                        type="checkbox"
                        className="mt-1 size-4 accent-accent"
                        checked={selectedIds.has(repair.currentItemId)}
                        onChange={() => toggleRepair(repair.currentItemId)}
                        disabled={repairing}
                      />
                      <span className="grid gap-2">
                        <span className="flex flex-wrap items-center gap-2">
                          <span className="font-medium text-text">{repair.textKnown}</span>
                          <span className="rounded-full border border-border-subtle px-2 py-0.5 text-xs text-text-soft">
                            {repair.reason === 'known_side'
                              ? t('lists.repairPreviewKnownSideReason')
                              : t('lists.repairPreviewTranslationReason')}
                          </span>
                        </span>

                        {repair.textKnown !== repair.proposedTextKnown ? (
                          <span className="grid gap-1 sm:grid-cols-2">
                            <span className="rounded border border-danger/20 bg-danger/5 px-2 py-1 text-text-soft">
                              {repair.textKnown}
                            </span>
                            <span className="rounded border border-fresh/25 bg-fresh/10 px-2 py-1 text-text">
                              {repair.proposedTextKnown}
                            </span>
                          </span>
                        ) : null}

                        {repair.currentTextTarget !== repair.proposedTextTarget ? (
                          <span className="grid gap-1 sm:grid-cols-2">
                            <span className="rounded border border-danger/20 bg-danger/5 px-2 py-1 text-text-soft">
                              {repair.currentTextTarget || t('lists.noTranslationYet')}
                            </span>
                            <span className="rounded border border-fresh/25 bg-fresh/10 px-2 py-1 text-text">
                              {repair.proposedTextTarget}
                            </span>
                          </span>
                        ) : (
                          <span className="rounded border border-border-subtle bg-background-elevated px-2 py-1 text-text-soft">
                            {repair.proposedTextTarget}
                          </span>
                        )}

                        <span className="text-xs text-text-soft">
                          {repair.currentCategoryName}
                          {repair.knownAudioAssetId || repair.audioAssetId ? ` · ${t('lists.repairPreviewAudioKept')}` : ''}
                        </span>
                      </span>
                    </label>
                  ))}
                </div>
              ) : (
                <p className="px-3 py-4 text-sm text-text-soft">{t('lists.repairPreviewNoSuggestions')}</p>
              )}
            </section>

            <section className="rounded-lg border border-border-subtle">
                <div className="flex items-center justify-between border-b border-border-subtle bg-background-elevated px-3 py-2">
                  <h3 className="text-sm font-semibold text-text">{t('lists.repairPreviewUnchangedTitle')}</h3>
                  <span className="text-xs text-text-soft">{t('lists.wordsCount', { count: preview.unchanged.length })}</span>
                </div>
                <div className="divide-y divide-border-subtle">
                  {unchangedPreview.map((item) => (
                    <div
                      key={item.itemId}
                      className="grid gap-1 px-3 py-2 text-sm sm:grid-cols-[1fr_1fr_auto]"
                    >
                      <span className="min-w-0 break-words text-text">{item.textKnown}</span>
                      <span className="min-w-0 break-words text-text-soft">{item.textTarget}</span>
                      <span className="text-xs text-text-soft">{item.categoryName}</span>
                    </div>
                  ))}
                </div>
                {hasMoreUnchanged ? (
                  <p className="border-t border-border-subtle px-3 py-2 text-xs text-text-soft">
                    {t('lists.repairPreviewMoreUnchanged', { count: preview.unchanged.length - unchangedPreview.length })}
                  </p>
                ) : null}
            </section>
          </div>
        </div>

        <div className="flex justify-end gap-2 border-t border-border-subtle p-4">
          <button
            type="button"
            className="rounded-lg border border-border-subtle px-4 py-2 text-sm font-medium text-text-soft transition-colors hover:bg-background-elevated"
            onClick={onCancel}
            disabled={repairing}
          >
            {t('common.cancel')}
          </button>
          <button
            type="button"
            className="rounded-lg bg-danger px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-danger/90 disabled:opacity-60"
            onClick={() => onConfirm([...selectedIds])}
            disabled={repairing || selectedCount === 0}
          >
            {repairing ? t('lists.repairingAutogenerated') : t('lists.repairAutogeneratedApply')}
          </button>
        </div>
      </div>
    </div>
  );

  if (typeof document === 'undefined') return null;
  return createPortal(modal, document.body);
}

export function CategoryBrowser(props: CategoryBrowserProps) {
  const { list, forkedFromListName, triggerEditSignal } = props;
  const [storedEditorState, setStoredEditorState] = useState(() => ({
    listId: list.id,
    forkedFromListName,
    triggerEditSignal,
    editing: Boolean(forkedFromListName),
  }));
  const listChanged =
    storedEditorState.listId !== list.id ||
    storedEditorState.forkedFromListName !== forkedFromListName;
  const editTriggered = storedEditorState.triggerEditSignal !== triggerEditSignal;
  const editorState = listChanged
    ? {
        listId: list.id,
        forkedFromListName,
        triggerEditSignal,
        editing: Boolean(forkedFromListName),
      }
    : editTriggered
      ? { ...storedEditorState, triggerEditSignal, editing: true }
      : storedEditorState;
  const editorKey = [
    list.id,
    list.name,
    list.description ?? '',
    list.languageFrom,
    list.languageTo,
    String(list.isPublic),
    String(Boolean(list.isCommon)),
    String(Boolean(list.isRecommended)),
    forkedFromListName ?? '',
  ].join('\u0000');
  return (
    <CategoryBrowserContent
      key={editorKey}
      {...props}
      editingList={editorState.editing}
      setEditingList={(editing) => setStoredEditorState({ ...editorState, editing })}
    />
  );
}

function CategoryBrowserContent({
  list,
  categories,
  itemsByCategory,
  languages = [],
  isOwner,
  isEditor,
  forkedFromListName,
  onEditCategory,
  onEditAllWords,
  onCreateCategory,
  onUpdateList,
  onDismissForkNotice,
  onRenameCategory,
  onReorderCategories,
  onDeleteCategory,
  onFork,
  onDeleteList,
  onListUpdated,
  onPreviewAutogeneratedRepair,
  onRepairAutogenerated,
  editingList,
  setEditingList,
}: CategoryBrowserProps & {
  editingList: boolean;
  setEditingList: (editing: boolean) => void;
}) {
  const { t } = useI18n();
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());
  const [newCategoryName, setNewCategoryName] = useState('');
  const [showAddCategory, setShowAddCategory] = useState(false);
  const [dragOverId, setDragOverId] = useState<string | null>(null);
  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState('');
  const [listName, setListName] = useState(list.name);
  const [listDescription, setListDescription] = useState(list.description ?? '');
  const [listLanguageFrom, setListLanguageFrom] = useState(list.languageFrom);
  const [listLanguageTo, setListLanguageTo] = useState(list.languageTo);
  const [listIsPublic, setListIsPublic] = useState(list.isPublic);
  const [listIsCommon, setListIsCommon] = useState(Boolean(list.isCommon));
  const [listIsRecommended, setListIsRecommended] = useState(Boolean(list.isRecommended));
  const [savingList, setSavingList] = useState(false);
  const [headerMenuOpen, setHeaderMenuOpen] = useState(false);
  const [deleteCategoryConfirm, setDeleteCategoryConfirm] = useState<WordCategory | null>(null);
  const [deleteListConfirm, setDeleteListConfirm] = useState(false);
  const {
    preview: repairPreview,
    previewing: previewingRepair,
    repairing: repairingList,
    openPreview: handlePreviewRepairList,
    applyRepair: handleRepairListConfirmed,
    closePreview: closeRepairPreview,
  } = useAutogeneratedListRepair({
    listId: list.id,
    previewRepair: onPreviewAutogeneratedRepair,
    repair: onRepairAutogenerated,
  });
  const [forkingList, setForkingList] = useState(false);
  const [shareList, setShareList] = useState<WordList | null>(null);
  const dragItemRef = useRef<string | null>(null);
  const headerMenuRef = useRef<HTMLDivElement>(null);
  const canEditListMetadata = isOwner || isEditor;
  const canEditListContent = isOwner || (isEditor && Boolean(list.isCommon));
  const canDeleteList = isOwner || (isEditor && Boolean(list.isCommon));
  const canRepairAutogenerated = Boolean(
    isEditor && list.isAutogenerated && onPreviewAutogeneratedRepair && onRepairAutogenerated,
  );
  // Owner (and editors of common lists) can change visibility and reset the
  // link; anyone can copy the link of a public list.
  const canManageVisibility = isOwner || (isEditor && Boolean(list.isCommon));
  const canShareList = canManageVisibility || list.isPublic;
  const languageOptions = languages.length > 0 ? languages : [
    { code: 'cs', name: t('languageName.cs') },
    { code: 'vi', name: t('languageName.vi') },
    { code: 'en', name: t('languageName.en') },
  ];

  useEffect(() => {
    if (!headerMenuOpen) return;
    function handlePointerDown(e: PointerEvent) {
      if (headerMenuRef.current && !headerMenuRef.current.contains(e.target as Node)) {
        setHeaderMenuOpen(false);
      }
    }
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') setHeaderMenuOpen(false);
    }
    document.addEventListener('pointerdown', handlePointerDown);
    document.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('pointerdown', handlePointerDown);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [headerMenuOpen]);

  async function handleRenameSubmit(categoryId: string) {
    const trimmed = renameValue.trim();
    if (trimmed) {
      await onRenameCategory(categoryId, trimmed);
    }
    setRenamingId(null);
    setRenameValue('');
  }

  const toggleExpand = useCallback((id: string) => {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  async function handleAddCategory() {
    if (!newCategoryName.trim()) return;
    const newCategoryId = await onCreateCategory(newCategoryName.trim());
    setNewCategoryName('');
    setShowAddCategory(false);
    // Jump straight into the "add words" edit step for the freshly created category.
    if (newCategoryId) {
      onEditCategory(newCategoryId, 'known');
    }
  }

  async function handleListMetadataSubmit() {
    const trimmedName = listName.trim();
    if (!trimmedName) return;

    setSavingList(true);
    try {
      await onUpdateList(list.id, {
        name: trimmedName,
        description: listDescription.trim() || null,
        languageFrom: listLanguageFrom,
        languageTo: listLanguageTo,
        isPublic: listIsCommon || listIsRecommended ? true : listIsPublic,
        ...(isEditor ? { isCommon: listIsCommon } : {}),
        ...(isEditor ? { isRecommended: listIsRecommended } : {}),
      });
      onDismissForkNotice?.();
      setEditingList(false);
    } finally {
      setSavingList(false);
    }
  }

  function cancelListMetadataEdit() {
    setListName(list.name);
    setListDescription(list.description ?? '');
    setListLanguageFrom(list.languageFrom);
    setListLanguageTo(list.languageTo);
    setListIsPublic(list.isPublic);
    setListIsCommon(Boolean(list.isCommon));
    setListIsRecommended(Boolean(list.isRecommended));
    setEditingList(false);
    onDismissForkNotice?.();
  }

  function handleDragStart(categoryId: string) {
    dragItemRef.current = categoryId;
  }

  function handleDragOver(e: React.DragEvent, categoryId: string) {
    e.preventDefault();
    setDragOverId(categoryId);
  }

  function handleDrop(targetId: string) {
    const dragId = dragItemRef.current;
    if (!dragId || dragId === targetId) {
      setDragOverId(null);
      return;
    }
    const ordered = categories.map((c) => c.id);
    const fromIdx = ordered.indexOf(dragId);
    const toIdx = ordered.indexOf(targetId);
    if (fromIdx === -1 || toIdx === -1) return;
    ordered.splice(fromIdx, 1);
    ordered.splice(toIdx, 0, dragId);
    onReorderCategories(ordered);
    setDragOverId(null);
    dragItemRef.current = null;
  }

  async function handleForkList() {
    if (!onFork) return;
    setHeaderMenuOpen(false);
    setForkingList(true);
    try {
      await onFork(list.id);
    } finally {
      setForkingList(false);
    }
  }

  async function handleDeleteListConfirmed() {
    if (!onDeleteList) return;
    setDeleteListConfirm(false);
    await onDeleteList(list.id);
  }

  const allItems = getAllItemsInCategoryOrder(itemsByCategory, categories);
  const allWordsExpanded = expandedIds.has(ALL_WORDS_CATEGORY_ID);
  const totalItems = allItems.length;

  return (
    <div className="max-w-3xl mx-auto p-4 md:p-6">
      {/* List header */}
      <div className="mb-6">
        {editingList ? (
          <div className="rounded-lg border border-border-subtle bg-background-elevated p-3 shadow-sm">
            <div className="grid gap-3">
              {forkedFromListName ? (
                <div className="rounded-lg border border-accent/30 bg-accent/10 px-3 py-2">
                  <p className="text-xs font-semibold uppercase tracking-wide text-accent">
                    {t('lists.copyNoticeTitle')}
                  </p>
                  <p className="mt-1 text-sm text-text">
                    {t('lists.copyNoticeBody', { name: forkedFromListName })}
                  </p>
                </div>
              ) : null}
              <label className="grid gap-1">
                <span className="text-xs font-medium text-text-soft">{t('lists.listName')}</span>
                <input
                  type="text"
                  value={listName}
                  onChange={(e) => setListName(e.target.value)}
                  className="rounded-lg border border-border-subtle bg-background px-3 py-2 text-sm text-text outline-none focus:border-accent"
                  placeholder={forkedFromListName ? t('lists.nameCopyPlaceholder') : undefined}
                  autoFocus
                />
              </label>
              <label className="grid gap-1">
                <span className="text-xs font-medium text-text-soft">{t('lists.description')}</span>
                <textarea
                  value={listDescription}
                  onChange={(e) => setListDescription(e.target.value)}
                  rows={3}
                  className="resize-none rounded-lg border border-border-subtle bg-background px-3 py-2 text-sm text-text outline-none focus:border-accent"
                  placeholder={
                    forkedFromListName
                      ? t('lists.copyDescriptionPlaceholder')
                      : t('lists.descriptionPlaceholder')
                  }
                />
              </label>
              <div className="grid gap-2 sm:grid-cols-[1fr_auto_1fr] sm:items-end">
                <label className="grid gap-1">
                  <span className="text-xs font-medium text-text-soft">{t('lists.knownLanguage')}</span>
                  <select
                    value={listLanguageFrom}
                    onChange={(e) => setListLanguageFrom(e.target.value)}
                    className="rounded-lg border border-border-subtle bg-background px-3 py-2 text-sm text-text outline-none focus:border-accent"
                  >
                    {languageOptions.map((language) => (
                      <option key={language.code} value={language.code}>
                        {language.name}
                      </option>
                    ))}
                  </select>
                </label>
                <span className="hidden pb-2 text-xs text-text-soft sm:block">→</span>
                <label className="grid gap-1">
                  <span className="text-xs font-medium text-text-soft">{t('lists.targetLanguage')}</span>
                  <select
                    value={listLanguageTo}
                    onChange={(e) => setListLanguageTo(e.target.value)}
                    className="rounded-lg border border-border-subtle bg-background px-3 py-2 text-sm text-text outline-none focus:border-accent"
                  >
                    {languageOptions.map((language) => (
                      <option key={language.code} value={language.code}>
                        {language.name}
                      </option>
                    ))}
                  </select>
                </label>
              </div>
              {canManageVisibility && (
                <div className="flex flex-wrap items-center gap-1.5 text-sm text-text-soft">
                  <span aria-hidden>{list.isPublic ? '🌐' : '🔒'}</span>
                  <span>
                    {list.isPublic
                      ? t('lists.visibilityRowPublic')
                      : t('lists.visibilityRowPrivate')}
                  </span>
                  {!listIsCommon && !listIsRecommended && (
                    <button
                      type="button"
                      className="rounded text-accent underline-offset-2 hover:underline focus:outline-none focus-visible:ring-2 focus-visible:ring-accent/40"
                      onClick={() => setShareList(list)}
                    >
                      {t('lists.visibilityRowEdit')}
                    </button>
                  )}
                </div>
              )}
              {isEditor ? (
                <div className="grid gap-2">
                  <label className="flex items-start gap-2 rounded-lg border border-border-subtle bg-background px-3 py-2 text-sm text-text-soft">
                    <input
                      type="checkbox"
                      checked={listIsRecommended}
                      onChange={(e) => {
                        setListIsRecommended(e.target.checked);
                        if (e.target.checked) setListIsPublic(true);
                      }}
                      className="mt-0.5 size-4 accent-accent"
                    />
                    <span>
                      <span className="block font-medium text-text">{t('lists.recommendedList')}</span>
                      <span className="block text-xs">
                        {t('lists.recommendedListDescription', {
                          from: listLanguageFrom,
                          to: listLanguageTo,
                        })}
                      </span>
                    </span>
                  </label>
                  <label className="flex items-start gap-2 rounded-lg border border-border-subtle bg-background px-3 py-2 text-sm text-text-soft">
                    <input
                      type="checkbox"
                      checked={listIsCommon}
                      onChange={(e) => {
                        setListIsCommon(e.target.checked);
                        if (e.target.checked) setListIsPublic(true);
                      }}
                      className="mt-0.5 size-4 accent-accent"
                    />
                    <span>
                      <span className="block font-medium text-text">{t('lists.commonBaseList')}</span>
                      <span className="block text-xs">{t('lists.commonBaseListDescription')}</span>
                    </span>
                  </label>
                </div>
              ) : null}
              <div className="flex gap-2">
                <button
                  type="button"
                  className="rounded-lg bg-accent px-3 py-1.5 text-xs font-medium text-background disabled:opacity-50"
                  disabled={savingList || !listName.trim() || listLanguageFrom === listLanguageTo}
                  onClick={handleListMetadataSubmit}
                >
                  {savingList ? t('common.saving') : t('lists.saveList')}
                </button>
                <button
                  type="button"
                  className="rounded-lg border border-border-subtle px-3 py-1.5 text-xs font-medium text-text-soft"
                  onClick={cancelListMetadataEdit}
                >
                  {t('common.cancel')}
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
            <div className="min-w-0">
              <h1 className="text-xl font-semibold text-text">{list.name}</h1>
              <div className="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-text-soft">
                <span>{list.languageFrom} → {list.languageTo}</span>
                <ListBadges list={list} />
                <span className="basis-full sm:basis-auto">
                  {t('lists.listStats', { words: totalItems, categories: categories.length })}
                </span>
              </div>
              {list.description && (
                <p className="text-sm text-text-soft mt-1">{list.description}</p>
              )}
            </div>

            <div className="flex shrink-0 flex-wrap items-center gap-2">
              {canRepairAutogenerated ? (
                <button
                  type="button"
                  className="inline-flex items-center gap-2 rounded-lg border border-fresh/30 bg-fresh/10 px-4 py-2 text-sm font-semibold text-fresh shadow-sm transition-colors hover:bg-fresh/15 focus:outline-none focus-visible:ring-2 focus-visible:ring-fresh/40 disabled:opacity-60"
                  onClick={handlePreviewRepairList}
                  disabled={repairingList || previewingRepair}
                >
                  <svg width="15" height="15" viewBox="0 0 20 20" fill="none" className="text-current" aria-hidden="true">
                    <path d="M12.8 3.2a4.2 4.2 0 00-5.1 5.9l-4.2 4.2a1.7 1.7 0 102.4 2.4l4.2-4.2a4.2 4.2 0 005.9-5.1l-2.8 2.8-2.4-2.4 2.8-2.8z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                  {repairingList
                    ? t('lists.repairingAutogenerated')
                    : previewingRepair
                      ? t('lists.repairPreviewLoading')
                      : t('lists.repairAutogenerated')}
                </button>
              ) : null}

              {canEditListMetadata ? (
                <button
                  type="button"
                  className="inline-flex items-center gap-2 rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-background shadow-sm transition-colors hover:bg-accent/90 focus:outline-none focus-visible:ring-2 focus-visible:ring-accent/40"
                  onClick={() => setEditingList(true)}
                >
                  <svg width="15" height="15" viewBox="0 0 20 20" fill="none" className="text-current">
                    <path d="M11.5 4.5l4 4L7 17H3v-4L11.5 4.5z" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
                    <path d="M10 6l4 4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
                  </svg>
                  {t('lists.editList')}
                </button>
              ) : null}

              {canShareList ? (
                <button
                  type="button"
                  className="rounded-lg border border-border-subtle p-2 text-text-soft transition-colors hover:bg-background-elevated hover:text-text focus:outline-none focus-visible:ring-2 focus-visible:ring-accent/40"
                  onClick={() => setShareList(list)}
                  aria-label={t('share.manageTitle')}
                  title={t('share.manageTitle')}
                >
                  <svg width="16" height="16" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                    <circle cx="15" cy="5" r="2.25" stroke="currentColor" strokeWidth="1.5" />
                    <circle cx="5" cy="10" r="2.25" stroke="currentColor" strokeWidth="1.5" />
                    <circle cx="15" cy="15" r="2.25" stroke="currentColor" strokeWidth="1.5" />
                    <path d="M13 6.2L7 8.8M7 11.2l6 2.6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                  </svg>
                </button>
              ) : null}

              {/* Three-dots menu next to Edit list */}
              {(onFork || (canDeleteList && onDeleteList)) && (
                <div className="relative" ref={headerMenuRef}>
                  <button
                    type="button"
                    className="p-2 rounded-lg border border-border-subtle text-text-soft hover:text-text hover:bg-background-elevated transition-colors"
                    onClick={() => setHeaderMenuOpen((prev) => !prev)}
                    disabled={forkingList}
                    aria-label={t('lists.moreOptions')}
                  >
                    <svg width="16" height="16" viewBox="0 0 20 20" fill="currentColor">
                      <circle cx="10" cy="4" r="1.5" />
                      <circle cx="10" cy="10" r="1.5" />
                      <circle cx="10" cy="16" r="1.5" />
                    </svg>
                  </button>

                  {headerMenuOpen && (
                    <div className="absolute right-0 top-full mt-1 z-50 min-w-[140px] rounded-lg border border-border-subtle bg-background shadow-lg py-1">
                      {onFork && (
                        <button
                          type="button"
                          className="flex w-full items-center gap-2 px-3 py-2 text-sm text-text hover:bg-background-elevated transition-colors"
                          onClick={handleForkList}
                          disabled={forkingList}
                        >
                          <ForkIcon />
                          {forkingList ? t('lists.copying') : t('lists.copyList')}
                        </button>
                      )}
                      {canDeleteList && onDeleteList && (
                        <>
                          {onFork && <div className="my-1 border-t border-border-subtle" />}
                          <button
                            type="button"
                            className="flex w-full items-center gap-2 px-3 py-2 text-sm text-danger hover:bg-danger/10 transition-colors"
                            onClick={() => { setHeaderMenuOpen(false); setDeleteListConfirm(true); }}
                          >
                            <svg width="14" height="14" viewBox="0 0 20 20" fill="none">
                            <path d="M4 6h12M8 3h4M7 6v10m6-10v10M6 6l.6 10.2A1 1 0 007.6 17h4.8a1 1 0 001-.8L14 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                          </svg>
                            {t('lists.delete')}
                          </button>
                        </>
                      )}
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Categories */}
      <div className="space-y-2">
        {canEditListContent ? (
          <div className="overflow-hidden rounded-xl border border-accent/30 bg-gradient-to-br from-accent/15 via-background-elevated to-background shadow-sm ring-1 ring-accent/10">
            <button
              type="button"
              className="w-full flex items-center gap-3 px-4 py-3.5 text-left hover:bg-accent/5 transition-colors"
              onClick={() => toggleExpand(ALL_WORDS_CATEGORY_ID)}
            >
              <span className="inline-flex size-8 shrink-0 items-center justify-center rounded-full bg-accent/15 text-accent">
                <svg width="16" height="16" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                  <path d="M5 5.5h10M5 10h10M5 14.5h6" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
                </svg>
              </span>
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-semibold text-text text-sm">{t('lists.allWords')}</span>
                  <span className="rounded-full border border-accent/30 bg-accent/10 px-2 py-0.5 text-[11px] font-medium uppercase tracking-wide text-accent">
                    {t('lists.reviewMode')}
                  </span>
                </div>
                <p className="mt-0.5 text-xs text-text-soft">{t('lists.allWordsDescription')}</p>
              </div>
              <span className="text-xs text-text-soft">{t('lists.wordsCount', { count: totalItems })}</span>
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                className={`text-accent transition-transform shrink-0 ${allWordsExpanded ? 'rotate-90' : ''}`}
              >
                <path d="M6 4l4 4-4 4" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round" />
              </svg>
            </button>

            {allWordsExpanded && (
              <div className="border-t border-accent/20 px-4 pb-3">
                <div className="py-2 flex flex-wrap items-center gap-2">
                  <button
                    type="button"
                    className="px-3 py-1.5 rounded-lg bg-accent text-background text-xs font-semibold hover:bg-accent-strong transition-colors"
                    onClick={(e) => {
                      e.stopPropagation();
                      onEditAllWords();
                    }}
                  >
                    {t('lists.reviewAllWords')}
                  </button>
                  <span className="text-xs text-text-soft">{t('lists.allWordsSafeEditHint')}</span>
                </div>

                {allItems.length === 0 ? (
                  <p className="py-3 text-sm text-text-soft">{t('lists.emptyList')}</p>
                ) : (
                  <div className="divide-y divide-border-subtle">
                    {allItems.map((item) => (
                      <div key={item.id} className="flex items-center gap-3 py-2 text-sm">
                        <span className="flex-1 text-text truncate">{item.textKnown}</span>
                        <span className="flex-1 text-text-soft truncate">
                          {item.textTarget ?? (
                            <span className="italic text-fresh/70">{t('lists.missingTranslation')}</span>
                          )}
                        </span>
                        {item.audioStatus === 'ready' && (
                          <span className="text-xs text-done" title={t('lists.hasAudio')}>♪</span>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        ) : null}

        {categories.map((category) => {
          const catItems = itemsByCategory.get(category.id) ?? [];
          const isExpanded = expandedIds.has(category.id);
          const isDragOver = dragOverId === category.id;

          return (
            <div
              key={category.id}
              className={`rounded-lg border transition-colors ${
                isDragOver ? 'border-accent' : 'border-border-subtle'
              }`}
              draggable={canEditListContent}
              onDragStart={() => handleDragStart(category.id)}
              onDragOver={(e) => handleDragOver(e, category.id)}
              onDragEnd={() => setDragOverId(null)}
              onDrop={() => handleDrop(category.id)}
            >
              {/* Category header */}
              {renamingId === category.id ? (
                <div className="flex items-center gap-2 px-4 py-2.5">
                  <input
                    type="text"
                    value={renameValue}
                    onChange={(e) => setRenameValue(e.target.value)}
                    className="flex-1 px-2 py-1 rounded-md bg-background border border-accent text-text text-sm focus:outline-none"
                    autoFocus
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') void handleRenameSubmit(category.id);
                      if (e.key === 'Escape') { setRenamingId(null); setRenameValue(''); }
                    }}
                    onBlur={() => void handleRenameSubmit(category.id)}
                  />
                  <button
                    type="button"
                    className="px-2.5 py-1 rounded-md bg-accent text-background text-xs font-medium"
                    onMouseDown={(e) => { e.preventDefault(); void handleRenameSubmit(category.id); }}
                  >
                    {t('common.save')}
                  </button>
                  <button
                    type="button"
                    className="px-2.5 py-1 rounded-md border border-border-subtle text-text-soft text-xs"
                    onMouseDown={(e) => { e.preventDefault(); setRenamingId(null); setRenameValue(''); }}
                  >
                    {t('common.cancel')}
                  </button>
                </div>
              ) : (
                <button
                  type="button"
                  className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-background-elevated/50 rounded-lg transition-colors"
                  onClick={() => toggleExpand(category.id)}
                >
                  {canEditListContent && (
                    <span className="cursor-grab text-text-soft text-xs select-none hidden md:inline">⠿</span>
                  )}
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    className={`text-text-soft transition-transform shrink-0 ${isExpanded ? 'rotate-90' : ''}`}
                  >
                    <path d="M6 4l4 4-4 4" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round" />
                  </svg>
                  <span className="font-medium text-text text-sm flex-1 truncate">{category.name}</span>
                  <span className="text-xs text-text-soft">{t('lists.wordsCount', { count: catItems.length })}</span>
                </button>
              )}

              {/* Expanded word list */}
              {isExpanded && (
                <div className="px-4 pb-3 border-t border-border-subtle">
                  {/* Edit/Delete buttons */}
                  {canEditListContent && (
                    <div className="py-2 flex flex-wrap gap-2">
                      <button
                        type="button"
                        className="px-3 py-1.5 rounded-lg bg-accent/10 text-accent text-xs font-medium hover:bg-accent/20 transition-colors"
                        onClick={(e) => {
                          e.stopPropagation();
                          onEditCategory(category.id, 'known');
                        }}
                      >
                        {t('lists.editWords')}
                      </button>
                      <button
                        type="button"
                        className="px-3 py-1.5 rounded-lg border border-border-subtle text-text-soft text-xs hover:bg-background transition-colors"
                        onClick={(e) => {
                          e.stopPropagation();
                          setRenamingId(category.id);
                          setRenameValue(category.name);
                        }}
                      >
                        {t('lists.rename')}
                      </button>
                      <button
                        type="button"
                        className="px-3 py-1.5 rounded-lg text-danger/70 text-xs hover:bg-danger/10 transition-colors"
                        onClick={(e) => {
                          e.stopPropagation();
                          setDeleteCategoryConfirm(category);
                        }}
                      >
                        {t('lists.deleteCategory')}
                      </button>
                    </div>
                  )}

                  {catItems.length === 0 ? (
                    <p className="py-3 text-sm text-text-soft">{t('lists.emptyCategory')}</p>
                  ) : (
                    <div className="divide-y divide-border-subtle">
                      {catItems.map((item) => (
                        <div key={item.id} className="flex items-center gap-3 py-2 text-sm">
                          <span className="flex-1 text-text truncate">{item.textKnown}</span>
                          <span className="flex-1 text-text-soft truncate">
                            {item.textTarget ?? (
                              <span className="italic text-fresh/70">{t('lists.missingTranslation')}</span>
                            )}
                          </span>
                          {item.audioStatus === 'ready' && (
                            <span className="text-xs text-done" title={t('lists.hasAudio')}>♪</span>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Add category */}
      {canEditListContent && (
        <div className="mt-4">
          {showAddCategory ? (
            <div className="flex gap-2">
              <input
                type="text"
                placeholder={t('lists.categoryName')}
                value={newCategoryName}
                onChange={(e) => setNewCategoryName(e.target.value)}
                className="flex-1 px-3 py-2 rounded-lg bg-background-elevated border border-border-subtle text-text text-sm focus:outline-none focus:border-accent"
                autoFocus
                onKeyDown={(e) => {
                  if (e.key === 'Enter') handleAddCategory();
                  if (e.key === 'Escape') setShowAddCategory(false);
                }}
              />
              <button
                type="button"
                className="px-4 py-2 rounded-lg bg-accent text-background text-sm font-medium"
                onClick={handleAddCategory}
              >
                {t('editor.addCategory')}
              </button>
              <button
                type="button"
                className="px-4 py-2 rounded-lg border border-border-subtle text-text text-sm"
                onClick={() => setShowAddCategory(false)}
              >
                {t('common.cancel')}
              </button>
            </div>
          ) : (
            <button
              type="button"
              className="w-full py-2.5 rounded-lg border border-dashed border-border-subtle text-text-soft text-sm hover:border-accent hover:text-accent transition-colors"
              onClick={() => setShowAddCategory(true)}
            >
              + {t('lists.addCategoryCta')}
            </button>
          )}
        </div>
      )}

      <ConfirmModal
        isOpen={Boolean(deleteCategoryConfirm)}
        title={t('lists.deleteCategoryTitle', { name: deleteCategoryConfirm?.name ?? '' })}
        message={t('lists.deleteCategoryMessage')}
        confirmLabel={t('lists.deleteCategory')}
        onConfirm={() => {
          const id = deleteCategoryConfirm?.id;
          setDeleteCategoryConfirm(null);
          if (id) onDeleteCategory(id);
        }}
        onCancel={() => setDeleteCategoryConfirm(null)}
      />

      <ConfirmModal
        isOpen={deleteListConfirm}
        title={t('lists.deleteConfirm', { name: list.name })}
        message={t('lists.deleteListMessage')}
        confirmLabel={t('lists.delete')}
        onConfirm={handleDeleteListConfirmed}
        onCancel={() => setDeleteListConfirm(false)}
      />

      {repairPreview ? (
        <RepairPreviewModal
          list={list}
          preview={repairPreview}
          currentWordCount={totalItems}
          currentCategoryCount={categories.length}
          repairing={repairingList}
          onConfirm={handleRepairListConfirmed}
          onCancel={closeRepairPreview}
        />
      ) : null}

      {shareList && (
        <ShareVisibilityDialog
          list={shareList}
          canManage={canManageVisibility}
          onClose={() => setShareList(null)}
          onListUpdated={onListUpdated}
        />
      )}
    </div>
  );
}

function getAllItemsInCategoryOrder(
  map: Map<string, WordListItem[]>,
  categories: WordCategory[],
): WordListItem[] {
  const items: WordListItem[] = [];
  const seenCategoryIds = new Set<string>();

  for (const category of categories) {
    seenCategoryIds.add(category.id);
    items.push(...(map.get(category.id) ?? []));
  }

  for (const [categoryId, categoryItems] of map) {
    if (seenCategoryIds.has(categoryId)) continue;
    items.push(...categoryItems);
  }

  return items;
}
