'use client';

import { useI18n } from '@/components/I18nProvider';
import type { WordList } from '@/features/lists/types';

export function ForkIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <circle cx="6" cy="5" r="2.25" stroke="currentColor" strokeWidth="2" />
      <circle cx="18" cy="6" r="2.25" stroke="currentColor" strokeWidth="2" />
      <circle cx="6" cy="19" r="2.25" stroke="currentColor" strokeWidth="2" />
      <path d="M6 7.25v9.5M8.25 5.75h4.5A5.25 5.25 0 0118 11v-2.75" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

export function ListBadges({ list }: { list: WordList }) {
  const { t } = useI18n();
  return (
    <>
      {list.isCommon && <span className="inline-flex items-center rounded-full border border-fresh/20 bg-fresh/10 px-2 py-0.5 text-xs font-medium text-fresh">{t('lists.badgeCommonBase')}</span>}
      {list.isRecommended && <span className="inline-flex items-center rounded-full border border-accent/20 bg-accent/10 px-2 py-0.5 text-xs font-medium text-accent">{t('lists.badgeRecommended')}</span>}
      {list.isAutogenerated && <span className="inline-flex items-center rounded-full border border-border-subtle bg-text-soft/10 px-2 py-0.5 text-xs font-medium text-text-soft" title={t('lists.badgeAutogeneratedHint')}>{t('lists.badgeAutogenerated')}</span>}
      {list.audioIncomplete && <span className="inline-flex items-center rounded-full border border-fresh/20 bg-fresh/10 px-2 py-0.5 text-xs font-medium text-fresh" title={t('lists.badgeAudioMissingHint')}>{t('lists.badgeAudioMissing')}</span>}
      {list.isPublic && <span className="inline-flex items-center rounded-full border border-done/20 bg-done/10 px-2 py-0.5 text-xs font-medium text-done">{t('lists.badgePublic')}</span>}
      {!list.isPublic && !list.isCommon && <span className="inline-flex items-center rounded-full border border-border-subtle bg-text-soft/10 px-2 py-0.5 text-xs font-medium text-text-soft">{t('lists.badgePrivate')}</span>}
      {list.isPublic && (list.subscriberCount ?? 0) > 0 && <span className="inline-flex items-center gap-1 rounded-full border border-border-subtle bg-text-soft/10 px-2 py-0.5 text-xs font-medium text-text-soft" title={t('lists.learnerCount', { count: String(list.subscriberCount) })}>👥 {t('lists.learnerCount', { count: String(list.subscriberCount) })}</span>}
    </>
  );
}
