'use client';

import { useCallback, useState } from 'react';
import type { RepairAutogeneratedListPreview } from '@/features/lists/client/actions';

export function useAutogeneratedListRepair({
  listId,
  previewRepair,
  repair,
}: {
  listId: string;
  previewRepair?: (listId: string) => Promise<RepairAutogeneratedListPreview>;
  repair?: (
    listId: string,
    preview?: RepairAutogeneratedListPreview,
    selectedRepairItemIds?: string[],
  ) => Promise<void>;
}) {
  type RepairState = {
    listId: string;
    preview: RepairAutogeneratedListPreview | null;
    previewing: boolean;
    repairing: boolean;
  };
  const emptyState = useCallback((): RepairState => ({
    listId,
    preview: null,
    previewing: false,
    repairing: false,
  }), [listId]);
  const [state, setState] = useState<RepairState>(emptyState);
  const current = state.listId === listId ? state : emptyState();

  const openPreview = useCallback(async () => {
    if (!previewRepair) return;
    setState({ ...current, previewing: true });
    try {
      const preview = await previewRepair(listId);
      setState({ listId, preview, previewing: false, repairing: false });
    } finally {
      setState((previous) => previous.listId === listId
        ? { ...previous, previewing: false }
        : previous);
    }
  }, [current, listId, previewRepair]);

  const applyRepair = useCallback(async (selectedRepairItemIds: string[]) => {
    if (!repair || !current.preview) return;
    setState({ ...current, repairing: true });
    try {
      await repair(listId, current.preview, selectedRepairItemIds);
      setState(emptyState());
    } finally {
      setState((previous) => previous.listId === listId
        ? { ...previous, repairing: false }
        : previous);
    }
  }, [current, emptyState, listId, repair]);

  const closePreview = useCallback(() => {
    if (!current.repairing) setState(emptyState());
  }, [current.repairing, emptyState]);

  return {
    preview: current.preview,
    previewing: current.previewing,
    repairing: current.repairing,
    openPreview,
    applyRepair,
    closePreview,
  };
}
