import type { WordItemComment } from "@/lib/word-item-comment";

export type WordList = {
  id: string;
  ownerId: string | null;
  name: string;
  description: string | null;
  languageFrom: string;
  languageTo: string;
  isPublic: boolean;
  isCommon?: boolean;
  isRecommended?: boolean;
  isAutogenerated?: boolean;
  isOwner?: boolean;
  moderationStatus?: 'visible' | 'under_review' | 'rejected';
  moderationUpdatedAt?: string | Date | null;
  moderationDecisionCode?: import('@/features/moderation/contracts').ModerationDecisionCode | null;
  moderationPublicNote?: string | null;
  audioIncomplete?: boolean;
  /** Distinct other learners subscribed to this list (owner excluded). */
  subscriberCount?: number;
  createdAt?: string | Date;
  updatedAt?: string | Date;
};

export type TranslationProvider = 'google' | 'openrouter' | 'none';

export type WizardActiveStep =
  | 'edit'
  | 'preview'
  | 'translate'
  | 'audio-target'
  | 'audio-known';

export type PendingFork = {
  source: WordList;
  languageFrom: string;
  languageTo: string;
  provider: TranslationProvider;
  sourceLanguage: string;
  translationModel: string;
  translateCategoryNames: boolean;
};

export type WordCategory = {
  id: string;
  listId: string;
  name: string;
  position: number;
  isSystem: boolean;
};

export type WordListItem = {
  id: string;
  listId: string;
  categoryId: string | null;
  position: number;
  textKnown: string;
  textTarget: string | null;
  acceptedKnown?: string[];
  acceptedTarget?: string[];
  translationStatus: string;
  knownAudioAssetId?: string | null;
  knownAudioStatus?: string;
  knownAudioUrl?: string | null;
  knownAudioArweaveUrl?: string | null;
  knownAudioArweaveUrls?: string[];
  knownAudioStorageRef?: string | null;
  knownAudioVoiceId?: string | null;
  knownAudioCreatedAt?: string | null;
  audioAssetId?: string | null;
  audioStatus: string;
  audioUrl?: string | null;
  audioArweaveUrl?: string | null;
  audioArweaveUrls?: string[];
  audioStorageRef?: string | null;
  audioVoiceId?: string | null;
  audioCreatedAt?: string | null;
  notes: string | null;
  comment?: WordItemComment | null;
};

export type DiffResult = {
  added: string[];
  added_positions?: { text: string; position: number }[];
  removed: { id: string; text_known: string; text_target: string | null }[];
  reordered: { id: string; text: string; from_pos: number; to_pos: number }[];
  unchanged: number;
  warning?: string;
};

export type ConfirmResult = {
  completed: boolean;
  needs_translation: boolean;
  pending_items?: {
    id: string;
    text_known: string;
    text_target: string | null;
    accepted_known?: string[];
    accepted_target?: string[];
    position: number;
    comment?: string | null;
    // Null = the word currently has no category. Populated only in the
    // client-built review flow (itemsToPending); the server confirm path omits
    // it because those items already belong to the edited category.
    category_id?: string | null;
  }[];
};

/** Structured advisory warning surfaced per row in the editor (see lib/translation-validate.ts). */
type ClientValidationWarning = {
  code: string;
  severity: string;
  confidence: string;
  message: string;
};

export type CompletedTranslationRow = {
  id: string;
  textKnown: string;
  textTarget: string;
  status: 'pending' | 'ok' | 'error' | 'manual';
  error?: string;
  warning?: string;
  source?: 'dedup' | 'api';
  acceptedKnown?: string[];
  acceptedTarget?: string[];
  /** Manual study-note text. undefined = untouched; '' = cleared. */
  comment?: string;
  /** Tracks whether the user edited the note in this session (controls save). */
  commentDirty?: boolean;
  /** Deterministic quality warnings for this row (advisory). */
  validationWarnings?: ClientValidationWarning[];
};

export type GoogleUsageScope = 'translate' | 'tts';

export type GoogleUsageAccountScope = {
  scope: GoogleUsageScope;
  used_units: number;
  request_count: number;
  account_limit: number;
  free_monthly_units: number;
  paused: boolean;
  limit_message?: string | null;
};

export type GoogleUsageGlobalScope = {
  scope: GoogleUsageScope;
  used_units: number;
  request_count: number;
  account_count: number;
  free_monthly_units: number;
};

export type GoogleUsageResponse = {
  period_start: string;
  inspected_user_id: string;
  account: GoogleUsageAccountScope[];
  global?: GoogleUsageGlobalScope[];
};
