ALTER TABLE "users"
  ADD COLUMN "settings_language" text,
  ADD COLUMN "settings_language_selected_at" timestamp;

UPDATE "users"
SET
  "settings_language" = 'en',
  "settings_language_selected_at" = now()
WHERE "settings_language" IS NULL;

CREATE TABLE "ui_translation_cache" (
  "language_code" text PRIMARY KEY,
  "messages" jsonb NOT NULL,
  "source_hash" text NOT NULL,
  "provider" text DEFAULT 'google' NOT NULL,
  "status" text DEFAULT 'autogenerated' NOT NULL,
  "last_error" text,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX "ui_translation_cache_source_hash_idx"
  ON "ui_translation_cache" USING btree ("source_hash");
