import { createHash } from "crypto";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { uiTranslationCache } from "@/lib/db/schema";
import { googleTranslate } from "@/lib/translation";
import {
  COMMON_LANGUAGES,
  GOOGLE_TRANSLATE_LANGUAGES,
  mergeLanguages,
  normalizeLanguageCode,
  type SupportedLanguage,
} from "./languages";
import { enMessages, reviewedMessages, type I18nMessages } from "./messages";

export type MessagesResponse = {
  language: string;
  messages: I18nMessages;
  status: "reviewed" | "autogenerated" | "fallback";
  sourceHash: string;
};

let supportedLanguageMemoryCache: {
  target: string;
  expiresAt: number;
  languages: SupportedLanguage[];
} | null = null;

export function getSourceHash(): string {
  return createHash("sha256").update(JSON.stringify(enMessages)).digest("hex");
}

export async function fetchGoogleSupportedLanguages(target = "en"): Promise<SupportedLanguage[]> {
  const normalizedTarget = normalizeLanguageCode(target);
  const now = Date.now();
  if (
    supportedLanguageMemoryCache &&
    supportedLanguageMemoryCache.target === normalizedTarget &&
    supportedLanguageMemoryCache.expiresAt > now
  ) {
    return supportedLanguageMemoryCache.languages;
  }

  const apiKey = process.env.GOOGLE_TRANSLATE_API_KEY;
  const cachedGoogleLanguages = mergeLanguages(COMMON_LANGUAGES, GOOGLE_TRANSLATE_LANGUAGES);
  if (!apiKey) return cachedGoogleLanguages;

  const url = new URL("https://translation.googleapis.com/language/translate/v2/languages");
  url.searchParams.set("key", apiKey);
  url.searchParams.set("target", normalizedTarget);

  const res = await fetch(url);
  if (!res.ok) return cachedGoogleLanguages;
  const data = await res.json();
  const languages = Array.isArray(data?.data?.languages)
    ? data.data.languages
        .map((item: { language?: string; name?: string }) => ({
          code: normalizeLanguageCode(item.language),
          name: String(item.name || item.language || "").trim(),
          source: "google" as const,
        }))
        .filter((item: SupportedLanguage) => item.code && item.name)
    : [];

  const merged = mergeLanguages(COMMON_LANGUAGES, languages);
  supportedLanguageMemoryCache = {
    target: normalizedTarget,
    expiresAt: now + 24 * 60 * 60 * 1000,
    languages: merged,
  };
  return merged;
}

export async function isGoogleSupportedLanguage(language: string): Promise<boolean> {
  const normalized = normalizeLanguageCode(language);
  const supported = await fetchGoogleSupportedLanguages("en");
  return supported.some((item) => normalizeLanguageCode(item.code) === normalized);
}

export async function getMessagesForLanguage(language: string): Promise<MessagesResponse> {
  const normalized = normalizeLanguageCode(language);
  const sourceHash = getSourceHash();
  const reviewed = reviewedMessages[normalized];
  if (reviewed) {
    return { language: normalized, messages: reviewed, status: "reviewed", sourceHash };
  }

  const [cached] = await db
    .select()
    .from(uiTranslationCache)
    .where(eq(uiTranslationCache.languageCode, normalized))
    .limit(1);

  if (cached?.sourceHash === sourceHash && cached.messages) {
    return {
      language: normalized,
      messages: { ...enMessages, ...cached.messages },
      status: "autogenerated",
      sourceHash,
    };
  }

  try {
    const keys = Object.keys(enMessages) as Array<keyof typeof enMessages>;
    const values = keys.map((key) => enMessages[key]);
    const translated = await googleTranslate(values, "en", normalized);
    const messages: I18nMessages = { ...enMessages };
    translated.forEach((result, index) => {
      if (result.status === "ok" && result.translated) {
        messages[keys[index]] = result.translated;
      }
    });

    await db
      .insert(uiTranslationCache)
      .values({
        languageCode: normalized,
        messages,
        sourceHash,
        provider: "google",
        status: "autogenerated",
        lastError: null,
      })
      .onConflictDoUpdate({
        target: uiTranslationCache.languageCode,
        set: {
          messages,
          sourceHash,
          provider: "google",
          status: "autogenerated",
          lastError: null,
          updatedAt: new Date(),
        },
      });

    return { language: normalized, messages, status: "autogenerated", sourceHash };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await db
      .insert(uiTranslationCache)
      .values({
        languageCode: normalized,
        messages: enMessages,
        sourceHash,
        provider: "google",
        status: "failed",
        lastError: message,
      })
      .onConflictDoUpdate({
        target: uiTranslationCache.languageCode,
        set: {
          lastError: message,
          status: "failed",
          updatedAt: new Date(),
        },
      })
      .catch(() => undefined);

    return { language: normalized, messages: enMessages, status: "fallback", sourceHash };
  }
}
