'use client';

import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import {
  bundledMessages,
  enMessages,
  getLanguageStatus,
  interpolateMessage,
  REVIEWED_LANGUAGES,
  type I18nKey,
  type I18nMessages,
} from '@/lib/i18n/messages';
import { normalizeLanguageCode } from '@/lib/i18n/languages';

type I18nContextValue = {
  language: string;
  status: 'reviewed' | 'autogenerated' | 'fallback';
  isAutogenerated: boolean;
  isLoading: boolean;
  t: (key: I18nKey, values?: Record<string, string | number>) => string;
};

const I18nContext = createContext<I18nContextValue | null>(null);

export function I18nProvider({
  language,
  children,
}: {
  language?: string | null;
  children: ReactNode;
}) {
  const normalizedLanguage = normalizeLanguageCode(language ?? 'en');
  const bundled = bundledMessages[normalizedLanguage];
  const [messages, setMessages] = useState<I18nMessages>(bundled ?? enMessages);
  const [status, setStatus] = useState<I18nContextValue['status']>(
    bundled ? getLanguageStatus(normalizedLanguage) : 'fallback',
  );
  const [isLoading, setIsLoading] = useState(!bundled);

  useEffect(() => {
    // Bundled dictionaries (en/cs reviewed, uk/vi seed) load instantly from the
    // local bundle; their status still reflects whether the language is
    // reviewed, so uk/vi read as "generated".
    const localBundled = bundledMessages[normalizedLanguage];
    if (localBundled) {
      setMessages(localBundled);
      setStatus(getLanguageStatus(normalizedLanguage));
      setIsLoading(false);
      return;
    }

    let cancelled = false;
    setIsLoading(true);
    setStatus('fallback');
    fetch(`/api/i18n/messages?language=${encodeURIComponent(normalizedLanguage)}`)
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error('Failed to load messages'))))
      .then((data) => {
        if (cancelled) return;
        setMessages({ ...enMessages, ...(data.messages ?? {}) });
        setStatus(data.status === 'autogenerated' ? 'autogenerated' : 'fallback');
        setIsLoading(false);
      })
      .catch(() => {
        if (cancelled) return;
        setMessages(enMessages);
        setStatus('fallback');
        setIsLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [normalizedLanguage]);

  const value = useMemo<I18nContextValue>(() => {
    return {
      language: normalizedLanguage,
      status,
      isAutogenerated: !REVIEWED_LANGUAGES.has(normalizedLanguage),
      isLoading,
      t: (key, values) => interpolateMessage(messages[key] ?? enMessages[key] ?? key, values),
    };
  }, [isLoading, messages, normalizedLanguage, status]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nContextValue {
  const ctx = useContext(I18nContext);
  if (!ctx) {
    return {
      language: 'en',
      status: 'reviewed',
      isAutogenerated: false,
      isLoading: false,
      t: (key, values) => interpolateMessage(enMessages[key] ?? key, values),
    };
  }
  return ctx;
}
