'use client';

import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import {
  bundledMessages,
  enMessages,
  getLanguageStatus,
  interpolateMessage,
  REVIEWED_LANGUAGES,
  type I18nKey,
  type I18nMessages,
} from '@/lib/i18n/messages';
import { normalizeLanguageCode } from '@/lib/i18n/languages';
import { apiFetch } from '@/features/shared/http/api-runtime';

type I18nContextValue = {
  language: string;
  status: 'reviewed' | 'autogenerated' | 'fallback';
  isAutogenerated: boolean;
  isLoading: boolean;
  t: (key: I18nKey, values?: Record<string, string | number>) => string;
};

const I18nContext = createContext<I18nContextValue | null>(null);

export function I18nProvider({
  language,
  children,
}: {
  language?: string | null;
  children: ReactNode;
}) {
  const normalizedLanguage = normalizeLanguageCode(language ?? 'en');
  const bundled = bundledMessages[normalizedLanguage];

  if (bundled) {
    return (
      <I18nValueProvider
        language={normalizedLanguage}
        messages={bundled}
        status={getLanguageStatus(normalizedLanguage)}
        isLoading={false}
      >
        {children}
      </I18nValueProvider>
    );
  }

  return (
    <RemoteI18nProvider key={normalizedLanguage} language={normalizedLanguage}>
      {children}
    </RemoteI18nProvider>
  );
}

function RemoteI18nProvider({
  language,
  children,
}: {
  language: string;
  children: ReactNode;
}) {
  const [remote, setRemote] = useState<{
    messages: I18nMessages;
    status: I18nContextValue['status'];
    isLoading: boolean;
  }>({ messages: enMessages, status: 'fallback', isLoading: true });

  useEffect(() => {
    let cancelled = false;
    apiFetch(`/api/i18n/messages?language=${encodeURIComponent(language)}`)
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error('Failed to load messages'))))
      .then((data) => {
        if (cancelled) return;
        setRemote({
          messages: { ...enMessages, ...(data.messages ?? {}) },
          status: data.status === 'autogenerated' ? 'autogenerated' : 'fallback',
          isLoading: false,
        });
      })
      .catch(() => {
        if (cancelled) return;
        setRemote({ messages: enMessages, status: 'fallback', isLoading: false });
      });

    return () => {
      cancelled = true;
    };
  }, [language]);

  return (
    <I18nValueProvider
      language={language}
      messages={remote.messages}
      status={remote.status}
      isLoading={remote.isLoading}
    >
      {children}
    </I18nValueProvider>
  );
}

function I18nValueProvider({
  language,
  messages,
  status,
  isLoading,
  children,
}: {
  language: string;
  messages: I18nMessages;
  status: I18nContextValue['status'];
  isLoading: boolean;
  children: ReactNode;
}) {

  const value = useMemo<I18nContextValue>(() => {
    return {
      language,
      status,
      isAutogenerated: !REVIEWED_LANGUAGES.has(language),
      isLoading,
      t: (key, values) => interpolateMessage(messages[key] ?? enMessages[key] ?? key, values),
    };
  }, [isLoading, language, messages, status]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nContextValue {
  const ctx = useContext(I18nContext);
  if (!ctx) {
    return {
      language: 'en',
      status: 'reviewed',
      isAutogenerated: false,
      isLoading: false,
      t: (key, values) => interpolateMessage(enMessages[key] ?? key, values),
    };
  }
  return ctx;
}
