'use client';

import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import {
  enMessages,
  interpolateMessage,
  reviewedMessages,
  REVIEWED_LANGUAGES,
  type I18nKey,
  type I18nMessages,
} from '@/lib/i18n/messages';
import { normalizeLanguageCode } from '@/lib/i18n/languages';

type I18nContextValue = {
  language: string;
  status: 'reviewed' | 'autogenerated' | 'fallback';
  isAutogenerated: boolean;
  t: (key: I18nKey, values?: Record<string, string | number>) => string;
};

const I18nContext = createContext<I18nContextValue | null>(null);

export function I18nProvider({
  language,
  children,
}: {
  language?: string | null;
  children: ReactNode;
}) {
  const normalizedLanguage = normalizeLanguageCode(language ?? 'en');
  const reviewed = reviewedMessages[normalizedLanguage];
  const [messages, setMessages] = useState<I18nMessages>(reviewed ?? enMessages);
  const [status, setStatus] = useState<I18nContextValue['status']>(
    reviewed ? 'reviewed' : 'fallback',
  );

  useEffect(() => {
    const localReviewed = reviewedMessages[normalizedLanguage];
    if (localReviewed) {
      setMessages(localReviewed);
      setStatus('reviewed');
      return;
    }

    let cancelled = false;
    setMessages(enMessages);
    setStatus('fallback');
    fetch(`/api/i18n/messages?language=${encodeURIComponent(normalizedLanguage)}`)
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error('Failed to load messages'))))
      .then((data) => {
        if (cancelled) return;
        setMessages({ ...enMessages, ...(data.messages ?? {}) });
        setStatus(data.status === 'autogenerated' ? 'autogenerated' : 'fallback');
      })
      .catch(() => {
        if (cancelled) return;
        setMessages(enMessages);
        setStatus('fallback');
      });

    return () => {
      cancelled = true;
    };
  }, [normalizedLanguage]);

  const value = useMemo<I18nContextValue>(() => {
    return {
      language: normalizedLanguage,
      status,
      isAutogenerated: !REVIEWED_LANGUAGES.has(normalizedLanguage),
      t: (key, values) => interpolateMessage(messages[key] ?? enMessages[key] ?? key, values),
    };
  }, [messages, normalizedLanguage, status]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nContextValue {
  const ctx = useContext(I18nContext);
  if (!ctx) {
    return {
      language: 'en',
      status: 'reviewed',
      isAutogenerated: false,
      t: (key, values) => interpolateMessage(enMessages[key] ?? key, values),
    };
  }
  return ctx;
}

