'use client';

import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import { useI18n } from '@/components/I18nProvider';
import { writePreferredPublicLanguage } from '@/lib/i18n/public-language';
import {
  COMMON_LANGUAGES,
  GOOGLE_TRANSLATE_LANGUAGES,
  getLanguageFlag,
  getLocalizedLanguageName,
  getNativeLanguageName,
  languageMatchesSearch,
  mergeLanguages,
  normalizeLanguageCode,
  orderSettingsLanguages,
  type SupportedLanguage,
} from '@/lib/i18n/languages';
import { BUNDLED_UI_LANGUAGE_CODES, REVIEWED_LANGUAGES } from '@/lib/i18n/messages';
import { UiLanguageRequestPanel } from '@/features/shared/languages/UiLanguageRequestPanel';
import { usePlatformCapabilities } from '@/packages/product/shared/platform/capabilities';

interface InterfaceLanguageSelectorProps {
  value: string;
  onChange: (language: string) => void;
  align?: 'left' | 'right';
  className?: string;
  compact?: boolean;
  /** Hide the language name on narrow screens, showing only the flag + chevron. */
  hideLabelBelowSm?: boolean;
  languages?: SupportedLanguage[];
}

const onboardingVars = {
  '--ob-surface': '#F4EFE2',
  '--ob-surface-hover': '#FFF8E8',
  '--ob-ink': '#2A2218',
  '--ob-ink-soft': '#6B5E48',
  '--ob-accent': '#1E6FA8',
} as CSSProperties;

const BUNDLED_UI_LANGUAGE_CODE_SET = new Set(
  BUNDLED_UI_LANGUAGE_CODES.map(normalizeLanguageCode),
);
const BUNDLED_UI_LANGUAGES = mergeLanguages(COMMON_LANGUAGES, GOOGLE_TRANSLATE_LANGUAGES)
  .filter((item) => BUNDLED_UI_LANGUAGE_CODE_SET.has(normalizeLanguageCode(item.code)));

export function InterfaceLanguageSelector({
  value,
  onChange,
  align = 'left',
  className = '',
  compact = false,
  hideLabelBelowSm = false,
  languages: providedLanguages,
}: InterfaceLanguageSelectorProps) {
  const { t, language } = useI18n();
  const { runtime } = usePlatformCapabilities();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [view, setView] = useState<'available' | 'request'>('available');
  const ref = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const dropdownShiftRef = useRef(0);
  const languages = providedLanguages ?? BUNDLED_UI_LANGUAGES;

  useEffect(() => {
    if (!open) return;
    function onPointerDown(event: MouseEvent) {
      if (ref.current && !ref.current.contains(event.target as Node)) setOpen(false);
    }
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Escape') setOpen(false);
    }
    document.addEventListener('mousedown', onPointerDown);
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('mousedown', onPointerDown);
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [open]);

  useLayoutEffect(() => {
    if (!open) {
      dropdownShiftRef.current = 0;
      return;
    }

    function updateDropdownShift() {
      const node = dropdownRef.current;
      if (!node) return;

      const viewportPadding = 12;
      const rect = node.getBoundingClientRect();
      const baseLeft = rect.left - dropdownShiftRef.current;
      const baseRight = rect.right - dropdownShiftRef.current;
      const maxRight = window.innerWidth - viewportPadding;
      let nextShift = 0;

      if (baseLeft < viewportPadding) {
        nextShift = viewportPadding - baseLeft;
      } else if (baseRight > maxRight) {
        nextShift = maxRight - baseRight;
      }

      dropdownShiftRef.current = nextShift;
      node.style.transform = nextShift ? `translateX(${nextShift}px)` : '';
    }

    updateDropdownShift();
    window.addEventListener('resize', updateDropdownShift);
    window.addEventListener('orientationchange', updateDropdownShift);
    return () => {
      window.removeEventListener('resize', updateDropdownShift);
      window.removeEventListener('orientationchange', updateDropdownShift);
    };
  }, [open]);

  const requestedValue = normalizeLanguageCode(value);
  const normalizedValue = languages.some(
    (item) => normalizeLanguageCode(item.code) === requestedValue,
  )
    ? requestedValue
    : 'en';
  const getDisplayName = useCallback(
    (item: SupportedLanguage) =>
      getLocalizedLanguageName(item.code, language) ?? item.name,
    [language],
  );

  const visibleLanguages = useMemo(() => {
    const filtered = languages.filter((item) =>
      languageMatchesSearch(item, query, [getDisplayName(item)]),
    );
    return orderSettingsLanguages(filtered);
  }, [getDisplayName, languages, query]);
  const visibleHasAutogenerated = visibleLanguages.some(
    (item) => !REVIEWED_LANGUAGES.has(normalizeLanguageCode(item.code)),
  );

  const current = useMemo(
    () => languages.find((item) => normalizeLanguageCode(item.code) === normalizedValue),
    [languages, normalizedValue],
  );
  const currentName =
    (current ? getDisplayName(current) : getLocalizedLanguageName(normalizedValue, language)) ??
    normalizedValue.toUpperCase();
  const currentFlag = current?.flag ?? getLanguageFlag(normalizedValue) ?? '🌐';
  const buttonSizeClass = compact ? 'w-full justify-between' : '';

  function choose(code: string) {
    const normalized = normalizeLanguageCode(code);
    onChange(normalized);
    writePreferredPublicLanguage(normalized);
    setQuery('');
    setOpen(false);
  }

  function toggleOpen() {
    const opening = !open;
    if (opening) {
      setView('available');
      setQuery('');
    }
    setOpen(opening);
  }

  const dropdownAlign = align === 'right' ? 'right-0' : 'left-0';

  return (
    <div
      ref={ref}
      style={onboardingVars}
      className={`relative ${compact ? 'w-full' : 'inline-block'} ${className}`}
      data-testid="interface-language-selector"
    >
      <button
        type="button"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-label={t('language.selectorLabel')}
        onClick={toggleOpen}
        className={`inline-flex h-10 max-w-full items-center gap-2 rounded-full border-2 border-[var(--ob-ink)] bg-[var(--ob-surface)] px-3.5 text-xs font-bold text-[color:var(--ob-ink)] transition-colors hover:bg-[var(--ob-surface-hover)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ob-accent)] ${buttonSizeClass}`}
      >
        <span aria-hidden="true" className="text-base leading-none">{currentFlag}</span>
        <span className={`min-w-0 truncate${hideLabelBelowSm ? ' hidden sm:inline' : ''}`}>
          {currentName}
        </span>
        <svg
          aria-hidden="true"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
          className={`h-3.5 w-3.5 shrink-0 transition-transform ${open ? 'rotate-180' : ''}`}
        >
          <path d="m6 9 6 6 6-6" />
        </svg>
      </button>
      {open ? (
        <div
          ref={dropdownRef}
          className={`absolute ${dropdownAlign} z-30 mt-2 w-80 max-w-[calc(100vw-1.5rem)]`}
        >
          {view === 'request' ? (
            <UiLanguageRequestPanel
              supportedCodes={BUNDLED_UI_LANGUAGE_CODE_SET}
              onBack={() => {
                setView('available');
                setQuery('');
              }}
            />
          ) : (
            <>
              <input
                type="search"
                value={query}
                autoFocus
                placeholder={t('onboarding.searchLanguages')}
                aria-label={t('language.selectorLabel')}
                onChange={(event) => setQuery(event.target.value)}
                // 16px on a phone: iOS Safari auto-zooms into any focused field
                // under that, and this one takes focus the moment the dropdown
                // opens — so the page arrived zoomed in and clipped at the sides.
                // Back to 14px from `sm` up, where no browser zooms.
                className="mb-1.5 h-10 w-full rounded-xl border-2 border-[var(--ob-ink)] bg-[var(--ob-surface)] px-3 text-base text-[color:var(--ob-ink)] outline-none transition-colors placeholder:text-[color:var(--ob-ink-soft)] placeholder:opacity-70 focus:bg-[var(--ob-surface-hover)] sm:text-sm"
              />
              <div className="onboarding-combobox-list overflow-hidden">
            <ul
              role="listbox"
              aria-label={t('language.selectorLabel')}
              className="max-h-80 overflow-y-auto p-1"
            >
              {visibleLanguages.length === 0 ? (
                <li className="px-3 py-2 text-sm onboarding-text-soft">
                  {t('onboarding.noLanguagesFound')}
                </li>
              ) : (
                visibleLanguages.map((item, index) => {
                  const code = normalizeLanguageCode(item.code);
                  const displayName = getDisplayName(item);
                  const nativeName = getNativeLanguageName(code);
                  const selected = code === normalizedValue;
                  const autogenerated = !REVIEWED_LANGUAGES.has(code);
                  const flag = item.flag ?? getLanguageFlag(code);
                  return (
                    <li key={`${item.code}-${index}`} role="none">
                      <button
                        type="button"
                        role="option"
                        aria-selected={selected}
                        onClick={() => choose(item.code)}
                        className={`onboarding-combobox-option flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-left text-sm ${selected ? 'font-bold' : 'font-medium'}`}
                      >
                        <span aria-hidden="true" className="w-5 shrink-0 text-base leading-none">
                          {flag ?? '·'}
                        </span>
                        <span className="min-w-0 flex-1">
                          <span className="block truncate">{displayName}</span>
                          {nativeName && nativeName !== displayName ? (
                            <span className="block truncate text-[0.68rem] leading-tight onboarding-text-soft">
                              {nativeName}
                            </span>
                          ) : null}
                        </span>
                        <span className="shrink-0 text-[0.62rem] uppercase tracking-wide onboarding-text-soft">
                          {code}
                        </span>
                        {autogenerated ? (
                          <span className="shrink-0 rounded-full border border-[var(--ob-ink)] px-1.5 py-0.5 text-[0.58rem] uppercase tracking-wide onboarding-text-soft">
                            {t('language.autogeneratedBadge')}
                          </span>
                        ) : null}
                      </button>
                    </li>
                  );
                })
              )}
            </ul>
            {visibleHasAutogenerated ? (
              <div className="border-t-2 border-[var(--ob-ink)] px-3 py-2 text-[0.68rem] leading-snug onboarding-text-soft">
                {t('language.autogeneratedBadgeHelp')}
              </div>
            ) : null}
                <div className="border-t-2 border-[var(--ob-ink)] p-2">
                  <button
                    type="button"
                    onClick={() => {
                      setView('request');
                      setQuery('');
                    }}
                    className="w-full rounded-lg px-2 py-1.5 text-left text-xs font-bold text-[color:var(--ob-accent)] hover:bg-[var(--ob-surface-hover)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ob-accent)]"
                  >
                    + {t('language.requestButton')}
                  </button>
                  {runtime === 'web' ? (
                    <p className="mb-0 mt-1.5 px-2 text-[0.68rem] leading-snug onboarding-text-soft">
                      {t('language.browserTranslateHelp')}
                    </p>
                  ) : null}
                </div>
              </div>
            </>
          )}
        </div>
      ) : null}
    </div>
  );
}
