'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  COMMON_LANGUAGES,
  findBestSupportedLanguage,
  getBrowserLanguageCandidates,
  mergeLanguages,
  normalizeLanguageCode,
  orderSettingsLanguages,
  type SupportedLanguage,
} from '@/lib/i18n/languages';
import { REVIEWED_LANGUAGES } from '@/lib/i18n/messages';
import { useI18n } from '@/components/I18nProvider';

interface SettingsLanguagePickerProps {
  value: string;
  onChange: (language: string) => void;
  compact?: boolean;
}

export function SettingsLanguagePicker({
  value,
  onChange,
  compact = false,
}: SettingsLanguagePickerProps) {
  const { t, language } = useI18n();
  const [query, setQuery] = useState('');
  const [languages, setLanguages] = useState<SupportedLanguage[]>(COMMON_LANGUAGES);
  const [loading, setLoading] = useState(false);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setFailed(false);
    const params = new URLSearchParams({ target: language });
    if (query.trim()) params.set('q', query.trim());
    fetch(`/api/settings-languages?${params.toString()}`)
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error('Failed'))))
      .then((data) => {
        if (cancelled) return;
        setLanguages(mergeLanguages(COMMON_LANGUAGES, data.languages ?? []));
      })
      .catch(() => {
        if (cancelled) return;
        setLanguages(COMMON_LANGUAGES);
        setFailed(true);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [language, query]);

  const normalizedValue = normalizeLanguageCode(value);
  const displayNames = useMemo(() => {
    try {
      return new Intl.DisplayNames(language, { type: 'language' });
    } catch {
      return null;
    }
  }, [language]);
  const getDisplayName = useCallback(
    (item: SupportedLanguage) => displayNames?.of(normalizeLanguageCode(item.code)) ?? item.name,
    [displayNames],
  );
  const suggested = useMemo(
    () => findBestSupportedLanguage(getBrowserLanguageCandidates(), languages),
    [languages],
  );
  const visibleLanguages = useMemo(() => {
    const lower = query.trim().toLowerCase();
    const filtered = !lower
      ? languages
      : languages.filter(
      (item) =>
        item.name.toLowerCase().includes(lower) ||
        getDisplayName(item).toLowerCase().includes(lower) ||
        item.code.toLowerCase().includes(lower),
    );
    return orderSettingsLanguages(filtered);
  }, [getDisplayName, languages, query]);

  return (
    <div className="flex flex-col gap-3">
      <label className="flex flex-col gap-1.5">
        <span className="text-xs font-semibold uppercase tracking-wide text-text-soft/70">
          <span className="inline-flex items-center gap-1.5">
            <span aria-hidden="true">🌐</span>
            <span>{t('language.selectorLabel')}</span>
          </span>
        </span>
        <input
          type="search"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder={t('language.searchPlaceholder')}
          className="w-full rounded-lg border border-border-subtle bg-background px-3 py-2 text-sm text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/60"
        />
      </label>
      {failed && <p className="m-0 text-xs text-text-soft">{t('language.unavailable')}</p>}
      {loading && <p className="m-0 text-xs text-text-soft">{t('language.loading')}</p>}
      <div className={compact ? 'max-h-44 overflow-y-auto rounded-lg border border-border-subtle' : 'max-h-72 overflow-y-auto rounded-xl border border-border-subtle'}>
        {visibleLanguages.map((item, index) => {
          const selected = normalizeLanguageCode(item.code) === normalizedValue;
          const autogenerated = !REVIEWED_LANGUAGES.has(normalizeLanguageCode(item.code));
          return (
            <button
              key={`${item.code}-${index}`}
              type="button"
              onClick={() => onChange(item.code)}
              className={`flex w-full items-center justify-between gap-3 border-b border-border-subtle/70 px-3 py-2.5 text-left text-sm last:border-b-0 transition-colors ${
                selected
                  ? 'bg-accent-soft text-accent'
                  : 'bg-background-elevated/30 text-text hover:bg-background-elevated'
              }`}
              aria-pressed={selected}
            >
              <span className="min-w-0">
                <span className="block truncate font-medium">{getDisplayName(item)}</span>
                <span className="block text-[0.68rem] uppercase tracking-wide text-text-soft">
                  {item.code}
                  {item.code === suggested ? ` · ${t('language.browserSuggestion')}` : ''}
                </span>
              </span>
              {autogenerated && (
                <span className="shrink-0 rounded-full border border-border-subtle px-2 py-0.5 text-[0.62rem] uppercase tracking-wide text-text-soft">
                  {t('language.autogeneratedBadge')}
                </span>
              )}
            </button>
          );
        })}
      </div>
      {!REVIEWED_LANGUAGES.has(normalizedValue) && (
        <p className="m-0 rounded-lg border border-amber-400/25 bg-amber-100/10 px-3 py-2 text-xs leading-relaxed text-text-soft">
          {t('language.autogeneratedNotice')}
        </p>
      )}
    </div>
  );
}
