import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { LandingPage } from '../LandingPage';

vi.mock('@/components/SpeckledBackground', () => ({
  SpeckledBackground: () => <div data-testid="speckled-background" />,
}));

describe('LandingPage language selector', () => {
  beforeEach(() => {
    localStorage.clear();
    vi.stubGlobal(
      'fetch',
      vi.fn(async (input: RequestInfo | URL) => {
        const url = String(input);
        if (url.startsWith('/api/i18n/messages')) {
          return {
            ok: true,
            json: async () => ({
              status: 'autogenerated',
              messages: {
                'landing.hero.title': 'Palabras que se quedan',
                'landing.hero.subtitle':
                  'Get Word te ayuda a memorizar palabras y frases.',
                'landing.hero.getStarted': 'Empezar',
              },
            }),
          };
        }
        return {
          ok: true,
          json: async () => ({
            languages: [
              { code: 'en', name: 'English', source: 'common', flag: '🇬🇧' },
              { code: 'cs', name: 'Czech', source: 'common', flag: '🇨🇿' },
              { code: 'es', name: 'Spanish', source: 'google', flag: '🇪🇸' },
            ],
          }),
        };
      }),
    );
  });

  it('uses the shared interface selector with the full language list', async () => {
    render(<LandingPage />);

    expect(screen.getByTestId('interface-language-selector')).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));

    expect(screen.getByRole('option', { name: /Czech/i })).toBeInTheDocument();
    expect(await screen.findByRole('option', { name: /Spanish/i })).toBeInTheDocument();
  });

  it('translates landing copy when selecting a generated language', async () => {
    render(<LandingPage />);

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));
    fireEvent.click(await screen.findByRole('option', { name: /Spanish/i }));

    expect(await screen.findByRole('heading', { name: 'Palabras que se quedan' })).toBeInTheDocument();
    expect(localStorage.getItem('get-word-landing-lang')).toBe('es');
  });

  it('shows a loading status while generated landing copy loads', async () => {
    const translationGate = { resolve: () => {} };
    vi.mocked(fetch).mockImplementation(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.startsWith('/api/i18n/messages')) {
        await new Promise<void>((resolve) => {
          translationGate.resolve = resolve;
        });
        return {
          ok: true,
          json: async () => ({
            status: 'autogenerated',
            messages: {
              'landing.hero.title': 'Palabras que se quedan',
            },
          }),
        } as Response;
      }
      return {
        ok: true,
        json: async () => ({
          languages: [
            { code: 'en', name: 'English', source: 'common', flag: '🇬🇧' },
            { code: 'es', name: 'Spanish', source: 'google', flag: '🇪🇸' },
          ],
        }),
      } as Response;
    });

    render(<LandingPage />);

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));
    fireEvent.click(await screen.findByRole('option', { name: /Spanish|español/i }));

    expect(await screen.findByRole('status')).toHaveTextContent('Loading language');

    translationGate.resolve();

    expect(await screen.findByRole('heading', { name: 'Palabras que se quedan' })).toBeInTheDocument();
    await waitFor(() => {
      expect(screen.queryByRole('status')).not.toBeInTheDocument();
    });
  });
});
