import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { LandingPage } from '../LandingPage';

vi.mock('@/components/SpeckledBackground', () => ({
  SpeckledBackground: () => <div data-testid="speckled-background" />,
}));

describe('LandingPage language selector', () => {
  beforeEach(() => {
    localStorage.clear();
    vi.stubGlobal(
      'fetch',
      vi.fn(async (input: RequestInfo | URL) => {
        const url = String(input);
        if (url.startsWith('/api/i18n/messages')) {
          return {
            ok: true,
            json: async () => ({
              status: 'autogenerated',
              messages: {
                'landing.hero.title': 'Palabras que se quedan',
                'landing.hero.subtitle':
                  'Get Word te ayuda a memorizar palabras y frases.',
                'landing.hero.getStarted': 'Empezar',
              },
            }),
          };
        }
        return {
          ok: true,
          json: async () => ({
            languages: [
              { code: 'en', name: 'English', source: 'common', flag: '🇬🇧' },
              { code: 'cs', name: 'Czech', source: 'common', flag: '🇨🇿' },
              { code: 'es', name: 'Spanish', source: 'google', flag: '🇪🇸' },
              { code: 'id', name: 'Indonesian', source: 'google', flag: '🇮🇩' },
            ],
          }),
        };
      }),
    );
  });

  it('uses the shared interface selector with the full language list', async () => {
    render(<LandingPage />);

    expect(screen.getByTestId('interface-language-selector')).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));

    expect(screen.getByRole('option', { name: /Czech/i })).toBeInTheDocument();
    expect(await screen.findByRole('option', { name: /Spanish/i })).toBeInTheDocument();
  });

  it('translates landing copy when selecting a generated language', async () => {
    render(<LandingPage />);

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));
    fireEvent.click(await screen.findByRole('option', { name: /Spanish/i }));

    expect(await screen.findByRole('heading', { name: 'Palabras que se quedan' })).toBeInTheDocument();
    expect(localStorage.getItem('get-word-landing-lang')).toBe('es');
  });

  it('keeps the demo card connected to the selected learning pair', async () => {
    render(<LandingPage />);

    fireEvent.focus(document.getElementById('landing-language-from') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /cs/i }));

    fireEvent.focus(document.getElementById('landing-language-to') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /id/i }));

    expect(await screen.findByText('ano')).toBeInTheDocument();
    expect(screen.getByText('ya')).toBeInTheDocument();
    expect(localStorage.getItem('get-word-landing-pair')).toBe(
      JSON.stringify({ from: 'cs', to: 'id' }),
    );
  });

  it('disables the language already selected on the other side', async () => {
    render(<LandingPage />);

    fireEvent.focus(document.getElementById('landing-language-from') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /cs/i }));

    fireEvent.focus(document.getElementById('landing-language-to') as Element);
    expect(await screen.findByRole('option', { name: /cs/i })).toBeDisabled();
  });

  it('does not prefill the target language from a stored pair after reload', async () => {
    localStorage.setItem('get-word-landing-pair', JSON.stringify({ from: 'cs', to: 'id' }));

    render(<LandingPage />);

    const targetInput = document.getElementById('landing-language-to') as HTMLInputElement;
    expect(targetInput.parentElement).toHaveClass('onboarding-combobox-highlight');
    expect(targetInput.parentElement).toHaveTextContent('Select a language');
    expect(targetInput.parentElement).not.toHaveTextContent('Indonesian');
  });

  it('saves whether the visitor wants to create a custom list', async () => {
    render(<LandingPage />);

    const customListCheckbox = screen.getByRole('checkbox', {
      name: /create my own vocabulary list/i,
    });
    expect(customListCheckbox).not.toBeChecked();

    fireEvent.focus(document.getElementById('landing-language-from') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /cs/i }));

    fireEvent.focus(document.getElementById('landing-language-to') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /id/i }));

    fireEvent.click(customListCheckbox);
    fireEvent.click(document.querySelector('.lp-btn-hero') as Element);

    expect(localStorage.getItem('get-word-landing-pair')).toBe(
      JSON.stringify({ from: 'cs', to: 'id', wantsOwnList: true }),
    );
  });

  it('saves the detected-language fallback when target is missing', async () => {
    render(<LandingPage />);

    await screen.findByText('yes');
    fireEvent.click(document.querySelector('.lp-btn-hero') as Element);

    const saved = JSON.parse(localStorage.getItem('get-word-landing-pair') ?? '{}') as {
      from?: string;
      to?: string;
    };
    expect(saved.from).toBeTruthy();
    expect(saved.to).toBe(saved.from === 'en' ? 'cs' : 'en');
  });

  it('persists the effective pair when the sticky header CTA is used', async () => {
    render(<LandingPage />);

    await screen.findByText('yes');
    fireEvent.click(document.querySelector('.lp-btn-ghost') as Element);

    const saved = JSON.parse(localStorage.getItem('get-word-landing-pair') ?? '{}') as {
      from?: string;
      to?: string;
    };
    expect(saved.from).toBeTruthy();
    expect(saved.to).toBe(saved.from === 'en' ? 'cs' : 'en');
  });

  it('shows a loading status while generated landing copy loads', async () => {
    const translationGate = { resolve: () => {} };
    vi.mocked(fetch).mockImplementation(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.startsWith('/api/i18n/messages')) {
        await new Promise<void>((resolve) => {
          translationGate.resolve = resolve;
        });
        return {
          ok: true,
          json: async () => ({
            status: 'autogenerated',
            messages: {
              'landing.hero.title': 'Palabras que se quedan',
            },
          }),
        } as Response;
      }
      return {
        ok: true,
        json: async () => ({
          languages: [
            { code: 'en', name: 'English', source: 'common', flag: '🇬🇧' },
            { code: 'es', name: 'Spanish', source: 'google', flag: '🇪🇸' },
          ],
        }),
      } as Response;
    });

    render(<LandingPage />);

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));
    fireEvent.click(await screen.findByRole('option', { name: /Spanish|español/i }));

    expect(await screen.findByRole('status')).toHaveTextContent('Loading language');

    translationGate.resolve();

    expect(await screen.findByRole('heading', { name: 'Palabras que se quedan' })).toBeInTheDocument();
    await waitFor(() => {
      expect(screen.queryByRole('status')).not.toBeInTheDocument();
    });
  });
});
