import { eq, inArray } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { resolveUserFromRequest, unauthorizedResponse } from "@/lib/auth";
import { db } from "@/lib/db/client";
import {
  googleApiUsage,
  reviewEvents,
  schoolFeatureUsage,
  schoolMemberships,
  schoolTranslationRequests,
  userApiKeys,
  userCategoryFilters,
  userDevices,
  userListSubscriptions,
  userMemoryHooks,
  userProgress,
  wordCategories,
  wordListItems,
  wordLists,
} from "@/lib/db/schema";
import { serializeWordList } from "@/lib/word-list-dto";

function exportFilename() {
  return `get-word-personal-data-${new Date().toISOString().slice(0, 10)}.json`;
}

export async function GET(request: NextRequest) {
  const user = await resolveUserFromRequest(request);
  if (!user) return unauthorizedResponse();

  const [
    devices,
    progress,
    reviews,
    memoryHooks,
    categoryFilters,
    subscriptions,
    ownedLists,
    providerConnections,
    googleUsage,
    schoolMembershipRows,
    schoolUsage,
    schoolTranslationRows,
  ] = await Promise.all([
    db.select().from(userDevices).where(eq(userDevices.userId, user.id)),
    db.select().from(userProgress).where(eq(userProgress.userId, user.id)),
    db.select().from(reviewEvents).where(eq(reviewEvents.userId, user.id)),
    db.select().from(userMemoryHooks).where(eq(userMemoryHooks.userId, user.id)),
    db.select().from(userCategoryFilters).where(eq(userCategoryFilters.userId, user.id)),
    db.select().from(userListSubscriptions).where(eq(userListSubscriptions.userId, user.id)),
    db.select().from(wordLists).where(eq(wordLists.ownerId, user.id)),
    db
      .select({
        id: userApiKeys.id,
        provider: userApiKeys.provider,
        keyLabel: userApiKeys.keyLabel,
        status: userApiKeys.status,
        lastValidatedAt: userApiKeys.lastValidatedAt,
        connectedAt: userApiKeys.connectedAt,
        updatedAt: userApiKeys.updatedAt,
        keyLast4: userApiKeys.keyLast4,
        connectionMethod: userApiKeys.connectionMethod,
        translationModel: userApiKeys.translationModel,
        createdAt: userApiKeys.createdAt,
      })
      .from(userApiKeys)
      .where(eq(userApiKeys.userId, user.id)),
    db.select().from(googleApiUsage).where(eq(googleApiUsage.userId, user.id)),
    db.select().from(schoolMemberships).where(eq(schoolMemberships.userId, user.id)),
    db.select().from(schoolFeatureUsage).where(eq(schoolFeatureUsage.userId, user.id)),
    db
      .select()
      .from(schoolTranslationRequests)
      .where(eq(schoolTranslationRequests.userId, user.id)),
  ]);

  const ownedListIds = ownedLists.map((list) => list.id);
  const [ownedCategories, ownedItems] =
    ownedListIds.length > 0
      ? await Promise.all([
          db
            .select()
            .from(wordCategories)
            .where(inArray(wordCategories.listId, ownedListIds)),
          db
            .select()
            .from(wordListItems)
            .where(inArray(wordListItems.listId, ownedListIds)),
        ])
      : [[], []];

  const subscribedListIds = subscriptions.map((subscription) => subscription.listId);
  const subscribedLists =
    subscribedListIds.length > 0
      ? await db
          .select({
            id: wordLists.id,
            name: wordLists.name,
            description: wordLists.description,
            languageFrom: wordLists.languageFrom,
            languageTo: wordLists.languageTo,
            isPublic: wordLists.isPublic,
            isCommon: wordLists.isCommon,
            isRecommended: wordLists.isRecommended,
            isAutogenerated: wordLists.isAutogenerated,
            createdAt: wordLists.createdAt,
            updatedAt: wordLists.updatedAt,
          })
          .from(wordLists)
          .where(inArray(wordLists.id, subscribedListIds))
      : [];

  return NextResponse.json(
    {
      exportedAt: new Date().toISOString(),
      format: "get-word-personal-data-export-v1",
      user,
      devices,
      learning: {
        progress,
        reviewEvents: reviews,
        memoryHooks,
        categoryFilters,
      },
      lists: {
        owned: {
          lists: ownedLists.map(serializeWordList),
          categories: ownedCategories,
          items: ownedItems,
        },
        subscriptions,
        subscribedLists,
      },
      providers: {
        connections: providerConnections,
        note: "Provider secrets and encrypted API keys are intentionally excluded from exports.",
      },
      usage: {
        googleApiUsage: googleUsage,
        schoolFeatureUsage: schoolUsage,
      },
      schools: {
        memberships: schoolMembershipRows,
        translationRequests: schoolTranslationRows,
      },
    },
    {
      headers: {
        "Cache-Control": "no-store",
        "Content-Disposition": `attachment; filename="${exportFilename()}"`,
      },
    },
  );
}
