import type { I18nMessages } from "./locales/en";

// Generated by `pnpm run ui:generate-locales`.
// Kept empty in source control until generated UI dictionaries are intentionally bundled.
export const generatedBundledMessages: Record<string, I18nMessages> = {};
export const generatedBundledMessagesSourceHash: string | null = null;
