import { enMessages, type I18nKey, type I18nMessages } from "./locales/en";
import { csMessages } from "./locales/cs";
import { ukMessages } from "./locales/uk";
import { viMessages } from "./locales/vi";

export { enMessages, csMessages, ukMessages, viMessages };
export type { I18nKey, I18nMessages };

/**
 * Languages with a hand-written, human-reviewed dictionary. Any other language
 * is served via the Google auto-translation fallback (see `lib/i18n/server.ts`)
 * and flagged as autogenerated in the UI.
 */
export const REVIEWED_LANGUAGES = new Set(["en", "cs", "uk", "vi"]);

export const reviewedMessages: Record<string, I18nMessages> = {
  en: enMessages,
  cs: csMessages,
  uk: ukMessages,
  vi: viMessages,
};

export function interpolateMessage(message: string, values?: Record<string, string | number>) {
  if (!values) return message;
  return message.replace(/\{([^}]+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}
