import { enMessages, type I18nKey, type I18nMessages } from "./locales/en";
import { csMessages } from "./locales/cs";
import { ukMessages } from "./locales/uk";
import { viMessages } from "./locales/vi";
import { generatedBundledMessages } from "./generated-bundled-messages";

export { enMessages };
export type { I18nKey, I18nMessages };

/**
 * Languages we consider human-reviewed: their dictionary is treated as the
 * source of truth and is NOT flagged as machine-generated in the UI. Everything
 * else — including bundled-but-unreviewed languages like uk/vi — shows the
 * "generated" mark.
 */
export const REVIEWED_LANGUAGES = new Set(["en", "cs"]);

/**
 * Languages that ship with a full bundled dictionary, so they can be served
 * instantly without any runtime translation (see `lib/i18n/server.ts`). uk/vi
 * keep their dictionaries as a high-quality seed
 * even though they are no longer "reviewed" — we serve the bundle but badge it
 * as generated. Languages without a bundle are not selectable.
 */
export const bundledMessages: Record<string, I18nMessages> = {
  en: enMessages,
  cs: csMessages,
  uk: ukMessages,
  vi: viMessages,
  ...generatedBundledMessages,
};

/** The only locale codes that may appear in the app-language picker. */
export const BUNDLED_UI_LANGUAGE_CODES = Object.freeze(Object.keys(bundledMessages));

/** Status of a language's UI dictionary for badge/notice purposes. */
export function getLanguageStatus(language: string): "reviewed" | "autogenerated" {
  return REVIEWED_LANGUAGES.has(language) ? "reviewed" : "autogenerated";
}

export function interpolateMessage(message: string, values?: Record<string, string | number>) {
  if (!values) return message;
  return message.replace(/\{([^}]+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}
