import { createHash } from "crypto";
import {
  COMMON_LANGUAGES,
  GOOGLE_TRANSLATE_LANGUAGES,
  getLocalizedLanguageName,
  mergeLanguages,
  normalizeLanguageCode,
  type SupportedLanguage,
} from "./languages";
import {
  bundledMessages,
  enMessages,
  getLanguageStatus,
  type I18nMessages,
} from "./messages";

export type MessagesResponse = {
  language: string;
  messages: I18nMessages;
  status: "reviewed" | "autogenerated" | "fallback";
  sourceHash: string;
};

export function getSourceHash(): string {
  return createHash("sha256").update(JSON.stringify(enMessages)).digest("hex");
}

export async function fetchGoogleSupportedLanguages(target = "en"): Promise<SupportedLanguage[]> {
  const normalizedTarget = normalizeLanguageCode(target);
  return mergeLanguages(COMMON_LANGUAGES, GOOGLE_TRANSLATE_LANGUAGES).map((language) => ({
    ...language,
    name: getLocalizedLanguageName(language.code, normalizedTarget) ?? language.name,
  }));
}

export async function isGoogleSupportedLanguage(language: string): Promise<boolean> {
  const normalized = normalizeLanguageCode(language);
  const supported = await fetchGoogleSupportedLanguages("en");
  return supported.some((item) => normalizeLanguageCode(item.code) === normalized);
}

export async function getMessagesForLanguage(language: string): Promise<MessagesResponse> {
  const normalized = normalizeLanguageCode(language);
  const sourceHash = getSourceHash();
  // Bundled languages (en/cs reviewed, uk/vi seed) are served from their local
  // dictionary without a Google round-trip. Their badge status still depends on
  // whether the language is reviewed, so uk/vi serve instantly but read as
  // "generated" in the UI.
  const bundled = bundledMessages[normalized];
  if (bundled) {
    return {
      language: normalized,
      messages: bundled,
      status: getLanguageStatus(normalized),
      sourceHash,
    };
  }

  // Runtime Google translation is intentionally disabled. Non-bundled UI
  // languages render the English source so the browser may translate locally;
  // only the explicit offline generator can create additional bundled locales.
  return {
    language: normalized,
    messages: enMessages,
    status: "fallback",
    sourceHash,
  };
}
