import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { LandingPage } from '../LandingPage';

vi.mock('@/components/SpeckledBackground', () => ({
  SpeckledBackground: () => <div data-testid="speckled-background" />,
}));

describe('LandingPage language selector', () => {
  const preventJsdomNavigation = (event: MouseEvent) => {
    if (event.target instanceof Element && event.target.closest('a[href]')) {
      event.preventDefault();
    }
  };

  beforeEach(() => {
    document.addEventListener('click', preventJsdomNavigation);
    localStorage.clear();
    vi.stubGlobal(
      'fetch',
      vi.fn(async (input: RequestInfo | URL) => {
        const url = String(input);
        if (url.startsWith('/api/i18n/messages')) {
          return {
            ok: true,
            json: async () => ({
              status: 'autogenerated',
              messages: {
                'landing.hero.title': 'Palabras que se quedan',
                'landing.hero.subtitle':
                  'Get Word te ayuda a memorizar palabras y frases.',
                'landing.hero.getStarted': 'Empezar',
              },
            }),
          };
        }
        return {
          ok: true,
          json: async () => ({
            languages: [
              { code: 'en', name: 'English', source: 'common', flag: '🇬🇧' },
              { code: 'cs', name: 'Czech', source: 'common', flag: '🇨🇿' },
              { code: 'es', name: 'Spanish', source: 'google', flag: '🇪🇸' },
              { code: 'id', name: 'Indonesian', source: 'google', flag: '🇮🇩' },
            ],
          }),
        };
      }),
    );
  });

  afterEach(() => {
    document.removeEventListener('click', preventJsdomNavigation);
    vi.unstubAllGlobals();
  });

  const stubCoarsePointer = () =>
    vi.stubGlobal(
      'matchMedia',
      vi.fn((query: string) => ({
        matches: query.includes('coarse'),
        media: query,
        onchange: null,
        addEventListener: vi.fn(),
        removeEventListener: vi.fn(),
        addListener: vi.fn(),
        removeListener: vi.fn(),
        dispatchEvent: vi.fn(),
      })),
    );

  it('uses the shared interface selector with the full language list', async () => {
    render(<LandingPage />);

    expect(screen.getByTestId('interface-language-selector')).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));

    expect(screen.getByRole('option', { name: /Czech/i })).toBeInTheDocument();
    expect(await screen.findByRole('option', { name: /Spanish/i })).toBeInTheDocument();
  });

  it('translates landing copy when selecting a generated language', async () => {
    render(<LandingPage />);

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));
    fireEvent.click(await screen.findByRole('option', { name: /Spanish/i }));

    expect(await screen.findByRole('heading', { name: 'Palabras que se quedan' })).toBeInTheDocument();
    expect(localStorage.getItem('get-word-landing-lang')).toBe('es');
  });

  it('keeps the demo card connected to the selected learning pair', async () => {
    render(<LandingPage />);

    fireEvent.focus(document.getElementById('landing-language-from') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /cs/i }));

    fireEvent.focus(document.getElementById('landing-language-to') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /id/i }));

    expect(await screen.findByText('ano')).toBeInTheDocument();
    expect(screen.getByText('ya')).toBeInTheDocument();
    expect(localStorage.getItem('get-word-landing-pair')).toBe(
      JSON.stringify({ from: 'cs', to: 'id', wantsOwnList: true }),
    );
  });

  it('keeps the hero language list open while a touch gesture scrolls it', async () => {
    render(<LandingPage />);

    const knownLanguageInput = screen.getByRole('combobox', { name: /I know language/i });
    fireEvent.focus(knownLanguageInput);

    const listbox = await screen.findByRole('listbox');
    const czechOption = await screen.findByRole('option', { name: /cs/i });
    expect(czechOption).toBeInTheDocument();

    fireEvent.pointerDown(czechOption, {
      pointerType: 'touch',
      clientX: 40,
      clientY: 120,
    });
    fireEvent.pointerMove(czechOption, {
      pointerType: 'touch',
      clientX: 40,
      clientY: 40,
    });
    fireEvent.scroll(listbox);
    fireEvent.pointerUp(czechOption, {
      pointerType: 'touch',
      clientX: 40,
      clientY: 40,
    });

    expect(screen.getByRole('listbox')).toBeInTheDocument();

    fireEvent.click(document.body);

    await waitFor(() => {
      expect(screen.queryByRole('listbox')).not.toBeInTheDocument();
    });
  });

  it('does not open the hero language list from the label tap target', async () => {
    render(<LandingPage />);

    fireEvent.pointerDown(screen.getAllByText('I know')[0]);

    expect(screen.queryByRole('listbox')).not.toBeInTheDocument();

    fireEvent.focus(screen.getByRole('combobox', { name: /I know language/i }));
    expect(await screen.findByRole('listbox')).toBeInTheDocument();

    fireEvent.pointerDown(screen.getAllByText('I know')[0]);

    await waitFor(() => {
      expect(screen.queryByRole('listbox')).not.toBeInTheDocument();
    });
  });

  it('selects a hero language after a completed tap', async () => {
    render(<LandingPage />);

    fireEvent.focus(screen.getByRole('combobox', { name: /I know language/i }));
    const czechOption = await screen.findByRole('option', { name: /cs/i });

    fireEvent.click(czechOption);

    await waitFor(() => {
      expect(screen.queryByRole('listbox')).not.toBeInTheDocument();
    });
    expect(localStorage.getItem('get-word-landing-pair')).toBe(
      JSON.stringify({ from: 'cs', wantsOwnList: true }),
    );
  });

  it('reopens the hero language list when the focused input is tapped again', async () => {
    render(<LandingPage />);

    const knownLanguageInput = screen.getByRole('combobox', { name: /I know language/i });
    fireEvent.click(knownLanguageInput);
    expect(await screen.findByRole('listbox')).toBeInTheDocument();

    fireEvent.keyDown(knownLanguageInput, { key: 'Escape' });
    await waitFor(() => {
      expect(screen.queryByRole('listbox')).not.toBeInTheDocument();
    });

    fireEvent.pointerDown(knownLanguageInput);
    expect(await screen.findByRole('listbox')).toBeInTheDocument();

    fireEvent.click(knownLanguageInput);
    expect(screen.getByRole('listbox')).toBeInTheDocument();
  });

  it('opens a keyboardless bottom sheet for the hero picker on touch devices', async () => {
    stubCoarsePointer();
    render(<LandingPage />);

    // The closed field is a button, not a focusable text input, so tapping it
    // never raises the on-screen keyboard.
    const field = await screen.findByRole('button', { name: /I know language/i });
    expect(field.tagName).toBe('BUTTON');

    fireEvent.click(field);

    const listbox = await screen.findByRole('listbox');
    expect(listbox).toBeInTheDocument();
    // Opening the sheet must not auto-focus the search input.
    expect(document.activeElement?.tagName).not.toBe('INPUT');

    // The search input lives inside the sheet and still filters the list.
    const search = screen.getByRole('combobox', { name: /I know language/i });
    fireEvent.change(search, { target: { value: 'span' } });
    const filtered = screen.getAllByRole('option');
    expect(filtered).toHaveLength(1);
    expect(filtered[0]).toHaveTextContent(/es/i);

    fireEvent.click(filtered[0]);

    await waitFor(() => {
      expect(screen.queryByRole('listbox')).not.toBeInTheDocument();
    });
    expect(localStorage.getItem('get-word-landing-pair')).toBe(
      JSON.stringify({ from: 'es', wantsOwnList: true }),
    );
  });

  it('dismisses the touch sheet when the backdrop is tapped', async () => {
    stubCoarsePointer();
    render(<LandingPage />);

    fireEvent.click(await screen.findByRole('button', { name: /I know language/i }));
    const listbox = await screen.findByRole('listbox');

    // The backdrop is the sheet list's fixed ancestor; tapping it closes.
    const backdrop = listbox.closest('.onboarding-combobox-backdrop') as HTMLElement;
    fireEvent.click(backdrop);

    await waitFor(() => {
      expect(screen.queryByRole('listbox')).not.toBeInTheDocument();
    });
  });

  it('disables the language already selected on the other side', async () => {
    render(<LandingPage />);

    fireEvent.focus(document.getElementById('landing-language-from') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /cs/i }));

    fireEvent.focus(document.getElementById('landing-language-to') as Element);
    expect(await screen.findByRole('option', { name: /cs/i })).toBeDisabled();
  });

  it('does not prefill the target language from a stored pair after reload', async () => {
    localStorage.setItem('get-word-landing-pair', JSON.stringify({ from: 'cs', to: 'id' }));

    render(<LandingPage />);

    const targetInput = document.getElementById('landing-language-to') as HTMLInputElement;
    expect(targetInput.parentElement).toHaveClass('onboarding-combobox-highlight');
    expect(targetInput.parentElement).toHaveTextContent('Select a language');
    expect(targetInput.parentElement).not.toHaveTextContent('Indonesian');
  });

  it('treats creating a custom list as the default landing path', async () => {
    render(<LandingPage />);

    expect(
      screen.queryByRole('checkbox', { name: /create my own vocabulary list/i }),
    ).not.toBeInTheDocument();

    fireEvent.focus(document.getElementById('landing-language-from') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /cs/i }));

    fireEvent.focus(document.getElementById('landing-language-to') as Element);
    fireEvent.click(await screen.findByRole('option', { name: /id/i }));

    fireEvent.click(document.querySelector('.lp-btn-hero') as Element);

    expect(localStorage.getItem('get-word-landing-pair')).toBe(
      JSON.stringify({ from: 'cs', to: 'id', wantsOwnList: true }),
    );
  });

  it('keeps the target language empty when the visitor has not picked one yet', async () => {
    render(<LandingPage />);

    await screen.findByText('yes');
    fireEvent.click(document.querySelector('.lp-btn-hero') as Element);

    const saved = JSON.parse(localStorage.getItem('get-word-landing-pair') ?? '{}') as {
      from?: string;
      to?: string;
    };
    expect(saved.from).toBeTruthy();
    expect(saved.to).toBeUndefined();
  });

  it('does not invent a target language when the sticky header CTA is used', async () => {
    render(<LandingPage />);

    await screen.findByText('yes');
    fireEvent.click(document.querySelector('.lp-btn-ghost') as Element);

    const saved = JSON.parse(localStorage.getItem('get-word-landing-pair') ?? '{}') as {
      from?: string;
      to?: string;
    };
    expect(saved.from).toBeTruthy();
    expect(saved.to).toBeUndefined();
  });

  it('shows a loading status while generated landing copy loads', async () => {
    const translationGate = { resolve: () => {} };
    vi.mocked(fetch).mockImplementation(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.startsWith('/api/i18n/messages')) {
        await new Promise<void>((resolve) => {
          translationGate.resolve = resolve;
        });
        return {
          ok: true,
          json: async () => ({
            status: 'autogenerated',
            messages: {
              'landing.hero.title': 'Palabras que se quedan',
            },
          }),
        } as Response;
      }
      return {
        ok: true,
        json: async () => ({
          languages: [
            { code: 'en', name: 'English', source: 'common', flag: '🇬🇧' },
            { code: 'es', name: 'Spanish', source: 'google', flag: '🇪🇸' },
          ],
        }),
      } as Response;
    });

    render(<LandingPage />);

    fireEvent.click(screen.getByRole('button', { name: 'App language' }));
    fireEvent.click(await screen.findByRole('option', { name: /Spanish|español/i }));

    expect(await screen.findByRole('status')).toHaveTextContent('Loading language');

    translationGate.resolve();

    expect(await screen.findByRole('heading', { name: 'Palabras que se quedan' })).toBeInTheDocument();
    await waitFor(() => {
      expect(screen.queryByRole('status')).not.toBeInTheDocument();
    });
  });
});
