import { NextRequest, NextResponse } from "next/server";
import { and, asc, desc, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { getListById } from "@/lib/db";
import {
  getListLanguageCodeVariants,
  normalizeListLanguageCode,
} from "@/lib/db/queries/word-list-items/lists";
import { userListSubscriptions, users, wordLists } from "@/lib/db/schema";
import { resolveUserFromRequest, unauthorizedResponse } from "@/lib/auth";
import { serializeWordList } from "@/lib/word-list-dto";

type RouteContext = { params: Promise<{ id: string }> };

/**
 * POST /api/lists/[id]/promote-common
 *
 * Promotes a freshly autogenerated onboarding list into the shared,
 * recommended common list for its language pair: public + recommended +
 * autogenerated, owned by the app editor rather than the learner who
 * triggered generation. The caller (who just created the list) is then
 * subscribed so it stays their active list.
 *
 * Only the list's current owner may promote it, and the app must have an
 * editor account to own the shared recommendation. The final promotion runs
 * under a per-language-pair advisory lock so concurrent generators do not race
 * the partial unique recommendation index.
 */
export async function POST(request: NextRequest, context: RouteContext) {
  const user = await resolveUserFromRequest(request);
  if (!user) return unauthorizedResponse();

  const { id: listId } = await context.params;
  const list = await getListById(listId);
  if (!list) {
    return NextResponse.json({ error: "List not found" }, { status: 404 });
  }
  if (list.ownerId !== user.id) {
    return NextResponse.json(
      { error: "Only the list creator can promote it" },
      { status: 403 },
    );
  }

  try {
    const result = await db.transaction(async (tx) => {
      const lockKey = `word_lists:recommended:${normalizeListLanguageCode(list.languageFrom)}:${normalizeListLanguageCode(list.languageTo)}`;
      await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey})::bigint)`);

      const [current] = await tx
        .select()
        .from(wordLists)
        .where(eq(wordLists.id, listId))
        .limit(1);
      if (!current) return { status: 404 as const, error: "List not found" };
      if (current.ownerId !== user.id) {
        return { status: 403 as const, error: "Only the list creator can promote it" };
      }
      // Promotion publishes a list to everyone, so it is limited to what this
      // route exists for: a list the generator just produced. A hand-written
      // list would be user content going public without review (guideline 1.2)
      // and must go through the editor-owned publish path instead.
      if (!current.isAutogenerated) {
        return {
          status: 403 as const,
          error: "Only a generated list can be promoted to the shared recommendation",
        };
      }

      const [editor] = await tx
        .select({ id: users.id })
        .from(users)
        .where(eq(users.userRole, "editor"))
        .orderBy(asc(users.createdAt))
        .limit(1);
      if (!editor) {
        return {
          status: 503 as const,
          error: "No editor account is configured to own autogenerated common lists.",
        };
      }

      const [existing] = await tx
        .select()
        .from(wordLists)
        .where(
          and(
            eq(wordLists.isRecommended, true),
            inArray(wordLists.languageFrom, getListLanguageCodeVariants(current.languageFrom)),
            inArray(wordLists.languageTo, getListLanguageCodeVariants(current.languageTo)),
          ),
        )
        .orderBy(desc(wordLists.isAutogenerated), desc(wordLists.updatedAt))
        .limit(1);

      if (existing && existing.id !== current.id) {
        await tx
          .insert(userListSubscriptions)
          .values({ userId: user.id, listId: existing.id })
          .onConflictDoNothing();
        return { status: 200 as const, list: existing, reusedExisting: true };
      }

      const [updated] = await tx
        .update(wordLists)
        .set({
          ownerId: editor.id,
          isPublic: true,
          isRecommended: true,
          isAutogenerated: true,
          updatedAt: new Date(),
        })
        .where(eq(wordLists.id, current.id))
        .returning();
      if (!updated) return { status: 500 as const, error: "Promotion failed" };

      await tx
        .insert(userListSubscriptions)
        .values({ userId: user.id, listId: updated.id })
        .onConflictDoNothing();

      return { status: 200 as const, list: updated, reusedExisting: false };
    });

    if ("error" in result) {
      return NextResponse.json({ error: result.error }, { status: result.status });
    }
    return NextResponse.json({
      list: serializeWordList(result.list),
      reused_existing: result.reusedExisting,
    });
  } catch (err) {
    console.error("[Get Word onboarding] promote common failed", err);
    return NextResponse.json({ error: "Promotion failed" }, { status: 500 });
  }
}
