import { NextRequest, NextResponse } from "next/server";
import {
  createUserSubscription,
  getAnyEditorUserId,
  getListById,
  isUserSubscribed,
  updateList,
} from "@/lib/db";
import { resolveUserFromRequest, unauthorizedResponse } from "@/lib/auth";

type RouteContext = { params: Promise<{ id: string }> };

/**
 * POST /api/lists/[id]/promote-common
 *
 * Promotes a freshly autogenerated onboarding list into the shared,
 * recommended common list for its language pair: public + recommended +
 * autogenerated, owned by the app editor rather than the learner who
 * triggered generation. The caller (who just created the list) is then
 * subscribed so it stays their active list.
 *
 * Only the list's current owner may promote it, which bounds this to the
 * just-created list. Stronger authority + per-pair dedupe (advisory lock)
 * is tracked as Phase 2 hardening.
 */
export async function POST(request: NextRequest, context: RouteContext) {
  const user = await resolveUserFromRequest(request);
  if (!user) return unauthorizedResponse();

  const { id: listId } = await context.params;
  const list = await getListById(listId);
  if (!list) {
    return NextResponse.json({ error: "List not found" }, { status: 404 });
  }
  if (list.ownerId !== user.id) {
    return NextResponse.json(
      { error: "Only the list creator can promote it" },
      { status: 403 },
    );
  }

  // App-owned when an editor exists; otherwise keep the creator as owner so
  // the flow still works in environments without a designated editor.
  const editorId = await getAnyEditorUserId();
  const newOwnerId = editorId ?? user.id;

  const updated = await updateList(listId, {
    isPublic: true,
    isRecommended: true,
    isAutogenerated: true,
    ownerId: newOwnerId,
  });
  if (!updated) {
    return NextResponse.json({ error: "Promotion failed" }, { status: 500 });
  }

  // Ownership moved to the editor, so the learner needs a subscription to keep
  // the list as their active list.
  if (newOwnerId !== user.id && !(await isUserSubscribed(user.id, listId))) {
    await createUserSubscription(user.id, listId);
  }

  return NextResponse.json({ list: updated });
}
