import { describe, it, expect, vi, beforeEach } from 'vitest'
import { NextRequest } from 'next/server'

const mockResolveUserFromRequest = vi.fn()
const mockAutogenerateCommonWordListForUser = vi.fn()

vi.mock('@/lib/auth', () => ({
  resolveUserFromRequest: (...args: unknown[]) => mockResolveUserFromRequest(...args),
  unauthorizedResponse: () =>
    new Response(JSON.stringify({ error: 'Authentication required' }), {
      status: 401,
      headers: { 'content-type': 'application/json' },
    }),
}))

vi.mock('@/features/learning/onboarding/server/autogenerate-common-list', () => ({
  autogenerateCommonWordListForUser: (...args: unknown[]) =>
    mockAutogenerateCommonWordListForUser(...args),
}))

import { POST } from '../autogenerate-common/route'
import { OpenRouterChatError } from '@/lib/openrouter-chat'

describe('POST /api/lists/autogenerate-common', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockResolveUserFromRequest.mockResolvedValue({ id: 'user-1', userRole: 'user' })
    mockAutogenerateCommonWordListForUser.mockResolvedValue({
      list: {
        id: 'list-generated',
        ownerId: 'editor-1',
        name: 'Common CS / VI',
        description: 'Autogenerated with Claude Opus 4.8 via OpenRouter.',
        languageFrom: 'cs',
        languageTo: 'vi',
        isPublic: true,
        isRecommended: true,
        isAutogenerated: true,
      },
      itemCount: 120,
      provider: 'openrouter',
      seedKind: 'llm_generated',
      seedListId: null,
      reusedExisting: false,
      translationStats: { reused: 0, generated: 120 },
    })
  })

  it('returns 401 if no user is authenticated', async () => {
    mockResolveUserFromRequest.mockResolvedValue(null)
    const req = new NextRequest('http://localhost:3000/api/lists/autogenerate-common', {
      method: 'POST',
      body: JSON.stringify({ language_from: 'cs', language_to: 'vi' }),
    })

    const res = await POST(req)

    expect(res.status).toBe(401)
    expect(mockAutogenerateCommonWordListForUser).not.toHaveBeenCalled()
  })

  it('validates language pair input before generating', async () => {
    const req = new NextRequest('http://localhost:3000/api/lists/autogenerate-common', {
      method: 'POST',
      body: JSON.stringify({ language_from: 'cs', language_to: 'cs' }),
    })

    const res = await POST(req)
    const body = await res.json()

    expect(res.status).toBe(400)
    expect(body.error).toMatch(/different/)
    expect(mockAutogenerateCommonWordListForUser).not.toHaveBeenCalled()
  })

  it('uses the dedicated onboarding generator for authenticated users', async () => {
    const req = new NextRequest('http://localhost:3000/api/lists/autogenerate-common', {
      method: 'POST',
      body: JSON.stringify({ language_from: 'cz', language_to: 'vi' }),
    })

    const res = await POST(req)
    const body = await res.json()

    expect(res.status).toBe(200)
    expect(mockAutogenerateCommonWordListForUser).toHaveBeenCalledWith({
      userId: 'user-1',
      userRole: 'user',
      languageFrom: 'cs',
      languageTo: 'vi',
    })
    expect(body.list.id).toBe('list-generated')
    expect(body.provider).toBe('openrouter')
    expect(body.item_count).toBe(120)
  })

  it('returns 503 with a clear code when the server OpenRouter key is out of credits', async () => {
    mockAutogenerateCommonWordListForUser.mockRejectedValueOnce(
      new OpenRouterChatError('OpenRouter API error: 402 insufficient credits', false, 402),
    )
    const req = new NextRequest('http://localhost:3000/api/lists/autogenerate-common', {
      method: 'POST',
      body: JSON.stringify({ language_from: 'cs', language_to: 'vi' }),
    })

    const res = await POST(req)
    const body = await res.json()

    expect(res.status).toBe(503)
    expect(body.code).toBe('OPENROUTER_OUT_OF_CREDITS')
    expect(body.error).toMatch(/temporarily unavailable/i)
  })
})
