'use client';

import { useCallback } from 'react';
import {
  assignItemsCategory,
  previewAutogeneratedListRepair,
  repairAutogeneratedList,
  type RepairAutogeneratedListPreview,
} from '@/features/lists/client/actions';
import type { WordList } from '@/features/lists/types';
import type { I18nKey } from '@/lib/i18n/messages';

type Translate = (key: I18nKey, values?: Record<string, string | number>) => string;

export function useListsMaintenanceActions({
  selectedListId,
  applyUpdatedList,
  reloadListDetails,
  setError,
  t,
}: {
  selectedListId: string | null;
  applyUpdatedList: (list: WordList) => void;
  reloadListDetails: () => Promise<unknown>;
  setError: (message: string | null) => void;
  t: Translate;
}) {
  const assignItemCategory = useCallback(async (itemId: string, categoryId: string) => {
    if (!selectedListId) return;
    await assignItemsCategory(selectedListId, [itemId], categoryId);
  }, [selectedListId]);

  const previewAutogeneratedRepair = useCallback(
    (listId: string) => previewAutogeneratedListRepair(listId),
    [],
  );

  const repairAutogenerated = useCallback(async (
    listId: string,
    preview?: RepairAutogeneratedListPreview,
    selectedRepairItemIds?: string[],
  ) => {
    try {
      const result = await repairAutogeneratedList(listId, preview, selectedRepairItemIds);
      applyUpdatedList(result.list);
      await reloadListDetails();
    } catch (error) {
      setError(error instanceof Error ? error.message : t('lists.repairAutogeneratedFailed'));
    }
  }, [applyUpdatedList, reloadListDetails, setError, t]);

  return { assignItemCategory, previewAutogeneratedRepair, repairAutogenerated };
}
