import { createHash } from "crypto";
import { writeFile } from "fs/promises";
import path from "path";
import { enMessages, type I18nMessages } from "@/lib/i18n/locales/en";
import { generatedBundledMessages } from "@/lib/i18n/generated-bundled-messages";
import {
  TOP_PREGENERATED_UI_LANGUAGE_CODES,
  UI_TRANSLATION_WAVES,
} from "@/lib/i18n/pre-generated-languages";
import { normalizeLanguageCode } from "@/lib/i18n/languages";
import { googleTranslate } from "@/lib/translation";

const OUTPUT_PATH = path.join(process.cwd(), "lib/i18n/generated-bundled-messages.ts");
const EXISTING_BUNDLED_LANGUAGES = new Set(["en", "cs", "uk", "vi"]);

function sourceHash(): string {
  return createHash("sha256").update(JSON.stringify(enMessages)).digest("hex");
}

function resolveTargetCodes(): string[] {
  const requested = process.argv.slice(2).filter((arg) => !arg.startsWith("--"));
  const includeSeeded = process.argv.includes("--include-seeded");
  const waveArgument = process.argv.find((arg) => arg.startsWith("--wave="));
  // `!== undefined` rather than a truthiness check so TypeScript narrows the
  // value to the wave keys for the lookup below.
  const wave = waveArgument?.slice("--wave=".length);
  if (wave !== undefined && wave !== "1" && wave !== "2") {
    throw new Error(`[ui-locales] Unknown wave ${wave}; expected --wave=1 or --wave=2.`);
  }
  if (wave && requested.length > 0) {
    throw new Error("[ui-locales] Pass either explicit language codes or --wave, not both.");
  }
  const source = requested.length > 0
    ? requested
    : wave
      ? [...UI_TRANSLATION_WAVES[wave]]
      : [...TOP_PREGENERATED_UI_LANGUAGE_CODES];
  const codes = source.map(normalizeLanguageCode);
  return Array.from(new Set(codes)).filter(
    (code) => includeSeeded || !EXISTING_BUNDLED_LANGUAGES.has(code),
  );
}

function toTsString(messages: Record<string, I18nMessages>): string {
  return `import type { I18nMessages } from "./locales/en";

// Generated by \`pnpm run ui:generate-locales\`.
// Do not edit by hand; rerun the generator after changing English UI messages.
export const generatedBundledMessagesSourceHash = ${JSON.stringify(sourceHash())};

export const generatedBundledMessages = ${JSON.stringify(messages, null, 2)} satisfies Record<string, I18nMessages>;
`;
}

async function generateLanguage(code: string): Promise<I18nMessages> {
  const keys = Object.keys(enMessages) as Array<keyof typeof enMessages>;
  const values = keys.map((key) => enMessages[key]);
  const translated = await googleTranslate(values, "en", code, {
    source: "ui_locale_script",
  });
  const messages: I18nMessages = { ...enMessages };

  translated.forEach((result, index) => {
    if (result.status === "ok" && result.translated) {
      messages[keys[index]] = result.translated;
    }
  });

  const failed = translated.filter((result) => result.status !== "ok").length;
  if (failed > 0) {
    console.warn(`[ui-locales] ${code}: ${failed} messages fell back to English`);
  }

  return messages;
}

async function main() {
  const codes = resolveTargetCodes();
  if (codes.length === 0) {
    console.log("[ui-locales] No target languages selected.");
    return;
  }

  // A later release wave must add to the languages already shipped, not replace
  // them. `--replace` remains available for an intentional full regeneration.
  const generated: Record<string, I18nMessages> = process.argv.includes("--replace")
    ? {}
    : { ...generatedBundledMessages };
  for (const code of codes) {
    console.log(`[ui-locales] Generating ${code}...`);
    generated[code] = await generateLanguage(code);
  }

  await writeFile(OUTPUT_PATH, toTsString(generated), "utf8");
  console.log(
    `[ui-locales] Generated ${codes.length}; wrote ${Object.keys(generated).length} bundled UI locale(s) to ${OUTPUT_PATH}`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
