import { getLocalizedLanguageName, normalizeLanguageCode } from "@/lib/i18n/languages";
import { normalizeListLanguageCode } from "@/lib/db/queries/word-list-items/lists";
import type { WordCategory, WordList, WordListItem } from "@/lib/db/schema";
import type { SourceSide } from "./types";

const RESOURCE_LANGUAGE_RANKS = new Map([
  ["en", 0],
  ["es", 1],
  ["fr", 2],
  ["de", 3],
  ["pt", 4],
  ["it", 5],
  ["cs", 6],
  ["uk", 7],
  ["vi", 8],
]);

function pairKey(languageFrom: string, languageTo: string) {
  return `${normalizeListLanguageCode(languageFrom)}:${normalizeListLanguageCode(languageTo)}`;
}

export function lockKey(languageFrom: string, languageTo: string) {
  return `word_lists:recommended:${pairKey(languageFrom, languageTo)}`;
}

export function getTextForSide(item: WordListItem, side: SourceSide) {
  return side === "known" ? item.textKnown : item.textTarget;
}

export function getLanguageForSide(list: WordList, side: SourceSide) {
  return normalizeLanguageCode(side === "known" ? list.languageFrom : list.languageTo);
}

function getBaseLanguage(code: string) {
  return normalizeListLanguageCode(code).split("-")[0];
}

export function getResourceRank(code: string) {
  return RESOURCE_LANGUAGE_RANKS.get(getBaseLanguage(code)) ?? 100;
}

export function chooseSourceSide(seed: WordList, targetFrom: string, targetTo: string): SourceSide {
  const seedFrom = normalizeLanguageCode(seed.languageFrom);
  const seedTo = normalizeLanguageCode(seed.languageTo);
  if (seedFrom === targetFrom || seedFrom === targetTo) return "known";
  if (seedTo === targetFrom || seedTo === targetTo) return "target";
  return getResourceRank(seedFrom) <= getResourceRank(seedTo) ? "known" : "target";
}

function capitalizeFirst(value: string) {
  return value ? value.charAt(0).toUpperCase() + value.slice(1) : value;
}

// Names the autogenerated list in the user's known language, e.g. "Angličtina - Vietnamština".
export function buildAutogeneratedListName(languageFrom: string, languageTo: string) {
  const fromName = getLocalizedLanguageName(languageFrom, languageFrom);
  const toName = getLocalizedLanguageName(languageTo, languageFrom);
  const from = fromName ? capitalizeFirst(fromName) : languageFrom.toUpperCase();
  const to = toName ? capitalizeFirst(toName) : languageTo.toUpperCase();
  return `${from} - ${to}`;
}

export function cleanText(value: unknown) {
  return typeof value === "string" ? value.trim().replace(/\s+/g, " ") : "";
}

export function cleanCategory(value: unknown) {
  const cleaned = cleanText(value);
  return cleaned || "Common";
}

export function categoryNameForItem(item: WordListItem, categoriesById: Map<string, WordCategory>) {
  return cleanCategory(item.categoryId ? categoriesById.get(item.categoryId)?.name : null);
}
