import { and, asc, desc, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { OpenRouterChatError } from "@/lib/openrouter-chat";
import {
  mediaAssets,
  userListSubscriptions,
  users,
  wordCategories,
  wordListItems,
  wordLists,
  type WordListItem,
} from "@/lib/db/schema";
import { getListLanguageCodeVariants } from "@/lib/db/queries/word-list-items/lists";
import { isPlayableAudioAsset } from "@/lib/audio-assets";
import { normalizeLanguageCode } from "@/lib/i18n/languages";

import { SERVER_AUTOGENERATE_MODEL_LABEL } from "./config";
import type {
  AutogeneratedCommonListResult,
  GenerationProvider,
  PreparedItem,
  SeedKind,
  TranslationStats,
} from "./types";
import {
  buildAutogeneratedListName,
  categoryNameForItem,
  chooseSourceSide,
  cleanText,
  getLanguageForSide,
  getTextForSide,
  lockKey,
} from "./helpers";
import { reserveAutogenerateRateLimit } from "./rate-limit";
import { generateFromOpenRouterSeed, generateNewOpenRouterList } from "./openrouter";
import { generateFromGoogleTranslateSeed } from "./google-fallback";
import { buildSeedCategoryMapping } from "./categories";
import {
  findSeedCandidates,
  loadSeedDetails,
  pickExactSeed,
  pickTranslationSeed,
} from "./seeds";
import { toPreparedItems } from "./items";

export { SERVER_AUTOGENERATE_MODEL } from "./config";
export type { AutogeneratedCommonListResult } from "./types";

async function buildPreparedItems(input: {
  userId: string;
  languageFrom: string;
  languageTo: string;
}): Promise<{
  items: PreparedItem[];
  // Final category names in origin order; insertion preserves this ordering.
  categories: string[];
  provider: GenerationProvider;
  seedKind: SeedKind;
  seedListId: string | null;
  description: string;
  translationStats: TranslationStats;
}> {
  const candidates = await findSeedCandidates();
  const exactSeed = pickExactSeed(candidates, input.languageFrom, input.languageTo);

  if (exactSeed) {
    const { categories, items } = await loadSeedDetails(exactSeed);
    const categoriesById = new Map(categories.map((category) => [category.id, category]));
    const assetIds = items
      .flatMap((item) => [item.knownAudioAssetId, item.audioAssetId])
      .filter((id): id is string => Boolean(id));
    const assets = assetIds.length > 0
      ? await db
          .select()
          .from(mediaAssets)
          .where(inArray(mediaAssets.id, assetIds))
      : [];
    const mediaById = new Map(assets.map((asset) => [asset.id, asset]));
    // Exact seed is already in the requested language pair, so category names are
    // kept as-is; we only preserve their origin order.
    const { orderedNames: categoryNames } = await buildSeedCategoryMapping({
      categories,
      seedLanguageFrom: getLanguageForSide(exactSeed, "known"),
      seedLanguageTo: getLanguageForSide(exactSeed, "target"),
      sourceLanguage: getLanguageForSide(exactSeed, "known"),
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      translate: false,
    });
    const preparedItems = items.map((item) => ({
      textKnown: item.textKnown,
      textTarget: item.textTarget ?? "",
      categoryName: categoryNameForItem(item, categoriesById),
      canonicalWordId: item.id,
      notes: item.notes,
      knownAudioAssetId: isPlayableAudioAsset(mediaById.get(item.knownAudioAssetId ?? ""))
        ? item.knownAudioAssetId
        : null,
      knownAudioStatus: item.knownAudioAssetId ? item.knownAudioStatus : "none",
      audioAssetId: isPlayableAudioAsset(mediaById.get(item.audioAssetId ?? ""))
        ? item.audioAssetId
        : null,
      audioStatus: item.audioAssetId ? item.audioStatus : "none",
    })).filter((item) => item.textKnown && item.textTarget);
    return {
      provider: "seed_copy",
      seedKind: "exact_pair",
      seedListId: exactSeed.id,
      categories: categoryNames,
      description: `Autogenerated common list copied from exact seed "${exactSeed.name}".`,
      items: preparedItems,
      // Exact-pair seed is copied verbatim: every word's translation is reused.
      translationStats: { reused: preparedItems.length, generated: 0 },
    };
  }

  const translationSeed = pickTranslationSeed(candidates, input.languageFrom, input.languageTo);
  if (translationSeed) {
    const { categories, items } = await loadSeedDetails(translationSeed);
    // Reserve the daily quota before any generation work (category-title and item
    // translation both call the LLM), so an over-quota user fails fast and cheap.
    await reserveAutogenerateRateLimit(input.userId);
    const categoriesById = new Map(categories.map((category) => [category.id, category]));
    const sourceSide = chooseSourceSide(translationSeed, input.languageFrom, input.languageTo);
    const sourceLanguage = getLanguageForSide(translationSeed, sourceSide);
    const seedItems = items
      .map((item, index) => ({
        // Index into the full `items` array so generated rows can be re-aligned
        // to their origin item even after empty-source filtering below.
        sourceIndex: index,
        source: cleanText(getTextForSide(item, sourceSide)),
        category: categoryNameForItem(item, categoriesById),
      }))
      .filter((item) => item.source);
    // Categories follow the origin list (same order), translated into the same
    // bilingual titles a fork produces.
    const categoryMapping = await buildSeedCategoryMapping({
      categories,
      seedLanguageFrom: getLanguageForSide(translationSeed, "known"),
      seedLanguageTo: getLanguageForSide(translationSeed, "target"),
      sourceLanguage,
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      translate: true,
    });
    const resolveCategoryName = (seedItem: WordListItem) => {
      const originName = categoryNameForItem(seedItem, categoriesById);
      return categoryMapping.nameMap.get(originName) ?? originName;
    };
    const assetIds = items
      .flatMap((item) => [item.knownAudioAssetId, item.audioAssetId])
      .filter((id): id is string => Boolean(id));
    const assets = assetIds.length > 0
      ? await db
          .select()
          .from(mediaAssets)
          .where(inArray(mediaAssets.id, assetIds))
      : [];
    const mediaById = new Map(assets.map((asset) => [asset.id, asset]));

    // Prefer the LLM for context-aware, category-consistent output. If the
    // donated server key runs out of credits, keep onboarding usable by falling
    // back to Google Translate for the already-curated seed inventory.
    let provider: GenerationProvider = "openrouter";
    let description = `Autogenerated with ${SERVER_AUTOGENERATE_MODEL_LABEL} via OpenRouter from seed "${translationSeed.name}".`;
    let generated;
    try {
      generated = await generateFromOpenRouterSeed({
        languageFrom: input.languageFrom,
        languageTo: input.languageTo,
        sourceLanguage,
        sourceList: translationSeed,
        sourceItems: seedItems,
      });
    } catch (err) {
      if (!(err instanceof OpenRouterChatError) || !err.isOutOfCredits) throw err;
      console.warn("[Get Word onboarding] OpenRouter credits exhausted; using Google Translate fallback", {
        seedListId: translationSeed.id,
        seedListName: translationSeed.name,
        languageFrom: input.languageFrom,
        languageTo: input.languageTo,
      });
      const fallback = await generateFromGoogleTranslateSeed({
        languageFrom: input.languageFrom,
        languageTo: input.languageTo,
        sourceLanguage,
        sourceItems: seedItems,
      });
      if (fallback.length === 0) throw err;
      generated = fallback;
      provider = "google_translate";
      description = `Autogenerated with Google Translate fallback from seed "${translationSeed.name}" after OpenRouter credits were unavailable.`;
    }
    if (generated.length === 0) {
      throw new Error(
        `OpenRouter returned no usable items for seed "${translationSeed.name}".`,
      );
    }
    const preparedItems = toPreparedItems(generated, {
      seedItems: items,
      seedSide: sourceSide,
      seedLanguage: sourceLanguage,
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      mediaById,
      resolveCategoryName,
    });
    return {
      provider,
      seedKind: "translation_base",
      seedListId: translationSeed.id,
      categories: categoryMapping.orderedNames,
      description,
      items: preparedItems,
      // Every word required a translation call (LLM or Google Translate).
      translationStats: { reused: 0, generated: preparedItems.length },
    };
  }

  await reserveAutogenerateRateLimit(input.userId);
  const generated = await generateNewOpenRouterList(input.languageFrom, input.languageTo);
  const preparedItems = toPreparedItems(generated, {
    languageFrom: input.languageFrom,
    languageTo: input.languageTo,
  });
  return {
    provider: "openrouter",
    seedKind: "llm_generated",
    seedListId: null,
    // No origin list to mirror; categories follow the generator's own labels.
    categories: [],
    description: `Autogenerated with ${SERVER_AUTOGENERATE_MODEL_LABEL} via OpenRouter without an existing seed list.`,
    items: preparedItems,
    // Generated from scratch by the LLM: every word's translation is new.
    translationStats: { reused: 0, generated: preparedItems.length },
  };
}

async function findExistingRecommendedForPair(
  tx: Parameters<Parameters<typeof db.transaction>[0]>[0],
  languageFrom: string,
  languageTo: string,
) {
  const [existing] = await tx
    .select()
    .from(wordLists)
    .where(
      and(
        eq(wordLists.isRecommended, true),
        inArray(wordLists.languageFrom, getListLanguageCodeVariants(languageFrom)),
        inArray(wordLists.languageTo, getListLanguageCodeVariants(languageTo)),
      ),
    )
    .orderBy(desc(wordLists.isAutogenerated), desc(wordLists.updatedAt))
    .limit(1);
  return existing ?? null;
}

async function subscribeUserToList(
  tx: Parameters<Parameters<typeof db.transaction>[0]>[0],
  userId: string,
  listId: string,
) {
  await tx
    .insert(userListSubscriptions)
    .values({ userId, listId })
    .onConflictDoNothing();
}

async function reuseExistingRecommendedList(input: {
  userId: string;
  languageFrom: string;
  languageTo: string;
}): Promise<AutogeneratedCommonListResult | null> {
  return db.transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey(input.languageFrom, input.languageTo)})::bigint)`);
    const existing = await findExistingRecommendedForPair(tx, input.languageFrom, input.languageTo);
    if (!existing) return null;

    if (existing.ownerId !== input.userId) {
      await subscribeUserToList(tx, input.userId, existing.id);
    }
    const [{ itemCount } = { itemCount: 0 }] = await tx
      .select({ itemCount: sql<number>`count(*)::int` })
      .from(wordListItems)
      .where(eq(wordListItems.listId, existing.id));
    return {
      list: existing,
      itemCount,
      provider: "reused_existing",
      seedKind: "existing_recommended",
      seedListId: null,
      reusedExisting: true,
      // Whole list reused: no translations were generated.
      translationStats: { reused: itemCount, generated: 0 },
    };
  });
}

export async function autogenerateCommonWordListForUser(input: {
  userId: string;
  languageFrom: string;
  languageTo: string;
}): Promise<AutogeneratedCommonListResult> {
  const languageFrom = normalizeLanguageCode(input.languageFrom);
  const languageTo = normalizeLanguageCode(input.languageTo);
  if (!languageFrom || !languageTo || languageFrom === languageTo) {
    throw new Error("language_from and language_to are required and must be different");
  }

  const existing = await reuseExistingRecommendedList({
    userId: input.userId,
    languageFrom,
    languageTo,
  });
  if (existing) return existing;

  const prepared = await buildPreparedItems({
    userId: input.userId,
    languageFrom,
    languageTo,
  });
  if (prepared.items.length === 0) {
    throw new Error("Could not generate any usable words for this language pair.");
  }

  const created = await db.transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey(languageFrom, languageTo)})::bigint)`);

    const existing = await findExistingRecommendedForPair(tx, languageFrom, languageTo);
    if (existing) {
      if (existing.ownerId !== input.userId) {
        await subscribeUserToList(tx, input.userId, existing.id);
      }
      const [{ itemCount } = { itemCount: 0 }] = await tx
        .select({ itemCount: sql<number>`count(*)::int` })
        .from(wordListItems)
        .where(eq(wordListItems.listId, existing.id));
      return {
        list: existing,
        itemCount,
        provider: "reused_existing" as const,
        seedKind: "existing_recommended" as const,
        seedListId: null,
        reusedExisting: true,
        // Whole list reused: no translations were generated.
        translationStats: { reused: itemCount, generated: 0 },
      };
    }

    const [editor] = await tx
      .select({ id: users.id })
      .from(users)
      .where(eq(users.userRole, "editor"))
      .orderBy(asc(users.createdAt))
      .limit(1);
    if (!editor) {
      throw new Error("No editor account is configured to own autogenerated common lists.");
    }

    const [list] = await tx
      .insert(wordLists)
      .values({
        ownerId: editor.id,
        name: buildAutogeneratedListName(languageFrom, languageTo),
        description: prepared.description,
        languageFrom,
        languageTo,
        isPublic: true,
        isRecommended: true,
        isAutogenerated: true,
      })
      .returning();

    // Create categories in the origin list's order first (only those actually
    // used), then append any leftover labels (e.g. the "Common" fallback or
    // generator-only categories) in their first-seen order.
    const usedCategoryNames = new Set(prepared.items.map((item) => item.categoryName));
    const categoryNames = Array.from(
      new Set([
        ...prepared.categories.filter((name) => usedCategoryNames.has(name)),
        ...prepared.items.map((item) => item.categoryName),
      ]),
    );
    const createdCategories = await tx
      .insert(wordCategories)
      .values(
        categoryNames.map((name, position) => ({
          listId: list.id,
          name,
          position,
          isSystem: false,
        })),
      )
      .returning();
    const categoryByName = new Map(createdCategories.map((category) => [category.name, category.id]));

    await tx
      .insert(wordListItems)
      .values(
        prepared.items.map((item, position) => ({
          listId: list.id,
          categoryId: categoryByName.get(item.categoryName) ?? null,
          canonicalWordId: item.canonicalWordId ?? null,
          position,
          textKnown: item.textKnown,
          textTarget: item.textTarget,
          translationStatus: "translated" as const,
          knownAudioAssetId: item.knownAudioAssetId ?? null,
          knownAudioStatus: item.knownAudioAssetId ? item.knownAudioStatus ?? "ready" : "none",
          audioAssetId: item.audioAssetId ?? null,
          audioStatus: item.audioAssetId ? item.audioStatus ?? "ready" : "none",
          notes: item.notes ?? null,
        })),
      );

    if (list.ownerId !== input.userId) {
      await subscribeUserToList(tx, input.userId, list.id);
    }

    return {
      list,
      itemCount: prepared.items.length,
      provider: prepared.provider,
      seedKind: prepared.seedKind,
      seedListId: prepared.seedListId,
      reusedExisting: false,
      translationStats: prepared.translationStats,
    };
  });

  return created;
}
