import { and, asc, desc, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { OpenRouterChatError } from "@/lib/openrouter-chat";
import {
  mediaAssets,
  userListSubscriptions,
  userProgress,
  users,
  wordCategories,
  wordListItems,
  wordLists,
  type MediaAsset,
  type WordCategory,
  type WordListItem,
} from "@/lib/db/schema";
import { getListLanguageCodeVariants } from "@/lib/db/queries/word-list-items/lists";
import { isPlayableAudioAsset } from "@/lib/audio-assets";
import { normalizeLanguageCode } from "@/lib/i18n/languages";
import { computeContentKey, normalizeText } from "@/lib/progress-key";
import { areAnswersEquivalent } from "@/lib/answer-normalization";
import { normalizeAcceptedAnswersForDisplay } from "@/lib/word-item-accepted-answers";

import { SERVER_AUTOGENERATE_MODEL_LABEL } from "./config";
import type {
  AutogeneratedCommonListRepairPreview,
  AutogeneratedCommonListResult,
  GenerationProvider,
  PreparedItem,
  SeedKind,
  TranslationStats,
  AutogeneratedCommonListRepair,
} from "./types";
import {
  buildAutogeneratedListName,
  categoryNameForItem,
  chooseSourceSide,
  cleanText,
  getLanguageForSide,
  getTextForSide,
  lockKey,
} from "./helpers";
import { reserveAutogenerateRateLimit } from "./rate-limit";
import { generateFromOpenRouterSeed, generateNewOpenRouterList } from "./openrouter";
import { generateFromGoogleTranslateSeed } from "./google-fallback";
import { buildSeedCategoryMapping, swapBilingualTitle } from "./categories";
import {
  findSeedCandidates,
  loadSeedDetails,
  pickRecommendedExactSeed,
  pickReverseExactSeed,
  pickTranslationSeed,
} from "./seeds";
import { toPreparedItems } from "./items";

export type { AutogeneratedCommonListRepairPreview, AutogeneratedCommonListResult } from "./types";

type AutogenerateUserRole = "user" | "editor";

function getPlayableSeedAudio(
  assetId: string | null,
  mediaById: Map<string, MediaAsset>,
) {
  // The asset is confirmed playable, so mark it "ready" regardless of the source
  // item's stored status: a stale "pending"/"failed" would block playback and
  // trigger needless TTS regeneration downstream.
  return isPlayableAudioAsset(mediaById.get(assetId ?? ""))
    ? { assetId, status: "ready" as const }
    : { assetId: null, status: "none" as const };
}

export function prepareReverseSeedItems(input: {
  categories: WordCategory[];
  items: WordListItem[];
  mediaById: Map<string, MediaAsset>;
  categoriesById?: Map<string, WordCategory>;
}): { categories: string[]; items: PreparedItem[] } {
  const categoriesById =
    input.categoriesById ?? new Map(input.categories.map((category) => [category.id, category]));
  const categoryNames = input.categories.map((category) => swapBilingualTitle(category.name));
  const preparedItems = input.items.map((item) => {
    const knownAudio = getPlayableSeedAudio(item.audioAssetId, input.mediaById);
    const targetAudio = getPlayableSeedAudio(item.knownAudioAssetId, input.mediaById);
    return {
      textKnown: item.textTarget ?? "",
      textTarget: item.textKnown,
      categoryName: swapBilingualTitle(categoryNameForItem(item, categoriesById)),
      canonicalWordId: item.id,
      notes: null,
      knownAudioAssetId: knownAudio.assetId,
      knownAudioStatus: knownAudio.status,
      audioAssetId: targetAudio.assetId,
      audioStatus: targetAudio.status,
      // Accepted answers swap sides along with the texts (same as fork's
      // reverse direction handling).
      acceptedKnown: normalizeAcceptedAnswersForDisplay(item.acceptedTarget, item.textTarget),
      acceptedTarget: normalizeAcceptedAnswersForDisplay(item.acceptedKnown, item.textKnown),
    };
  }).filter((item) => item.textKnown && item.textTarget);

  return { categories: categoryNames, items: preparedItems };
}

async function buildPreparedItems(input: {
  userId: string;
  userRole?: AutogenerateUserRole;
  languageFrom: string;
  languageTo: string;
  excludeListIds?: string[];
}): Promise<{
  items: PreparedItem[];
  // Final category names in origin order; insertion preserves this ordering.
  categories: string[];
  provider: GenerationProvider;
  seedKind: SeedKind;
  seedListId: string | null;
  description: string;
  translationStats: TranslationStats;
}> {
  const candidates = await findSeedCandidates({ excludeListIds: input.excludeListIds });
  // Only a public *recommended* exact-direction list may be copied verbatim.
  // Public-but-not-recommended exact lists are unvetted; the UI surfaces them
  // under advanced options for manual selection but Continue never picks them, so
  // autogenerate must not silently adopt one either — fall through to a reverse
  // recommendation or a translated common base instead.
  const exactSeed = pickRecommendedExactSeed(candidates, input.languageFrom, input.languageTo);

  if (exactSeed) {
    const { categories, items } = await loadSeedDetails(exactSeed);
    const categoriesById = new Map(categories.map((category) => [category.id, category]));
    const assetIds = items
      .flatMap((item) => [item.knownAudioAssetId, item.audioAssetId])
      .filter((id): id is string => Boolean(id));
    const assets = assetIds.length > 0
      ? await db
          .select()
          .from(mediaAssets)
          .where(inArray(mediaAssets.id, assetIds))
      : [];
    const mediaById = new Map(assets.map((asset) => [asset.id, asset]));
    // Exact seed is already in the requested language pair, so category names are
    // kept as-is; we only preserve their origin order.
    const { orderedNames: categoryNames } = await buildSeedCategoryMapping({
      categories,
      seedLanguageTo: getLanguageForSide(exactSeed, "target"),
      sourceLanguage: getLanguageForSide(exactSeed, "known"),
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      translate: false,
    });
    const preparedItems = items.map((item) => ({
      textKnown: item.textKnown,
      textTarget: item.textTarget ?? "",
      categoryName: categoryNameForItem(item, categoriesById),
      canonicalWordId: item.id,
      notes: item.notes,
      knownAudioAssetId: isPlayableAudioAsset(mediaById.get(item.knownAudioAssetId ?? ""))
        ? item.knownAudioAssetId
        : null,
      knownAudioStatus: item.knownAudioAssetId ? item.knownAudioStatus : "none",
      audioAssetId: isPlayableAudioAsset(mediaById.get(item.audioAssetId ?? ""))
        ? item.audioAssetId
        : null,
      audioStatus: item.audioAssetId ? item.audioStatus : "none",
      // Verbatim copy keeps the seed's accepted answers as-is.
      acceptedKnown: normalizeAcceptedAnswersForDisplay(item.acceptedKnown, item.textKnown),
      acceptedTarget: normalizeAcceptedAnswersForDisplay(item.acceptedTarget, item.textTarget),
    })).filter((item) => item.textKnown && item.textTarget);
    return {
      provider: "seed_copy",
      seedKind: "exact_pair",
      seedListId: exactSeed.id,
      categories: categoryNames,
      description: `Autogenerated common list copied from exact seed "${exactSeed.name}".`,
      items: preparedItems,
      // Exact-pair seed is copied verbatim: every word's translation is reused.
      translationStats: { reused: preparedItems.length, generated: 0 },
    };
  }

  const reverseSeed = pickReverseExactSeed(candidates, input.languageFrom, input.languageTo);
  if (reverseSeed) {
    const { categories, items } = await loadSeedDetails(reverseSeed);
    const categoriesById = new Map(categories.map((category) => [category.id, category]));
    const assetIds = items
      .flatMap((item) => [item.knownAudioAssetId, item.audioAssetId])
      .filter((id): id is string => Boolean(id));
    const assets = assetIds.length > 0
      ? await db
          .select()
          .from(mediaAssets)
          .where(inArray(mediaAssets.id, assetIds))
      : [];
    const mediaById = new Map(assets.map((asset) => [asset.id, asset]));
    const prepared = prepareReverseSeedItems({
      categories,
      items,
      mediaById,
      categoriesById,
    });
    return {
      provider: "seed_copy",
      seedKind: "reverse_pair",
      seedListId: reverseSeed.id,
      categories: prepared.categories,
      description: `Autogenerated by reversing "${reverseSeed.name}".`,
      items: prepared.items,
      translationStats: { reused: prepared.items.length, generated: 0 },
    };
  }

  const translationSeed = pickTranslationSeed(candidates, input.languageFrom, input.languageTo);
  if (translationSeed) {
    const { categories, items } = await loadSeedDetails(translationSeed);
    // Reserve the daily quota before any generation work (category-title and item
    // translation both call the LLM), so an over-quota user fails fast and cheap.
    await reserveAutogenerateRateLimit(input.userId, input.userRole);
    const categoriesById = new Map(categories.map((category) => [category.id, category]));
    const sourceSide = chooseSourceSide(translationSeed, input.languageFrom, input.languageTo);
    const sourceLanguage = getLanguageForSide(translationSeed, sourceSide);
    const seedItems = items
      .map((item, index) => ({
        // Index into the full `items` array so generated rows can be re-aligned
        // to their origin item even after empty-source filtering below.
        sourceIndex: index,
        source: cleanText(getTextForSide(item, sourceSide)),
        category: categoryNameForItem(item, categoriesById),
      }))
      .filter((item) => item.source);
    // Categories follow the origin list (same order), translated into the same
    // bilingual titles a fork produces.
    const categoryMapping = await buildSeedCategoryMapping({
      categories,
      seedLanguageTo: getLanguageForSide(translationSeed, "target"),
      sourceLanguage,
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      translate: true,
    });
    const resolveCategoryName = (seedItem: WordListItem) => {
      const originName = categoryNameForItem(seedItem, categoriesById);
      return categoryMapping.nameMap.get(originName) ?? originName;
    };
    const assetIds = items
      .flatMap((item) => [item.knownAudioAssetId, item.audioAssetId])
      .filter((id): id is string => Boolean(id));
    const assets = assetIds.length > 0
      ? await db
          .select()
          .from(mediaAssets)
          .where(inArray(mediaAssets.id, assetIds))
      : [];
    const mediaById = new Map(assets.map((asset) => [asset.id, asset]));

    // Prefer the LLM for context-aware, category-consistent output. If the
    // donated server key runs out of credits, keep onboarding usable by falling
    // back to Google Translate for the already-curated seed inventory.
    let provider: GenerationProvider = "openrouter";
    let description = `Autogenerated with ${SERVER_AUTOGENERATE_MODEL_LABEL} via OpenRouter from seed "${translationSeed.name}".`;
    let generated;
    try {
      generated = await generateFromOpenRouterSeed({
        languageFrom: input.languageFrom,
        languageTo: input.languageTo,
        sourceLanguage,
        sourceList: translationSeed,
        sourceItems: seedItems,
      });
    } catch (err) {
      if (!(err instanceof OpenRouterChatError) || !err.isOutOfCredits) throw err;
      console.warn("[Get Word onboarding] OpenRouter credits exhausted; using Google Translate fallback", {
        seedListId: translationSeed.id,
        seedListName: translationSeed.name,
        languageFrom: input.languageFrom,
        languageTo: input.languageTo,
      });
      const fallback = await generateFromGoogleTranslateSeed({
        languageFrom: input.languageFrom,
        languageTo: input.languageTo,
        sourceLanguage,
        sourceItems: seedItems,
      });
      if (fallback.length === 0) throw err;
      generated = fallback;
      provider = "google_translate";
      description = `Autogenerated with Google Translate fallback from seed "${translationSeed.name}" after OpenRouter credits were unavailable.`;
    }
    if (generated.length === 0) {
      throw new Error(
        `OpenRouter returned no usable items for seed "${translationSeed.name}".`,
      );
    }
    const preparedItems = toPreparedItems(generated, {
      seedItems: items,
      seedSide: sourceSide,
      seedLanguage: sourceLanguage,
      languageFrom: input.languageFrom,
      languageTo: input.languageTo,
      mediaById,
      resolveCategoryName,
    });
    return {
      provider,
      seedKind: "translation_base",
      seedListId: translationSeed.id,
      categories: categoryMapping.orderedNames,
      description,
      items: preparedItems,
      // Every word required a translation call (LLM or Google Translate).
      translationStats: { reused: 0, generated: preparedItems.length },
    };
  }

  await reserveAutogenerateRateLimit(input.userId, input.userRole);
  const generated = await generateNewOpenRouterList(input.languageFrom, input.languageTo);
  const preparedItems = toPreparedItems(generated, {
    languageFrom: input.languageFrom,
    languageTo: input.languageTo,
  });
  return {
    provider: "openrouter",
    seedKind: "llm_generated",
    seedListId: null,
    // No origin list to mirror; categories follow the generator's own labels.
    categories: [],
    description: `Autogenerated with ${SERVER_AUTOGENERATE_MODEL_LABEL} via OpenRouter without an existing seed list.`,
    items: preparedItems,
    // Generated from scratch by the LLM: every word's translation is new.
    translationStats: { reused: 0, generated: preparedItems.length },
  };
}

async function findExistingRecommendedForPair(
  tx: Parameters<Parameters<typeof db.transaction>[0]>[0],
  languageFrom: string,
  languageTo: string,
) {
  const [existing] = await tx
    .select()
    .from(wordLists)
    .where(
      and(
        eq(wordLists.isRecommended, true),
        inArray(wordLists.languageFrom, getListLanguageCodeVariants(languageFrom)),
        inArray(wordLists.languageTo, getListLanguageCodeVariants(languageTo)),
      ),
    )
    .orderBy(desc(wordLists.isAutogenerated), desc(wordLists.updatedAt))
    .limit(1);
  return existing ?? null;
}

async function subscribeUserToList(
  tx: Parameters<Parameters<typeof db.transaction>[0]>[0],
  userId: string,
  listId: string,
) {
  await tx
    .insert(userListSubscriptions)
    .values({ userId, listId })
    .onConflictDoNothing();
}

async function reuseExistingRecommendedList(input: {
  userId: string;
  languageFrom: string;
  languageTo: string;
}): Promise<AutogeneratedCommonListResult | null> {
  return db.transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey(input.languageFrom, input.languageTo)})::bigint)`);
    const existing = await findExistingRecommendedForPair(tx, input.languageFrom, input.languageTo);
    if (!existing) return null;

    if (existing.ownerId !== input.userId) {
      await subscribeUserToList(tx, input.userId, existing.id);
    }
    const [{ itemCount } = { itemCount: 0 }] = await tx
      .select({ itemCount: sql<number>`count(*)::int` })
      .from(wordListItems)
      .where(eq(wordListItems.listId, existing.id));
    return {
      list: existing,
      itemCount,
      provider: "reused_existing",
      seedKind: "existing_recommended",
      seedListId: null,
      reusedExisting: true,
      // Whole list reused: no translations were generated.
      translationStats: { reused: itemCount, generated: 0 },
    };
  });
}

export async function autogenerateCommonWordListForUser(input: {
  userId: string;
  userRole?: AutogenerateUserRole;
  languageFrom: string;
  languageTo: string;
}): Promise<AutogeneratedCommonListResult> {
  const languageFrom = normalizeLanguageCode(input.languageFrom);
  const languageTo = normalizeLanguageCode(input.languageTo);
  if (!languageFrom || !languageTo || languageFrom === languageTo) {
    throw new Error("language_from and language_to are required and must be different");
  }

  const existing = await reuseExistingRecommendedList({
    userId: input.userId,
    languageFrom,
    languageTo,
  });
  if (existing) return existing;

  const prepared = await buildPreparedItems({
    userId: input.userId,
    userRole: input.userRole,
    languageFrom,
    languageTo,
  });
  if (prepared.items.length === 0) {
    throw new Error("Could not generate any usable words for this language pair.");
  }

  const created = await db.transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey(languageFrom, languageTo)})::bigint)`);

    const existing = await findExistingRecommendedForPair(tx, languageFrom, languageTo);
    if (existing) {
      if (existing.ownerId !== input.userId) {
        await subscribeUserToList(tx, input.userId, existing.id);
      }
      const [{ itemCount } = { itemCount: 0 }] = await tx
        .select({ itemCount: sql<number>`count(*)::int` })
        .from(wordListItems)
        .where(eq(wordListItems.listId, existing.id));
      return {
        list: existing,
        itemCount,
        provider: "reused_existing" as const,
        seedKind: "existing_recommended" as const,
        seedListId: null,
        reusedExisting: true,
        // Whole list reused: no translations were generated.
        translationStats: { reused: itemCount, generated: 0 },
      };
    }

    const [editor] = await tx
      .select({ id: users.id })
      .from(users)
      .where(eq(users.userRole, "editor"))
      .orderBy(asc(users.createdAt))
      .limit(1);
    if (!editor) {
      throw new Error("No editor account is configured to own autogenerated common lists.");
    }

    const [list] = await tx
      .insert(wordLists)
      .values({
        ownerId: editor.id,
        name: buildAutogeneratedListName(languageFrom, languageTo),
        description: prepared.description,
        languageFrom,
        languageTo,
        isPublic: true,
        isRecommended: true,
        isAutogenerated: true,
      })
      .returning();

    // Create categories in the origin list's order first (only those actually
    // used), then append any leftover labels (e.g. the "Common" fallback or
    // generator-only categories) in their first-seen order.
    const usedCategoryNames = new Set(prepared.items.map((item) => item.categoryName));
    const categoryNames = Array.from(
      new Set([
        ...prepared.categories.filter((name) => usedCategoryNames.has(name)),
        ...prepared.items.map((item) => item.categoryName),
      ]),
    );
    const createdCategories = await tx
      .insert(wordCategories)
      .values(
        categoryNames.map((name, position) => ({
          listId: list.id,
          name,
          position,
          isSystem: false,
        })),
      )
      .returning();
    const categoryByName = new Map(createdCategories.map((category) => [category.name, category.id]));

    await tx
      .insert(wordListItems)
      .values(
        prepared.items.map((item, position) => ({
          listId: list.id,
          categoryId: categoryByName.get(item.categoryName) ?? null,
          canonicalWordId: item.canonicalWordId ?? null,
          position,
          textKnown: item.textKnown,
          textTarget: item.textTarget,
          acceptedKnown: item.acceptedKnown ?? [],
          acceptedTarget: item.acceptedTarget ?? [],
          translationStatus: "translated" as const,
          knownAudioAssetId: item.knownAudioAssetId ?? null,
          knownAudioStatus: item.knownAudioAssetId ? item.knownAudioStatus ?? "ready" : "none",
          audioAssetId: item.audioAssetId ?? null,
          audioStatus: item.audioAssetId ? item.audioStatus ?? "ready" : "none",
          notes: item.notes ?? null,
        })),
      );

    if (list.ownerId !== input.userId) {
      await subscribeUserToList(tx, input.userId, list.id);
    }

    return {
      list,
      itemCount: prepared.items.length,
      provider: prepared.provider,
      seedKind: prepared.seedKind,
      seedListId: prepared.seedListId,
      reusedExisting: false,
      translationStats: prepared.translationStats,
    };
  });

  return created;
}

export async function repairAutogeneratedCommonWordList(input: {
  listId: string;
  userId: string;
  userRole?: AutogenerateUserRole;
  preview?: AutogeneratedCommonListRepairPreview;
}): Promise<AutogeneratedCommonListResult> {
  const [list] = await db
    .select()
    .from(wordLists)
    .where(eq(wordLists.id, input.listId))
    .limit(1);
  if (!list) throw new Error("List not found");

  const languageFrom = normalizeLanguageCode(list.languageFrom);
  const languageTo = normalizeLanguageCode(list.languageTo);
  if (!languageFrom || !languageTo || languageFrom === languageTo) {
    throw new Error("List has an invalid language pair");
  }

  const prepared = input.preview ?? await buildPreparedItems({
    userId: input.userId,
    userRole: input.userRole,
    languageFrom,
    languageTo,
    // Repair must never copy the broken list as the seed for itself.
    excludeListIds: [input.listId],
  });
  if (prepared.items.length === 0) {
    throw new Error("Could not generate any usable replacement words.");
  }

  return db.transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey(languageFrom, languageTo)})::bigint)`);

    const [current] = await tx
      .select()
      .from(wordLists)
      .where(eq(wordLists.id, input.listId))
      .limit(1)
      .for("update");
    if (!current) throw new Error("List not found");
    if (normalizeLanguageCode(current.languageFrom) !== languageFrom || normalizeLanguageCode(current.languageTo) !== languageTo) {
      throw new Error("List language pair changed during repair");
    }

    const oldItems = await tx
      .select()
      .from(wordListItems)
      .where(eq(wordListItems.listId, input.listId));

    await tx
      .delete(wordCategories)
      .where(eq(wordCategories.listId, input.listId));

    const usedCategoryNames = new Set(prepared.items.map((item) => item.categoryName));
    const categoryNames = Array.from(
      new Set([
        ...prepared.categories.filter((name) => usedCategoryNames.has(name)),
        ...prepared.items.map((item) => item.categoryName),
      ]),
    );
    const createdCategories = categoryNames.length > 0
      ? await tx
          .insert(wordCategories)
          .values(
            categoryNames.map((name, position) => ({
              listId: input.listId,
              name,
              position,
              isSystem: false,
            })),
          )
          .returning()
      : [];
    const categoryByName = new Map(createdCategories.map((category) => [category.name, category.id]));

    const oldItemsByContentKey = new Map<string, typeof oldItems>();
    await Promise.all(
      oldItems.map(async (item) => {
        const key = await computeContentKey({
          languageFrom,
          languageTo,
          textKnown: item.textKnown,
          textTarget: item.textTarget,
          ignoreCase: item.ignoreCase,
        });
        if (!key) return;
        oldItemsByContentKey.set(key, [...(oldItemsByContentKey.get(key) ?? []), item]);
      }),
    );

    const retainedItemIds = new Set<string>();
    const itemsToInsert: Array<typeof wordListItems.$inferInsert> = [];

    for (const [position, item] of prepared.items.entries()) {
      const key = await computeContentKey({
        languageFrom,
        languageTo,
        textKnown: item.textKnown,
        textTarget: item.textTarget,
      });
      const reusableItems = key ? oldItemsByContentKey.get(key) : undefined;
      const existing = reusableItems?.shift();
      if (key && reusableItems && reusableItems.length === 0) {
        oldItemsByContentKey.delete(key);
      }

      const knownAudioAssetId = item.knownAudioAssetId ?? existing?.knownAudioAssetId ?? null;
      const audioAssetId = item.audioAssetId ?? existing?.audioAssetId ?? null;
      const row = {
        listId: input.listId,
        categoryId: categoryByName.get(item.categoryName) ?? null,
        canonicalWordId: item.canonicalWordId ?? existing?.canonicalWordId ?? null,
        position,
        ignoreCase: false,
        textKnown: item.textKnown,
        textTarget: item.textTarget,
        // Rows reuse by content key, so `existing` always has identical texts —
        // user-curated answers stay valid and win; fresh generations fill the
        // rest. A row without a match gets the generated variants (if any).
        acceptedKnown: existing?.acceptedKnown?.length
          ? existing.acceptedKnown
          : item.acceptedKnown ?? [],
        acceptedTarget: existing?.acceptedTarget?.length
          ? existing.acceptedTarget
          : item.acceptedTarget ?? [],
        translationStatus: "translated" as const,
        knownAudioAssetId,
        knownAudioStatus: knownAudioAssetId
          ? item.knownAudioStatus ?? existing?.knownAudioStatus ?? "ready"
          : "none" as const,
        audioAssetId,
        audioStatus: audioAssetId
          ? item.audioStatus ?? existing?.audioStatus ?? "ready"
          : "none" as const,
        notes: item.notes ?? existing?.notes ?? null,
        comment: existing?.comment ?? null,
        updatedAt: new Date(),
      };

      if (existing) {
        retainedItemIds.add(existing.id);
        await tx
          .update(wordListItems)
          .set(row)
          .where(eq(wordListItems.id, existing.id));
      } else {
        itemsToInsert.push(row);
      }
    }

    const staleItemIds = oldItems
      .map((item) => item.id)
      .filter((id) => !retainedItemIds.has(id));
    if (staleItemIds.length > 0) {
      await tx
        .update(userProgress)
        .set({ archivedAt: new Date(), updatedAt: new Date() })
        .where(inArray(userProgress.wordListItemId, staleItemIds));
      await tx
        .delete(wordListItems)
        .where(inArray(wordListItems.id, staleItemIds));
    }

    if (itemsToInsert.length > 0) {
      await tx
        .insert(wordListItems)
        .values(itemsToInsert);
    }

    const [updated] = await tx
      .update(wordLists)
      .set({
        description: prepared.description,
        isAutogenerated: true,
        updatedAt: new Date(),
      })
      .where(eq(wordLists.id, input.listId))
      .returning();
    if (!updated) throw new Error("List repair failed");

    return {
      list: updated,
      itemCount: prepared.items.length,
      provider: prepared.provider,
      seedKind: prepared.seedKind,
      seedListId: prepared.seedListId,
      reusedExisting: false,
      translationStats: prepared.translationStats,
    };
  });
}

function normalizedRepairText(value: string | null | undefined) {
  return normalizeText(value ?? "", { ignoreCase: false });
}

export function acceptedAnswersForRepairedSide(
  currentText: string | null | undefined,
  proposedText: string | null | undefined,
  currentAnswers: unknown,
  proposedAnswers: unknown = [],
) {
  if (areAnswersEquivalent(currentText, proposedText)) {
    return normalizeAcceptedAnswersForDisplay(currentAnswers, proposedText);
  }
  return normalizeAcceptedAnswersForDisplay(proposedAnswers, proposedText);
}

function takeFirstAvailable(
  map: Map<string, PreparedItem[]>,
  key: string,
  used: Set<PreparedItem>,
) {
  const items = map.get(key);
  if (!items) return null;
  while (items.length > 0) {
    const item = items.shift()!;
    if (!used.has(item)) {
      if (items.length === 0) map.delete(key);
      return item;
    }
  }
  map.delete(key);
  return null;
}

async function buildRepairPreviewFromPrepared(input: {
  listId: string;
  languageFrom: string;
  languageTo: string;
  prepared: {
    items: PreparedItem[];
    categories: string[];
    provider: GenerationProvider;
    seedKind: SeedKind;
    seedListId: string | null;
    description: string;
    translationStats: TranslationStats;
  };
}): Promise<AutogeneratedCommonListRepairPreview> {
  const [categories, currentItems] = await Promise.all([
    db
      .select()
      .from(wordCategories)
      .where(eq(wordCategories.listId, input.listId))
      .orderBy(asc(wordCategories.position)),
    db
      .select()
      .from(wordListItems)
      .where(eq(wordListItems.listId, input.listId))
      .orderBy(asc(wordListItems.position)),
  ]);
  const categoriesById = new Map(categories.map((category) => [category.id, category]));

  const proposedByKnown = new Map<string, PreparedItem[]>();
  const proposedByTarget = new Map<string, PreparedItem[]>();
  for (const item of input.prepared.items) {
    const knownKey = normalizedRepairText(item.textKnown);
    const targetKey = normalizedRepairText(item.textTarget);
    if (knownKey) proposedByKnown.set(knownKey, [...(proposedByKnown.get(knownKey) ?? []), item]);
    if (targetKey) proposedByTarget.set(targetKey, [...(proposedByTarget.get(targetKey) ?? []), item]);
  }

  const repairs: AutogeneratedCommonListRepair[] = [];
  const unchanged: AutogeneratedCommonListRepairPreview["unchanged"] = [];
  const usedProposals = new Set<PreparedItem>();
  const currentTargetsByKnown = new Map<string, Set<string>>();
  for (const item of currentItems) {
    const knownKey = normalizedRepairText(item.textKnown);
    const targetKey = normalizedRepairText(item.textTarget);
    if (!knownKey || !targetKey) continue;
    const targets = currentTargetsByKnown.get(knownKey) ?? new Set<string>();
    targets.add(targetKey);
    currentTargetsByKnown.set(knownKey, targets);
  }

  for (const current of currentItems) {
    const key = normalizedRepairText(current.textKnown);
    let proposed = key ? takeFirstAvailable(proposedByKnown, key, usedProposals) : null;
    let reason: AutogeneratedCommonListRepair["reason"] = "translation";
    const currentCategoryName = categoryNameForItem(current, categoriesById);
    if (!proposed) {
      const targetKey = normalizedRepairText(current.textTarget);
      const suspiciousKnown =
        key === normalizedRepairText(currentCategoryName) ||
        (currentTargetsByKnown.get(key)?.size ?? 0) > 1;
      proposed = targetKey && suspiciousKnown
        ? takeFirstAvailable(proposedByTarget, targetKey, usedProposals)
        : null;
      reason = "known_side";
    }

    if (!proposed) {
      unchanged.push({
        itemId: current.id,
        textKnown: current.textKnown,
        textTarget: current.textTarget,
        categoryName: currentCategoryName,
      });
      continue;
    }
    usedProposals.add(proposed);

    const knownSame = normalizedRepairText(current.textKnown) === normalizedRepairText(proposed.textKnown);
    const targetSame = normalizedRepairText(current.textTarget) === normalizedRepairText(proposed.textTarget);
    if (knownSame && targetSame) {
      unchanged.push({
        itemId: current.id,
        textKnown: current.textKnown,
        textTarget: current.textTarget,
        categoryName: currentCategoryName,
      });
      continue;
    }

    repairs.push({
      currentItemId: current.id,
      textKnown: current.textKnown,
      proposedTextKnown: proposed.textKnown,
      currentTextTarget: current.textTarget,
      proposedTextTarget: proposed.textTarget,
      acceptedKnown: normalizeAcceptedAnswersForDisplay(
        proposed.acceptedKnown,
        proposed.textKnown,
      ),
      acceptedTarget: normalizeAcceptedAnswersForDisplay(
        proposed.acceptedTarget,
        proposed.textTarget,
      ),
      currentCategoryName,
      proposedCategoryName: proposed.categoryName,
      reason,
      knownAudioAssetId: proposed.knownAudioAssetId ?? null,
      knownAudioStatus: proposed.knownAudioStatus ?? "none",
      audioAssetId: proposed.audioAssetId ?? null,
      audioStatus: proposed.audioStatus ?? "none",
      canonicalWordId: proposed.canonicalWordId ?? current.canonicalWordId ?? null,
      notes: proposed.notes ?? null,
      selectedByDefault: true,
    });
  }

  const ignoredSuggestionCount = input.prepared.items.filter((item) => !usedProposals.has(item)).length;
  const usedCategoryNames = new Set(input.prepared.items.map((item) => item.categoryName));
  const previewCategories = Array.from(
    new Set([
      ...input.prepared.categories.filter((name) => usedCategoryNames.has(name)),
      ...input.prepared.items.map((item) => item.categoryName),
    ]),
  );

  return {
    itemCount: input.prepared.items.length,
    categoryCount: previewCategories.length,
    provider: input.prepared.provider,
    seedKind: input.prepared.seedKind,
    seedListId: input.prepared.seedListId,
    description: input.prepared.description,
    categories: previewCategories,
    items: input.prepared.items,
    repairs,
    unchanged,
    ignoredSuggestionCount,
    translationStats: input.prepared.translationStats,
  };
}

export async function applyAutogeneratedCommonWordListRepairs(input: {
  listId: string;
  userId: string;
  preview: AutogeneratedCommonListRepairPreview;
  selectedRepairItemIds: string[];
}): Promise<AutogeneratedCommonListResult> {
  const [list] = await db
    .select()
    .from(wordLists)
    .where(eq(wordLists.id, input.listId))
    .limit(1);
  if (!list) throw new Error("List not found");

  const languageFrom = normalizeLanguageCode(list.languageFrom);
  const languageTo = normalizeLanguageCode(list.languageTo);
  if (!languageFrom || !languageTo || languageFrom === languageTo) {
    throw new Error("List has an invalid language pair");
  }

  const selectedIds = new Set(input.selectedRepairItemIds);
  const selectedRepairs = input.preview.repairs.filter((repair) => selectedIds.has(repair.currentItemId));

  return db.transaction(async (tx) => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${lockKey(languageFrom, languageTo)})::bigint)`);

    const [currentList] = await tx
      .select()
      .from(wordLists)
      .where(eq(wordLists.id, input.listId))
      .limit(1)
      .for("update");
    if (!currentList) throw new Error("List not found");
    if (normalizeLanguageCode(currentList.languageFrom) !== languageFrom || normalizeLanguageCode(currentList.languageTo) !== languageTo) {
      throw new Error("List language pair changed during repair");
    }

    if (selectedRepairs.length > 0) {
      const itemIds = selectedRepairs.map((repair) => repair.currentItemId);
      const currentItems = await tx
        .select()
        .from(wordListItems)
        .where(inArray(wordListItems.id, itemIds))
        .for("update");
      const currentById = new Map(currentItems.map((item) => [item.id, item]));
      const insertRows: Array<typeof wordListItems.$inferInsert> = [];

      for (const repair of selectedRepairs) {
        const current = currentById.get(repair.currentItemId);
        if (!current || current.listId !== input.listId) {
          throw new Error("List changed since the repair preview was prepared");
        }
        if (
          normalizedRepairText(current.textKnown) !== normalizedRepairText(repair.textKnown) ||
          normalizedRepairText(current.textTarget) !== normalizedRepairText(repair.currentTextTarget)
        ) {
          throw new Error("List changed since the repair preview was prepared");
        }

        insertRows.push({
          listId: input.listId,
          categoryId: current.categoryId,
          canonicalWordId: repair.canonicalWordId ?? current.canonicalWordId ?? null,
          position: current.position,
          ignoreCase: current.ignoreCase,
          textKnown: repair.proposedTextKnown,
          textTarget: repair.proposedTextTarget,
          acceptedKnown: acceptedAnswersForRepairedSide(
            current.textKnown,
            repair.proposedTextKnown,
            current.acceptedKnown,
            repair.acceptedKnown,
          ),
          acceptedTarget: acceptedAnswersForRepairedSide(
            current.textTarget,
            repair.proposedTextTarget,
            current.acceptedTarget,
            repair.acceptedTarget,
          ),
          translationStatus: "translated" as const,
          knownAudioAssetId: repair.knownAudioAssetId ?? (
            normalizedRepairText(current.textKnown) === normalizedRepairText(repair.proposedTextKnown)
              ? current.knownAudioAssetId
              : null
          ),
          knownAudioStatus: repair.knownAudioAssetId
            ? repair.knownAudioStatus ?? "ready"
            : normalizedRepairText(current.textKnown) === normalizedRepairText(repair.proposedTextKnown) && current.knownAudioAssetId
              ? current.knownAudioStatus
              : "none",
          audioAssetId: repair.audioAssetId ?? null,
          audioStatus: repair.audioAssetId ? repair.audioStatus ?? "ready" : "none",
          notes: repair.notes ?? null,
          comment: null,
        });
      }

      await tx
        .update(userProgress)
        .set({ archivedAt: new Date(), updatedAt: new Date() })
        .where(inArray(userProgress.wordListItemId, itemIds));
      await tx
        .delete(wordListItems)
        .where(inArray(wordListItems.id, itemIds));
      await tx
        .insert(wordListItems)
        .values(insertRows);
    }

    const [updated] = await tx
      .update(wordLists)
      .set({ updatedAt: new Date() })
      .where(eq(wordLists.id, input.listId))
      .returning();
    if (!updated) throw new Error("List repair failed");

    return {
      list: updated,
      itemCount: selectedRepairs.length,
      provider: input.preview.provider,
      seedKind: input.preview.seedKind,
      seedListId: input.preview.seedListId,
      reusedExisting: false,
      translationStats: input.preview.translationStats,
    };
  });
}

export async function previewAutogeneratedCommonWordListRepair(input: {
  listId: string;
  userId: string;
  userRole?: AutogenerateUserRole;
}): Promise<AutogeneratedCommonListRepairPreview> {
  const [list] = await db
    .select()
    .from(wordLists)
    .where(eq(wordLists.id, input.listId))
    .limit(1);
  if (!list) throw new Error("List not found");

  const languageFrom = normalizeLanguageCode(list.languageFrom);
  const languageTo = normalizeLanguageCode(list.languageTo);
  if (!languageFrom || !languageTo || languageFrom === languageTo) {
    throw new Error("List has an invalid language pair");
  }

  const prepared = await buildPreparedItems({
    userId: input.userId,
    userRole: input.userRole,
    languageFrom,
    languageTo,
    // Repair must never copy the broken list as the seed for itself.
    excludeListIds: [input.listId],
  });
  if (prepared.items.length === 0) {
    throw new Error("Could not generate any usable replacement words.");
  }

  return buildRepairPreviewFromPrepared({
    listId: input.listId,
    languageFrom,
    languageTo,
    prepared,
  });
}
