import { sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { oauthRateLimits } from "@/lib/db/schema";

const RATE_BUCKET_PREFIX = "onboarding_common_autogenerate";
const DEFAULT_USER_DAILY_LIMIT = 3;
const DEFAULT_EDITOR_DAILY_LIMIT = 25;
const DEFAULT_GLOBAL_DAILY_LIMIT = 50;
type AutogenerateRateLimitRole = "user" | "editor";

function parsePositiveInt(value: string | undefined, fallback: number) {
  if (!value) return fallback;
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : fallback;
}

function getMaxUserGenerationsPerDay() {
  return parsePositiveInt(
    process.env.OPENROUTER_SERVER_AUTOGENERATE_USER_DAILY_LIMIT,
    DEFAULT_USER_DAILY_LIMIT,
  );
}

function getMaxEditorGenerationsPerDay() {
  return parsePositiveInt(
    process.env.OPENROUTER_SERVER_AUTOGENERATE_EDITOR_DAILY_LIMIT,
    DEFAULT_EDITOR_DAILY_LIMIT,
  );
}

function getMaxGlobalGenerationsPerDay() {
  return parsePositiveInt(
    process.env.OPENROUTER_SERVER_AUTOGENERATE_GLOBAL_DAILY_LIMIT,
    DEFAULT_GLOBAL_DAILY_LIMIT,
  );
}

function getUtcDayStart(date = new Date()) {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
}

export function getAutogenerateDailyLimitForRole(role: AutogenerateRateLimitRole) {
  return role === "editor" ? getMaxEditorGenerationsPerDay() : getMaxUserGenerationsPerDay();
}

export async function reserveAutogenerateRateLimit(
  userId: string,
  role: AutogenerateRateLimitRole = "user",
) {
  const bucketStart = getUtcDayStart();
  const bucketStartSql = bucketStart.toISOString();
  const buckets = [
    {
      key: `${RATE_BUCKET_PREFIX}:user:${userId}`,
      limit: getAutogenerateDailyLimitForRole(role),
      message: "Daily autogenerated list limit reached for this account.",
    },
    {
      key: `${RATE_BUCKET_PREFIX}:global`,
      limit: getMaxGlobalGenerationsPerDay(),
      message: "Daily autogenerated list limit reached. Please try again tomorrow.",
    },
  ];

  for (const bucket of buckets) {
    const rows = await db.execute(
      sql`
        INSERT INTO ${oauthRateLimits} (
          bucket_key,
          bucket_start,
          request_count,
          created_at,
          updated_at
        )
        VALUES (${bucket.key}, ${bucketStartSql}::timestamp, 1, now(), now())
        ON CONFLICT (bucket_key, bucket_start)
        DO UPDATE SET
          request_count = ${oauthRateLimits.requestCount} + 1,
          updated_at = now()
        WHERE ${oauthRateLimits.requestCount} < ${bucket.limit}
        RETURNING request_count
      `,
    );
    if (rows.length === 0) {
      throw new Error(bucket.message);
    }
  }
}
