import { asc, desc, eq, sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { wordCategories, wordListItems, wordLists, type WordList } from "@/lib/db/schema";
import {
  getListLanguageCodeVariants,
  normalizeListLanguageCode,
} from "@/lib/db/queries/word-list-items/lists";
import { MAX_GENERATED_ITEMS } from "./config";
import { getResourceRank } from "./helpers";
import type { SeedCandidate } from "./types";

export async function findSeedCandidates() {
  const itemCounts = db
    .select({
      listId: wordListItems.listId,
      itemCount: sql<number>`count(*)::int`.as("item_count"),
    })
    .from(wordListItems)
    .groupBy(wordListItems.listId)
    .as("item_counts");

  return db
    .select({
      id: wordLists.id,
      ownerId: wordLists.ownerId,
      name: wordLists.name,
      description: wordLists.description,
      languageFrom: wordLists.languageFrom,
      languageTo: wordLists.languageTo,
      isPublic: wordLists.isPublic,
      isCommon: wordLists.isCommon,
      isRecommended: wordLists.isRecommended,
      isAutogenerated: wordLists.isAutogenerated,
      shareToken: wordLists.shareToken,
      createdAt: wordLists.createdAt,
      updatedAt: wordLists.updatedAt,
      itemCount: sql<number>`coalesce(${itemCounts.itemCount}, 0)::int`,
    })
    .from(wordLists)
    .leftJoin(itemCounts, eq(wordLists.id, itemCounts.listId))
    .where(eq(wordLists.isPublic, true))
    .orderBy(desc(wordLists.isCommon), desc(wordLists.isRecommended), desc(wordLists.updatedAt))
    .limit(80);
}

function scoreTranslationSeed(seed: SeedCandidate, languageFrom: string, languageTo: string) {
  const seedFrom = normalizeListLanguageCode(seed.languageFrom);
  const seedTo = normalizeListLanguageCode(seed.languageTo);
  const targetFrom = normalizeListLanguageCode(languageFrom);
  const targetTo = normalizeListLanguageCode(languageTo);
  const overlaps = [seedFrom, seedTo].filter((code) => code === targetFrom || code === targetTo).length;
  const bestResourceRank = Math.min(getResourceRank(seedFrom), getResourceRank(seedTo));
  let score = 0;
  if (seed.isCommon) score += 1000;
  if (seed.isRecommended) score += 200;
  score += overlaps * 100;
  score += Math.min(seed.itemCount, MAX_GENERATED_ITEMS);
  score -= bestResourceRank * 5;
  return score;
}

export function pickExactSeed(candidates: SeedCandidate[], languageFrom: string, languageTo: string) {
  const fromVariants = getListLanguageCodeVariants(languageFrom);
  const toVariants = getListLanguageCodeVariants(languageTo);
  return candidates
    .filter((seed) =>
      fromVariants.includes(normalizeListLanguageCode(seed.languageFrom)) &&
      toVariants.includes(normalizeListLanguageCode(seed.languageTo)) &&
      seed.itemCount > 0
    )
    .sort((a, b) =>
      Number(b.isRecommended) - Number(a.isRecommended) ||
      Number(b.isCommon) - Number(a.isCommon) ||
      b.itemCount - a.itemCount ||
      b.updatedAt.getTime() - a.updatedAt.getTime()
    )[0] ?? null;
}

export function pickRecommendedExactSeed(candidates: SeedCandidate[], languageFrom: string, languageTo: string) {
  return pickExactSeed(
    candidates.filter((seed) => seed.isPublic && seed.isRecommended),
    languageFrom,
    languageTo,
  );
}

export function pickReverseExactSeed(candidates: SeedCandidate[], languageFrom: string, languageTo: string) {
  return pickExactSeed(
    candidates.filter((seed) => seed.isPublic && seed.isRecommended),
    languageTo,
    languageFrom,
  );
}

export function pickTranslationSeed(candidates: SeedCandidate[], languageFrom: string, languageTo: string) {
  return candidates
    .filter((seed) => seed.itemCount > 0)
    .sort((a, b) =>
      scoreTranslationSeed(b, languageFrom, languageTo) -
        scoreTranslationSeed(a, languageFrom, languageTo) ||
      b.updatedAt.getTime() - a.updatedAt.getTime()
    )[0] ?? null;
}

export async function loadSeedDetails(seed: WordList) {
  const [categories, items] = await Promise.all([
    db
      .select()
      .from(wordCategories)
      .where(eq(wordCategories.listId, seed.id))
      .orderBy(asc(wordCategories.position)),
    db
      .select()
      .from(wordListItems)
      .where(eq(wordListItems.listId, seed.id))
      .orderBy(asc(wordListItems.position))
      .limit(MAX_GENERATED_ITEMS),
  ]);
  return { categories, items };
}
