import type { WordList } from "@/lib/db/schema";

export type SourceSide = "known" | "target";
export type GenerationProvider =
  | "openrouter"
  | "google_translate"
  | "seed_copy"
  | "reused_existing";
export type SeedKind = "exact_pair" | "reverse_pair" | "translation_base" | "llm_generated";

export type TranslationStats = { reused: number; generated: number };

export type AutogeneratedCommonListResult = {
  list: WordList;
  itemCount: number;
  provider: GenerationProvider;
  seedKind: SeedKind | "existing_recommended";
  seedListId: string | null;
  reusedExisting: boolean;
  // Per-word reuse vs. generation counts for the translations of this list.
  translationStats: TranslationStats;
};

export type AutogeneratedCommonListRepairPreview = {
  itemCount: number;
  categoryCount: number;
  provider: GenerationProvider;
  seedKind: SeedKind;
  seedListId: string | null;
  description: string;
  categories: string[];
  items: PreparedItem[];
  repairs: AutogeneratedCommonListRepair[];
  unchanged: AutogeneratedCommonListUnchangedItem[];
  ignoredSuggestionCount: number;
  translationStats: TranslationStats;
};

export type AutogeneratedCommonListRepair = {
  currentItemId: string;
  textKnown: string;
  proposedTextKnown: string;
  currentTextTarget: string | null;
  proposedTextTarget: string;
  currentCategoryName: string;
  proposedCategoryName: string;
  reason: "translation" | "known_side";
  knownAudioAssetId?: string | null;
  knownAudioStatus?: "none" | "pending" | "ready" | "failed";
  audioAssetId?: string | null;
  audioStatus?: "none" | "pending" | "ready" | "failed";
  canonicalWordId?: string | null;
  notes?: string | null;
  selectedByDefault: boolean;
};

export type AutogeneratedCommonListUnchangedItem = {
  itemId: string;
  textKnown: string;
  textTarget: string | null;
  categoryName: string;
};

export type SeedCandidate = WordList & { itemCount: number };

export type PreparedItem = {
  textKnown: string;
  textTarget: string;
  categoryName: string;
  knownAudioAssetId?: string | null;
  knownAudioStatus?: "none" | "pending" | "ready" | "failed";
  audioAssetId?: string | null;
  audioStatus?: "none" | "pending" | "ready" | "failed";
  canonicalWordId?: string | null;
  notes?: string | null;
};

export type GeneratedCommonItem = {
  known: string;
  target: string;
  category?: string | null;
  // Index into the origin seed list for seed-based generation; lets us re-align
  // generated rows to their source item even if the model drops or reorders
  // entries. Absent for from-scratch (no-seed) generation.
  sourceIndex?: number;
};
