import type { WordList } from "@/lib/db/schema";

export type SourceSide = "known" | "target";
export type GenerationProvider = "openrouter" | "seed_copy" | "reused_existing";
export type SeedKind = "exact_pair" | "translation_base" | "llm_generated";

export type AutogeneratedCommonListResult = {
  list: WordList;
  itemCount: number;
  provider: GenerationProvider;
  seedKind: SeedKind | "existing_recommended";
  seedListId: string | null;
  reusedExisting: boolean;
};

export type SeedCandidate = WordList & { itemCount: number };

export type PreparedItem = {
  textKnown: string;
  textTarget: string;
  categoryName: string;
  knownAudioAssetId?: string | null;
  knownAudioStatus?: "none" | "pending" | "ready" | "failed";
  audioAssetId?: string | null;
  audioStatus?: "none" | "pending" | "ready" | "failed";
  canonicalWordId?: string | null;
  notes?: string | null;
};

export type GeneratedCommonItem = {
  known: string;
  target: string;
  category?: string | null;
  // Index into the origin seed list for seed-based generation; lets us re-align
  // generated rows to their source item even if the model drops or reorders
  // entries. Absent for from-scratch (no-seed) generation.
  sourceIndex?: number;
};
