'use client';

import { useI18n } from '@/components/I18nProvider';
import { useAppStateContext } from '@/context/AppStateContext';
import { SettingsLanguagePicker } from '@/components/SettingsLanguagePicker';
import { Section } from './primitives';

export function LanguageSection() {
  const { t, isAutogenerated } = useI18n();
  const { settingsLanguage, setSettingsLanguage } = useAppStateContext();

  return (
    <Section label={t('language.sectionLabel')}>
      <SettingsLanguagePicker
        value={settingsLanguage}
        onChange={setSettingsLanguage}
        compact
      />
      {isAutogenerated && (
        <p className="m-0 text-xs leading-relaxed text-text-soft">
          {t('language.autogeneratedNotice')}
        </p>
      )}
    </Section>
  );
}
