import { afterEach, describe, expect, it, vi } from "vitest";
import { getAutogenerateDailyLimitForRole } from "../rate-limit";

vi.mock("@/lib/db/client", () => ({
  db: { execute: vi.fn() },
}));

describe("autogenerate common list rate limits", () => {
  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("uses a higher default daily limit for editor accounts", () => {
    expect(getAutogenerateDailyLimitForRole("user")).toBe(3);
    expect(getAutogenerateDailyLimitForRole("editor")).toBe(25);
  });

  it("allows the editor daily limit to be configured separately", () => {
    vi.stubEnv("OPENROUTER_SERVER_AUTOGENERATE_USER_DAILY_LIMIT", "4");
    vi.stubEnv("OPENROUTER_SERVER_AUTOGENERATE_EDITOR_DAILY_LIMIT", "40");

    expect(getAutogenerateDailyLimitForRole("user")).toBe(4);
    expect(getAutogenerateDailyLimitForRole("editor")).toBe(40);
  });
});
