import { describe, expect, it, vi } from "vitest";
import type { MediaAsset, WordCategory, WordListItem } from "@/lib/db/schema";
import { prepareReverseSeedItems } from "../index";
import { pickRecommendedExactSeed, pickReverseExactSeed } from "../seeds";
import type { SeedCandidate } from "../types";

vi.mock("@/lib/db/client", () => ({ db: {} }));

function category(id: string, name: string, position: number): WordCategory {
  return {
    id,
    listId: "seed-list",
    name,
    position,
    isSystem: false,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  };
}

function item(input: Partial<WordListItem> & Pick<WordListItem, "id" | "textKnown" | "textTarget">): WordListItem {
  return {
    id: input.id,
    listId: "seed-list",
    categoryId: input.categoryId ?? null,
    canonicalWordId: input.canonicalWordId ?? null,
    position: input.position ?? 0,
    ignoreCase: input.ignoreCase ?? false,
    textKnown: input.textKnown,
    textTarget: input.textTarget,
    translationStatus: input.translationStatus ?? "translated",
    knownAudioAssetId: input.knownAudioAssetId ?? null,
    knownAudioStatus: input.knownAudioStatus ?? "none",
    audioAssetId: input.audioAssetId ?? null,
    audioStatus: input.audioStatus ?? "none",
    notes: input.notes ?? null,
    comment: input.comment ?? null,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
  };
}

function playableAsset(id: string): MediaAsset {
  return {
    id,
    contentHash: `hash-${id}`,
    storageType: "object_store",
    storageProvider: "b2",
    storageRef: `audio/${id}.mp3`,
    mediaType: "audio",
    provider: "google_tts",
    language: "cs",
    textReference: "text",
    sizeBytes: null,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  };
}

function unplayableAsset(id: string): MediaAsset {
  return {
    ...playableAsset(id),
    storageType: "r2",
  };
}

function seedCandidate(input: Partial<SeedCandidate> & Pick<SeedCandidate, "id">): SeedCandidate {
  return {
    id: input.id,
    ownerId: input.ownerId ?? null,
    name: input.name ?? input.id,
    description: input.description ?? null,
    languageFrom: input.languageFrom ?? "cs",
    languageTo: input.languageTo ?? "vi",
    isPublic: input.isPublic ?? true,
    isCommon: input.isCommon ?? false,
    isRecommended: input.isRecommended ?? false,
    isAutogenerated: input.isAutogenerated ?? false,
    shareToken: input.shareToken ?? null,
    createdAt: input.createdAt ?? new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: input.updatedAt ?? new Date("2026-01-01T00:00:00.000Z"),
    itemCount: input.itemCount ?? 10,
  };
}

describe("prepareReverseSeedItems", () => {
  it("swaps text, audio, statuses, and bilingual category titles", () => {
    const categories = [
      category("cat-1", "Greetings - Pozdravy", 0),
      category("cat-2", "Plain", 1),
    ];
    const mediaById = new Map([
      ["asset-known", playableAsset("asset-known")],
      ["asset-target", playableAsset("asset-target")],
      ["asset-unplayable", unplayableAsset("asset-unplayable")],
    ]);

    const result = prepareReverseSeedItems({
      categories,
      mediaById,
      items: [
        item({
          id: "item-1",
          categoryId: "cat-1",
          textKnown: "hello",
          textTarget: "ahoj",
          knownAudioAssetId: "asset-known",
          knownAudioStatus: "ready",
          audioAssetId: "asset-target",
          audioStatus: "pending",
          notes: "source-side note",
        }),
        item({
          id: "item-2",
          categoryId: "cat-2",
          textKnown: "food",
          textTarget: "jidlo",
          knownAudioAssetId: "asset-unplayable",
          knownAudioStatus: "ready",
          audioAssetId: null,
          audioStatus: "ready",
        }),
      ],
    });

    expect(result.categories).toEqual(["Pozdravy - Greetings", "Plain"]);
    expect(result.items).toEqual([
      expect.objectContaining({
        textKnown: "ahoj",
        textTarget: "hello",
        categoryName: "Pozdravy - Greetings",
        canonicalWordId: "item-1",
        notes: null,
        // A playable asset is always marked "ready", even if the source item's
        // stored status was stale ("pending" here).
        knownAudioAssetId: "asset-target",
        knownAudioStatus: "ready",
        audioAssetId: "asset-known",
        audioStatus: "ready",
      }),
      expect.objectContaining({
        textKnown: "jidlo",
        textTarget: "food",
        categoryName: "Plain",
        knownAudioAssetId: null,
        knownAudioStatus: "none",
        audioAssetId: null,
        audioStatus: "none",
      }),
    ]);
  });
});

describe("pickReverseExactSeed", () => {
  it("only reverses public recommended seed lists", () => {
    const publicOnly = seedCandidate({
      id: "public-only",
      isPublic: true,
      isRecommended: false,
      itemCount: 100,
    });
    const privateRecommended = seedCandidate({
      id: "private-recommended",
      isPublic: false,
      isRecommended: true,
      itemCount: 200,
    });
    const publicRecommended = seedCandidate({
      id: "public-recommended",
      isPublic: true,
      isRecommended: true,
      itemCount: 5,
    });

    expect(
      pickReverseExactSeed(
        [publicOnly, privateRecommended, publicRecommended],
        "vi",
        "cs",
      )?.id,
    ).toBe("public-recommended");
  });
});

describe("pickRecommendedExactSeed", () => {
  it("only copies public recommended exact-direction seed lists", () => {
    const publicOnly = seedCandidate({
      id: "public-only",
      languageFrom: "cs",
      languageTo: "vi",
      isPublic: true,
      isRecommended: false,
      itemCount: 100,
    });
    const privateRecommended = seedCandidate({
      id: "private-recommended",
      languageFrom: "cs",
      languageTo: "vi",
      isPublic: false,
      isRecommended: true,
      itemCount: 200,
    });
    const publicRecommended = seedCandidate({
      id: "public-recommended",
      languageFrom: "cs",
      languageTo: "vi",
      isPublic: true,
      isRecommended: true,
      itemCount: 5,
    });

    expect(
      pickRecommendedExactSeed(
        [publicOnly, privateRecommended, publicRecommended],
        "cs",
        "vi",
      )?.id,
    ).toBe("public-recommended");
  });

  it("returns null when only a public-but-not-recommended exact seed exists", () => {
    const publicOnly = seedCandidate({
      id: "public-only",
      languageFrom: "cs",
      languageTo: "vi",
      isPublic: true,
      isRecommended: false,
      itemCount: 100,
    });

    expect(pickRecommendedExactSeed([publicOnly], "cs", "vi")).toBeNull();
  });
});
