/**
 * Store-review and QA accounts that study nothing real.
 *
 * They arrive in waves from the closed-testing programmes the app stores
 * require, so they dominate registrations and devices while contributing no
 * retention — the dashboard is unreadable with them mixed in, and misleading
 * with them silently gone. `testerScope` on the admin stats query switches
 * between the two populations instead.
 *
 * Kept out of `features/admin` on purpose: these are real personal email
 * addresses, and only the server may hold the list. The client learns how many
 * there are from the stats payload, never who.
 */
const TESTER_ACCOUNT_EMAIL_SOURCE = [
  'support@testerscommunity.com',
  'lyracalder36@gmail.com',
  'setiawanbayu1974@gmail.com',
  'kloe.watson42@gmail.com',
  'brokgames32@gmail.com',
  'jacksgill807@gmail.com',
  'nimali.fernando2001@gmail.com',
  'arthurhazel88@gmail.com',
  'rahul.deshmukh8765@gmail.com',
  'khanapatro739@gmail.com',
  'omaralfars24@gmail.com',
  'vivaanmehta223@gmail.com',
  'charlote.evans88@gmail.com',
  'yuvrajmajomder@gmail.com',
  'asityapranata@gmail.com',
  'anapopescur57@gmail.com',
  'stevenharrys218@gmail.com',
  'frau.holle625@gmail.com',
  'sanduni.ratnayake45@gmail.com',
  'montgregamore@gmail.com',
  'grace.andersob91@gmail.com',
  'henryowens889@gmail.com',
  'miinjikim687@gmail.com',
  'emma.collinjsr@gmail.com',
  'leonsmark45@gmail.com',
  'minnha653@gmail.com',
  'kaiwen.lim23@gmail.com',
  'campuskai22@gmail.com',
  'karlpeters516@gmail.com',
  'iam.shreeshant4@gmail.com',
  'saikrina0@gmail.com',
  'rachin4325@gmail.com',
  'mason.reedx5@gmail.com',
  'prankjihoon@gmail.com',
  'samwillks24@gmail.com',
  'nattanon.k91@gmail.com',
  'yodhust@gmail.com',
  'logantaylor1656@gmail.com',
  'thabo.mokona2002@gmail.com',
  'fathimaalhasmi@gmail.com',
  'nancystark100@gmail.com',
  'pavanmudhiraj2024@gmail.com',
  'olivia.martin0809@gmail.com',
  'michealscrook@gmail.com',
  'winsley3245@gmail.com',
  'thanakorn.pit4@gmail.com',
  'kavyanairs45@gmail.com',
  'srisuk.nattapong18@gmail.com',
  'diegorami862@gmail.com',
  'sriskupimlada@gmail.com',
  'chandragupta0809@gmail.com',
  'ethan.parkeghr1960@gmail.com',
  'navarrodieg47@gmail.com',
  'alex.kurner069@gmail.com',
  'kevinwong5648@gmail.com',
  'noahwark25@gmail.com',
  'rohitsinghsr682@gmail.com',
  'fajarsuryant50@gmail.com',
  'benjamin.haye314@gmail.com',
  'arianajone45@gmail.com',
  'amandajason448@gmail.com',
  'tharindu.silveshwar@gmail.com',
  'dhattaaman@gmail.com',
  'roston913@gmail.com',
  'mark.a.mendoza2004@gmail.com',
  'devdinish10@gmail.com',
  'mattadams941@gmail.com',
  'sayuikdan@gmail.com',
  'jack.morison374@gmail.com',
  'leoharry497@gmail.com',
  'vickyverma.tech@gmail.com',
  'elmasrychinedu@gmail.com',
  'supriya1367i@gmail.com',
  'lukas.eeider8@gmail.com',
  'leoniesami78@gmail.com',
  'satyakarthik789@gmail.com',
  'saikrishna.chala4@gmail.com',
  'gwijayagalan@gmail.com',
  'wilstonjade6@gmail.com',
  'jasperlucas024@gmail.com',
  'clarissaong5@gmail.com',
  'vikramkrishna574@gmail.com',
  'briankenns6@gmail.com',
  'mikeshaun141@gmail.com',
  'availejackson@gmail.com',
  'lukasmuc434@gmail.com',
  'liamconnoy@gmail.com',
  'chamathsakariya@gmail.com',
  'gabrieambr@gmail.com',
  'martinharryson134@gmail.com',
  'tomsonwalker44@gmail.com',
  'martincoo46@gmail.com',
  'ardiansyahpro26@gmail.com',
  'scottwingston470@gmail.com',
  'freyaswheeler15@gmail.com',
  'aisyaa9346@gmail.com',
  'sehakulkarni@gmail.com',
  'rubyfletcher852@gmail.com',
  'sumandhaju2@gmail.com',
  'ahemdelmasry25@gmail.com',
  'takasan697@gmail.com',
  'oliverhayes443@gmail.com',
  'phanmlan30@gmail.com',
  'lilythedev56@gmail.com',
  'morrisonhorks@gmail.com',
  'wandererd800@gmail.com',
  'harutsaito@gmail.com',
  'mousadiop82@gmail.com',
  'jakemillers964@gmail.com',
  'slyviamarie9@gmail.com',
  'vishnumanne89@gmail.com',
  'agusrahardho@gmail.com',
  'samwhitman67@gmail.com',
  'elarabrooks85@gmail.com',
  'nikhilpati30@gmail.com',
  'likithpyata22@gmail.com',
  'susanharts12@gmail.com',
  'rizkypratamayr86@gmail.com',
  'nuraisyahrahman75@gmail.com',
  'gillswalter40@gmail.com',
  'ramentsuki8@gmail.com',
  'obrienseamus30@gmail.com',
  'finleyredmont@gmail.com',
  'asiyahjackson0@gmail.com',
  'conarhenry@gmail.com',
  'elenapetrovavr@gmail.com',
  'manishchowdhury65@gmail.com',
  'rodgerkenneth7@gmail.com',
  'jiahuilim03@gmail.com',
  'arjunvishwanadhan4@gmail.com',
  'machtyson62@gmail.com',
  'lilyracheler@gmail.com',
  'wurstw68@gmail.com',
  'emilyrosesb68@gmail.com',
  'noahtremblay23@gmail.com',
  'minhnguyeny9@gmail.com',
] as const;

/** Lowercased and de-duplicated; the SQL compares against `lower(email)`. */
export const TESTER_ACCOUNT_EMAILS: string[] = Array.from(
  new Set(TESTER_ACCOUNT_EMAIL_SOURCE.map((email) => email.trim().toLowerCase()))
);
