import { and, eq } from 'drizzle-orm';

import { db } from '../client';
import { webPushSubscriptions } from '../schema';

export interface WebPushSubscriptionInput {
  endpoint: string;
  p256dh: string;
  auth: string;
  userAgent: string | null;
}

/** Endpoint ownership is deliberately updated on conflict: browser push
 * subscriptions are regenerated by the UA and may later belong to a newly
 * authenticated account on the same physical device. */
export async function upsertWebPushSubscription(
  userId: string,
  subscription: WebPushSubscriptionInput,
): Promise<void> {
  await db.insert(webPushSubscriptions).values({
    userId,
    endpoint: subscription.endpoint,
    p256dh: subscription.p256dh,
    auth: subscription.auth,
    userAgent: subscription.userAgent,
    updatedAt: new Date(),
  }).onConflictDoUpdate({
    target: webPushSubscriptions.endpoint,
    set: {
      userId,
      p256dh: subscription.p256dh,
      auth: subscription.auth,
      userAgent: subscription.userAgent,
      updatedAt: new Date(),
      failureCount: 0,
      lastFailureAt: null,
    },
  });
}

export async function deleteWebPushSubscription(userId: string, endpoint: string): Promise<void> {
  await db.delete(webPushSubscriptions).where(and(
    eq(webPushSubscriptions.userId, userId),
    eq(webPushSubscriptions.endpoint, endpoint),
  ));
}
